<?php include PATH_TPL."/manage/tpl.header.phtml";?>
<style>
.form{height:40px; line-height:40px;float:right;margin:10px 0;}
.date{width:150px; height:11px; line-height:11px; padding:5px; border:1px #AA9FFF solid; cursor:pointer; background:url(../images/dateIco.png) no-repeat right center;}
.calender{ width:200px; margin:50px auto; top:0; left:0; border:4px #D6D6D6 solid; background:#EBEBEB; position:absolute; display:none; z-index:999;}
.calendertb{width:100%;}
.calendertb td{width:35px; height:30px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; font-size:14px; font-weight:bold;}
.calendertb td.hover,.calendertb td.weekendhover{background:#D6D6D6;}
.calendertb th{width:35px; height:30px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; color:#979797; }
.tdtoday{ background:#0080FF;color:#fff;width:35px; height:35px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; font-size:14px; font-weight:bold;}
.getyear{ height:35px; line-height:35px; width:100%; text-align:center;}
.preMonth{ font-size:14px; font-weight:bold; cursor:pointer; margin-right:18px;color:#0080FF;}
.nextMonth{ font-size:14px; font-weight:bold; cursor:pointer; margin-left:18px;color:#0080FF;}
.zhezhao{width:100%; height:100%; position:fixed; z-index:998;	background:#fff;filter:alpha(opacity=10);opacity:0.1; display:none; }
.select{width:100px; height:24px; border:2px #AA9FFF solid;}
</style>
<link rel="stylesheet" type="text/css" href="/css/calendar/jquery.datetimepicker.css"/>
<script src="/js/calendar/jquery.datetimepicker.js"></script>
<div class="mod">
	<div class="hd">
		<h3 class="title">变更用户资产记录</h3>
		<form method="post" style="float:right">
			<input name="kw" value="<?if(isset($kw)) echo $kw?>">
			<select id="yaf_field" name="field">
				<option value="uid">uid</option>
			</select>
      		<script>$('#yaf_field').val('<?=isset($field)?$field:'uid'?>')</script>
      		<span style="margin: 0 10px;"><input type="checkbox" name="hasTime" value="1" <?if($hasTime==1){?>checked<?}?> >是否筛选时间</span>
      		开始时间:<input type="text" class="date" value="<?=date('Y-m-d H:i', $stime)?>" id="date-start" name="stime" readonly="true" /> 结束时间:<input type="text" class="date" value="<?=date('Y-m-d H:i', $etime)?>" id="date-end" name="etime" readonly="true" />
			<input type="submit" value="搜索">
		</form>
	</div>
	<div class="bd">
	<table class="table_s01">
		<thead>
			<tr>
				<th>id</th>
				<th>操作管理员</th>
				<th>变更资产用户</th>
				<th>资产类别</th>
				<th>变更资产数量</th>
				<th>变更原因</th>
				<th>官方账户</th>
				<th>创建时间</th>
			</tr>
		</thead>
		<tbody>
		<? foreach($datas['list'] as $v1){?>
		<tr>
			<td><?=$v1["id"]?></td>
			<td><?=$v1["admin"]?></td>
			<td><?=$v1["uid"]?></td>
			<td>
				<? $arr = explode('_', $v1['coin']);
				$str = $arr[1] == 'over' ? '可用' : '冻结';
				echo $str.strtoupper($arr[0]); ?>
			</td>
			<td><?=$v1["num"]?></td>
			<td><?=$v1["bak"]?></td>
			<td><?=$v1["official"]?></td>
			<td><?=date('Y-m-d H:i:s', $v1["created"])?></td>
		</tr>
		<?php }?>
		</tbody>
	</table>
	<?=$datas['pageinfo']?>
	</div>
</div>
</body>
</html>
<script>
	$(function(){
		var hasTime = "<?=$hasTime?>";
		if(hasTime==1){
			var start = $('#date-start').val();
			var end = $('#date-end').val();
			$('.pageUl li').each(function(){
				var oldHref = $(this).find('a').attr('href');

				var prega = oldHref.match(/p=(\d*)$/);
				var pregb = oldHref.match(/p=(\d*)&/);
				if( prega != null ){
					var p = prega[1];
				}else if( pregb != null ) {
					var p = pregb[1];
				}else{
					var p = 1;
				}

				var newHref = '?p=' + p + '&hasTime=1&stime=' + start + '&etime=' + end;

				$(this).find('a').attr('href', newHref);
			});
		}
	});
</script>
<script>
	$('#date-start').datetimepicker();
	$('#date-end').datetimepicker();
</script>
