<?php include PATH_TPL . "/manage/tpl.header.phtml" ?>
<style>
	.loginValue{border: 1px solid #D5D5D5;float: left;height: 29px;line-height: 29px;margin-right: 15px;padding: 3px;width: 224px;}
	.res {color:red;}
	.right {text-align: right;color:#236097;}
	#form-box {float: left;width: 500px;}
	#user-assets {margin-top:10px;margin-left:20px;padding: 15px;float: left;text-align: left;width: 300px;min-height: 260px;border: #e3e3e3 1px solid;}
</style>
<div id="form-box">
	<fieldset>
	<legend><h3 class="title">变更用户资产</h3></legend>
	<table class="formtable">
	  <tbody>
			<tr id="flag">
				<th>请输入用户ID</th>
				<td><input type="text" name="uid" id="uid" class="loginValue"/><span style="color:red;">*</span></td>
			</tr>
			<tr>
				<th>变更资产品类</th>
				<td>
					<select name="coin" id="coin" style="width: 232px;">
						<option value="">请选择</option>
						<option value="cny_over">可用CNY</option>
						<option value="cny_lock">冻结CNY</option>
						<? foreach ($pairs as $k => $v) { ?>
							<option value="<?=$v['name']?>_over">可用<?=strtoupper($v['name'])?></option>
							<option value="<?=$v['name']?>_lock">冻结<?=strtoupper($v['name'])?></option>
						<? } ?>
					</select>
				</td>
			</tr>
			<tr>
				<th>变更资产数量</th>
	            <td><input type="text" id="num" class="loginValue" /><span style="color:red;">*&nbsp;例如：-20，扣减20</span></td>
			</tr>
			<tr>
				<th>更改资产理由</th>
	            <td><input type="text" id="bak" class="loginValue" /><span style="color:red;">*</span></td>
			</tr>
			<tr>
				<th>回收到官方账户</th>
	            <td><input type="text" id="admin" class="loginValue" /><span style="color:red;">默认增减资产不进入官方账户</span></td>
			</tr>
	  </tbody>
	</table>
	</fieldset>
	<fieldset><input class="submit" type="submit" value="提交"></fieldset>
</div>
<div id="user-assets">

</div>
<script>
	$('.submit').click(function() {
		var uid = $('#uid').val();
		var coin = $('#coin').val();
		var num = $('#num').val();
		var bak = $('#bak').val();
		var admin = $('#admin').val();

		if(!uid) return alert('请填写用户UID');
		if(!num) return alert('请填写变更数量');
		if(!bak) return alert('请填写变资产原因');
		if(!coin) return alert('请选择需要操作的币种');

		var aj = $.ajax({
					    url:'/manage_user/modifyassets',
					    data:{
					    	uid:uid,
					    	coin:coin,
					    	num:num,
					    	bak:bak,
					    	admin:admin
					    },
					    type:'post',
					    cache:false,
					    dataType:'json',
					    success:function(data) {
					    	if(0 == data.code) {
					            alert("更新资产成功！");
					            window.location.reload();
					    	} else {
					    		alert(data.msg);
					    	}
					     },
					     error : function() {
					        alert("更新资产失败！");
					     }
					});

	});


	$('#uid').blur(function() {
		$('.res').remove();
		var uid = $(this).val();
		if(!uid) return;
		var aj = $.ajax({
					    url:'/manage_user/getassests',
					    data:{
					    	uid:uid
					    },
					    type:'post',
					    cache:false,
					    dataType:'json',
					    success:function(data) {
					    	if(0 == data.code) {
					    		var html = "<p class='res'>姓名："+data.data.name+"</p>";
					    			html += "<p class='res'>邮箱："+data.data.email+"</p>";
					    			html += "<p class='res'>手机号："+data.data.mo+"</p>";
					    			html += "<p class='res'>推荐人ID："+data.data.pid+"</p>";

					    			for( var i in data.data ){
					    				if( i.indexOf('_over') != -1){
					    					var arr = i.split('_');
					    					html += '<p class="res">可用'+arr[0].toUpperCase()+'：'+data.data[i]+'</p>';
					    				}
					    				if( i.indexOf('_lock') != -1){
					    					var arr = i.split('_');
					    					html += '<p class="res">冻结'+arr[0].toUpperCase()+'：'+data.data[i]+'</p>';
					    				}
					    			}

					    		$('#user-assets').html(html);
					    	} else {
					    		alert(data.msg);
					    	}
					     },
					     error : function() {

					     }
					});
	});
</script>
</body>
</html>
