<?php include PATH_TPL."/manage/tpl.header.phtml";?>
<style>
.form{height:40px; line-height:40px;float:right;margin:10px 0;}
.date{width:150px; height:11px; line-height:11px; padding:5px; border:1px #AA9FFF solid; cursor:pointer; background:url(../images/dateIco.png) no-repeat right center;}
.calender{ width:200px; margin:50px auto; top:0; left:0; border:4px #D6D6D6 solid; background:#EBEBEB; position:absolute; display:none; z-index:999;}
.calendertb{width:100%;}
.calendertb td{width:35px; height:30px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; font-size:14px; font-weight:bold;}
.calendertb td.hover,.calendertb td.weekendhover{background:#D6D6D6;}
.calendertb th{width:35px; height:30px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; color:#979797; }
.tdtoday{ background:#0080FF;color:#fff;width:35px; height:35px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; font-size:14px; font-weight:bold;}
.getyear{ height:35px; line-height:35px; width:100%; text-align:center;}
.preMonth{ font-size:14px; font-weight:bold; cursor:pointer; margin-right:18px;color:#0080FF;}
.nextMonth{ font-size:14px; font-weight:bold; cursor:pointer; margin-left:18px;color:#0080FF;}
.zhezhao{width:100%; height:100%; position:fixed; z-index:998;	background:#fff;filter:alpha(opacity=10);opacity:0.1; display:none; }
.select{width:100px; height:24px; border:2px #AA9FFF solid;}
.page{float: left;}
.tongji{min-width:570px;float: right;height: 44px;text-align: right;}
.tongji span{margin-left: 10px;font-size: 17px;color:red;height: 44px;line-height: 44px;}
</style>
<link rel="stylesheet" type="text/css" href="/css/calendar/jquery.datetimepicker.css"/>
<script src="/js/calendar/jquery.datetimepicker.js"></script>

<?$tTS = $type.$status?>
<div class="mod">
	<div class="hd">
		<h3 class="title">人民币</h3>
		<ul class="tabs">
			<li<?if($tTS=='out等待') echo ' class="cur"'?>><a href="/manage_user/rmb/type/out/status/<?=urlencode('等待')?>">等待转出</a></li>
			<li<?if($tTS=='out成功') echo ' class="cur"'?>><a href="/manage_user/rmb/type/out/status/<?=urlencode('成功')?>">成功转出</a></li>
			<li<?if($tTS=='in成功') echo ' class="cur"'?>><a href="/manage_user/rmb/type/in/status/<?=urlencode('成功')?>">充值成功</a></li>
			<li<?if($tTS=='in等待') echo ' class="cur"'?>><a href="/manage_user/rmb/type/in/status/<?=urlencode('等待')?>">充值等待</a></li>
			<li<?if($tTS=='in已取消') echo ' class="cur"'?>><a href="/manage_user/rmb/type/in/status/<?=urlencode('已取消')?>">充值已取消</a></li>
			<li<?if($tTS=='out已取消') echo ' class="cur"'?>><a href="/manage_user/rmb/type/out/status/<?=urlencode('已取消')?>">提现已取消</a></li>
		</ul>
		<!-- <?search_form(array('uid'=>'用户', 'email'=>'邮箱', 'id'=>'订单ID'))?> -->
		<div class="form">
			<form method="post" style="float:left;margin-left:50px;">
				<input class="inputBtn" name="kw" value="<?if(isset($kw))echo $kw;?>">
				<select id="yaf_field" name="field">
			    	<option value="uid">用户ID</option>
			    	<option value="email">邮箱</option>
			    	<option value="id">订单ID</option>
			    	<option value="name">姓名</option>
			    	<option value="account">汇款帐号</option>
				</select>
			  <? if(isset($field)){ ?>
				<script>$('#yaf_field').val('<?=$field?>')</script>
			  <? } ?>
			  <span style="margin: 0 10px;"><input type="checkbox" name="hasTime" value="1" <?if($hasTime==1){?>checked<?}?> >是否筛选时间</span>
				开始时间:<input type="text" class="date" value="<?=date('Y-m-d H:i', $stime)?>" id="date-start" name="stime" readonly="true" /> 结束时间:<input type="text" class="date" value="<?=date('Y-m-d H:i', $etime)?>" id="date-end" name="etime" readonly="true" />
	            	<input type="submit" value="搜索"/>
			<?if($tTS=='in等待'){?><input type="submit" name="cancle_all" value="批量撤销"/><?}?>
	        </form>
        </div>
	</div>
	<div class="bd">
	<table class="table_s01">
		<thead>
			<tr>
				<?if('等待'==$status){?>
				<th style="min-width: 100px;">操作</th>
				<?}?>
				<th>id</th>
				<th>用户id</th>
				<th style="min-width: 60px;">姓名</th>
				<th>邮箱</th>
				<th>金额</th>
				<?if($tTS=='out成功' || $tTS=='out等待'){?><th>实付金额</th><th>手续费</th><?}?>
				<th>汇款单号</th>
				<th>汇款账号</th>
				<th style="min-width: 70px;">开户行</th>
				<th>收款类别</th>
				<?if($tTS=='out成功' || $tTS=='out等待'){?><th>开户行地址</th><?}?>
				<th style="min-width: 150px;">创建时间</th>
				<?if($tTS=='in成功' || $tTS=='out成功'){?><th style="min-width: 150px;">到账时间</th><?}?>
				<th class="hide">创建ip</th>
				<!-- <th <?if($tTS!='in成功') {?>class="hide"<?}?>>更新时间</th> -->
				<th class="hide">更新ip</th>
				<th>备注</th>
			</tr>
		</thead>
		<tbody>

		<?php foreach ($datas['list'] as $v1){?>
		<?
		$tUserMO = new UserModel();
		$level = new UserLevelModel();
		$leveldata = $level->fList();
		$leveluser = level($tUserMO->getById($v1["uid"]),$leveldata);?>
		<tr <?if($leveluser[0]['rmb_out'] && ($tTS=='out等待' || $tTS=='out成功')){?>style="background:#FFFF00"<?}?>>
			<?if($tTS=='out等待'){?>
			<td>
				<? if($btnAuth['user_rmb_outsuccess']){ ?>
					<button onclick="WVKE.confirm('/manage_user/rmbout/id/<?=$v1['id']?>', 'ok')">成功</button>
				<? } ?>
				<? if($btnAuth['user_rmb_outcancel']){ ?>
					<button onclick="WVKE.confirm('/manage_user/rmbout/id/<?=$v1['id']?>/cancel/1', 'ok')">撤消</button>
				<? } ?>
			</td>
			<?}else if($tTS=='in等待'){?>
			<td>
				<button onclick="WVKE.confirm('/manage_user/rmbpay/id/<?=$v1['id']?>', 'ok')">到账</button>
				<? if($btnAuth['user_rmb_incancel']){ ?>
					<button onclick="WVKE.confirm('/manage_user/rmbpay/id/<?=$v1['id']?>/cancel/1', 'ok')">撤消</button>
				<? } ?>
				<a href="/manage_user/modrmbin/id/<?=$v1['id']?>" style="font-size: 12px;">修改</a>
			</td>
			<?}?>
			<td><?=$v1["id"]?></td>
			<td><?=$v1["uid"]?></td>
			<td><?=Tool_Str::safestr($v1["name"])?></td>
			<td><?=$v1["email"]?></td>
			<td><?=Tool_Str::format($v1['money'], 2)?></td>
			<?$level=leveluser($v1["uid"]);
			?>
			<?if($tTS=='out成功' || $tTS=='out等待'){?><td><?=$v1['money_u']==0?Tool_Str::format($v1['money']*0.995, 2):Tool_Str::format($v1['money_u'], 2)?></td><td><?=$v1['money_u']==0?Tool_Str::format($v1['money']*(1-0.995), 2):Tool_Str::format($v1['money'] - $v1['money_u'], 2)?></td><?}?>
			<td><?=Tool_Str::safestr($v1["order"])?></td>
			<td><?=Tool_Str::safestr($v1["account"])?></td>
			<td><?=Tool_Str::safestr($v1["bank"])?></td>
			<td><?=$v1["accounttype"]?></td>
			<?if($tTS=='out成功' || $tTS=='out等待'){?><td>
				<?
					if (!$v1['province']) {
						$v1['province'] = '';
					}
					if (!$v1['city']) {
						$v1['city'] = '';
					}
					if (!$v1['district']) {
						$v1['district'] = '';
					}
					if (!$v1['subbranch']) {
						$v1['subbranch'] = '';
					}
					$bank_address = $v1['province'] . ' ' . $v1['city'] . ' ' . $v1['district'] . ' ' . $v1['subbranch'];
					$bank_address = trim($bank_address);

					if (((int)$bank_address)!=0) {
						$bank_address = '';
					}
				?>
				<?=$bank_address?>
			</td><?}?>
			<td><?=date('Y-m-d H:i:s', $v1["created"])?></td>
			<?if($tTS=='in成功' || $tTS=='out成功'){?><td><?= $v1['updated']==0 ? '' : date('Y-m-d H:i:s', $v1["updated"]) ?></td><?}?>
			<td class="hide"><?=$v1["createip"]?></td>
			<!-- <td <?if($tTS!='in成功') {?>class="hide"<?}?>><?=date('Y-m-d H:i:s', $v1["updated"])?></td> -->
			<td class="hide"><?=$v1["updateip"]?></td>
			<td><?=$v1["bak"]?></td>
		</tr>
		<?php }?>
		</tbody>
	</table>
	<?=$datas['pageinfo']?>
	<p class="tongji">
		<span>总笔数：<?=$datas['total'][0]['num']?></span>
		<span>总金额：<?=(float)$datas['total'][0]['total']?>元</span>
		<? if($tTS=='out等待' || $tTS=='out成功'){ ?>
		<span>总实付金额：<?=(float)$datas['total'][0]['total_u']?>元</span>
		<span>总手续费：<?=round((float)$datas['total'][0]['total']-(float)$datas['total'][0]['total_u'], 2)?>元</span>
		<? } ?>
	</p>
	</div>
</div>
</body>
</html>
<script>
	$(function(){
		// 关键字和搜索字段
		var kw = "<?=$kw?>";
		var field = "<?=$field?>";
		if( kw ){
			var kwstr = '&kw=' + kw + '&field=' + field;
		}else{
			var kwstr = '';
		}

		var hasTime = "<?=$hasTime?>";
		$('.pageUl li').each(function(){
			var oldHref = $(this).find('a').attr('href');

			var prega = oldHref.match(/p=(\d*)$/);
			var pregb = oldHref.match(/p=(\d*)&/);
			if( prega != null ){
				var p = prega[1];
			}else if( pregb != null ) {
				var p = pregb[1];
			}else{
				var p = 1;
			}

			if(hasTime==1){
				var start = $('#date-start').val();
				var end = $('#date-end').val();
				var newHref = '?p=' + p + '&hasTime=1&stime=' + start + '&etime=' + end + kwstr;
			}else{
				var newHref = '?p=' + p + kwstr;
			}

			$(this).find('a').attr('href', newHref);
		});
	});
</script>
<script>
	$('#date-start').datetimepicker();
	$('#date-end').datetimepicker();
</script>
