<?php include PATH_TPL . "/manage/tpl.header.phtml" ?>
<style>
	.loginValue{border: 1px solid #D5D5D5;float: left;height: 29px;line-height: 29px;margin-right: 15px;padding: 3px;width: 400px;}
</style>
<?
	$addressMo = new AddressModel;
	$coinlist = User_CoinModel::getInstance()->getList();
	$adArr = [];
	foreach ($coinlist as $key => $value) {
		$adArr[$value['name']] = $addressMo->getAddr($data['uid'], $value['name']);
	}
?>
<fieldset>
	<legend><h3 class="title">用户</h3></legend>
	<table class="formtable">
		<tbody>
			<tr>
				<th>邮箱</th>
				<td><?=$data["email"]?></td>
			</tr>
			<? /*
			<tr>
				<th>密码</th>
				<td>
					<input id="yaf_pwd" name="pwd"/> 密码为空时不修改密码
				</td>
			</tr>
 			*/?>
 			<tr>
 				<th>角色</th>
 				<td><?=$data["role"]?></td>
 			</tr>
 			<tr>
 				<th>姓名</th>
 				<td><?=Tool_Str::safestr($data["name"], '无')?></td>
 			</tr>
 			<tr>
 				<th>身份证</th>
 				<td><?=Tool_Str::safestr($data["idcard"], '无')?></td>
 			</tr>
 			<tr>
 				<th>电话</th>
 				<td><?=Tool_Str::safestr($data["mo"], '无')?></td>
 			</tr>
 			<? foreach ($coinlist as $k1 => $v1) { ?>
 				<tr>
	 				<th><?=strtoupper($v1['name'])?>余额</th>
	 				<td><?=$data[$v1['name']."_over"]?></td>
	 			</tr>
	 			<tr>
	 				<th><?=strtoupper($v1['name'])?>冻结</th>
	 				<td><?=$data[$v1['name']."_lock"]?></td>
	 			</tr>
 			<? } ?>
 			<tr>
 				<th>注册时间</th>
 				<td><?=date('Y-m-d H:i:s', $data["created"])?></td>
 			</tr>
 			<tr>
 				<th>注册IP</th>
 				<td><?=$data["createip"]?></td>
 			</tr>
 			<tr>
 				<th>修改时间</th>
 				<td><?=date('Y-m-d H:i:s', $data["updated"])?></td>
 			</tr>
 			<tr>
 				<th>修改IP</th>
 				<td><?=$data["updateip"]?></td>
 			</tr>
 			<? foreach ($coinlist as $k2 => $v2) { ?>
 					<tr>
		 				<th><?=$v2['name']?>钱包地址</th>
		 				<td><?=$adArr[$v2['name']]?></td>
		 			</tr>
 			<? } ?>
 		</tbody>
 	</table>
 </fieldset>
 <fieldset>
 	<legend><h3 class="title">修改</h3></legend>
 	<table class="formtable">
 		<form method="post">
 			<input id="yaf_uid" name="uid" type="hidden" value="<?=$data["uid"]?>"/>
 			<tbody>
 				<tr>
 					<th>邮箱</th>
 					<td><input id="yaf_email" name="email" value="<?=$data["email"]?>" class="loginValue"/></td>
 				</tr>
 				<tr>
 					<th>姓名</th>
 					<td><input id="yaf_name" name="name" value="<?=Tool_Str::safestr($data["name"], '无')?>" class="loginValue"/></td>
 				</tr>
 				<tr>
 					<th>身份证</th>
 					<td><input id="yaf_idcard" name="idcard" value="<?=Tool_Str::safestr($data["idcard"], '无')?>" class="loginValue"/></td>
 				</tr>
 				<tr>
 					<th>电话</th>
 					<td><input id="yaf_mo" name="mo" value="<?=Tool_Str::safestr($data["mo"], '无')?>" class="loginValue"/></td>
 				</tr>
 				<tr>
 					<th>修改原因</th>
 					<td><input id="yaf_mo" name="message" value="" class="loginValue"/></td>
 				</tr>
 			</tbody>
 		</table>
 	</fieldset>
 	<fieldset><input class="submit" type="submit" value="修改"></fieldset>
 </form>
</body>
</html>
