<?php include PATH_TPL."/manage/tpl.header.phtml"?>
<div class="mod">
	<div class="hd">
		<h3 class="title">用户关系</h3>
		<form style="float:right" method='get' action=''>
        <input name="kw" value="<?=isset($_GET['kw'])&&!empty($_GET['kw']) ? $_GET['kw'] : ''?>">
			<select id="yaf_field" name="field">
				<option value="" <?if(!isset($_GET['id'])){echo 'selected';} else {'';}?>>全部</option>
				<option value="uid" <?if(isset($_GET['id'])&&$_GET['id']=='uid'){echo 'selected';} else {'';}?>>邀请者ID</option>
				<option value="oid" <?if(isset($_GET['id'])&&$_GET['id']=='oid'){echo 'selected';} else {'';}?>>被邀请者ID</option>
			</select>
			<input type="submit" value="搜索">
		</form>
	</div>
	<div class="bd">
	<table class="table_s01">
		<thead>
			<tr>
				<th>ID</th>
				<th>邀请者ID</th>
				<th>被邀请者ID</th>
				<th>奖励金额</th>
				<th>奖励时间</th>
			</tr>
		</thead>
		<tbody>
		<?if(!empty($datas)){?>
		<? foreach($datas as $v1){?>
		<tr>
			<td><?=$v1["id"]?></td>
			<td><?=$v1["uid"]?></td>
			<td><?=$v1["oid"]?></td>
			<td><?=$v1["reward"]?></td>
			<td><?=date('Y-m-d H:i:s', $v1["creatime"])?></td>
		</tr>
		<?php }}?>
		</tbody>
	</table>
	<?if(isset($_GET['id']) && $_GET['id'] == 'pid'){
	echo '';
	}else{?>
	<?=$pageinfo;}?>
	</div>
</div>
</body>
</html>
