<?php include PATH_TPL."/manage/tpl.header.phtml";?>
<style>
.form{height:40px; line-height:40px;float:right;margin:10px 0;}
.date{width:150px; height:11px; line-height:11px; padding:5px; border:1px #AA9FFF solid; cursor:pointer; background:url(../images/dateIco.png) no-repeat right center;}
.calender{ width:200px; margin:50px auto; top:0; left:0; border:4px #D6D6D6 solid; background:#EBEBEB; position:absolute; display:none; z-index:999;}
.calendertb{width:100%;}
.calendertb td{width:35px; height:30px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; font-size:14px; font-weight:bold;}
.calendertb td.hover,.calendertb td.weekendhover{background:#D6D6D6;}
.calendertb th{width:35px; height:30px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; color:#979797; }
.tdtoday{ background:#0080FF;color:#fff;width:35px; height:35px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; font-size:14px; font-weight:bold;}
.getyear{ height:35px; line-height:35px; width:100%; text-align:center;}
.preMonth{ font-size:14px; font-weight:bold; cursor:pointer; margin-right:18px;color:#0080FF;}
.nextMonth{ font-size:14px; font-weight:bold; cursor:pointer; margin-left:18px;color:#0080FF;}
.zhezhao{width:100%; height:100%; position:fixed; z-index:998;	background:#fff;filter:alpha(opacity=10);opacity:0.1; display:none; }
.select{width:100px; height:24px; border:2px #AA9FFF solid;}
.page{float: left;}
.tongji{width:350px;float: right;height: 44px;}
.tongji span{margin-left: 20px;font-size: 18px;color:red;height: 44px;line-height: 44px;}
</style>
<link rel="stylesheet" type="text/css" href="/css/calendar/jquery.datetimepicker.css"/>
<script src="/js/calendar/jquery.datetimepicker.js"></script>
<?
$coinArr = [];
foreach ($user as $key => $value){
	if( strpos($key, '_over') !== false ){
		$ar = explode('_', $key);
		$coinArr[] = $ar[0];
	}
}
?>
<div class="mod">
	<div class="hd">
		<h3 class="title">用户</h3>
		<form method="post" style="float:right">
			<input name="kw" value="<?if(isset($kw)) echo $kw?>">
			<select id="yaf_field" name="field">
				<option value="uid">用户ID</option>
				<option value="email">邮箱</option>
				<option value="name">姓名</option>
			</select>
      		<script>$('#yaf_field').val('<?=isset($field)?$field:'uid'?>')</script>
      		<span style="margin: 0 10px;"><input type="checkbox" name="hasTime" value="1" <?if($hasTime==1){?>checked<?}?> >是否筛选时间</span>
      		开始时间:<input type="text" class="date" value="<?=date('Y-m-d H:i', $stime)?>" id="date-start" name="stime" readonly="true" /> 结束时间:<input type="text" class="date" value="<?=date('Y-m-d H:i', $etime)?>" id="date-end" name="etime" readonly="true" />
			<input type="submit" value="搜索">
		</form>
	</div>
	<div class="bd">
	<table class="table_s01">
		<thead>
			<tr>
				<th style="width: 88px;">操作</th>
				<th>用户ID</th>
				<th>邮箱</th>
				<!-- <? foreach ($coinArr as $k2 => $v2) { ?>
						<th><?=strtoupper($v2)?>余额</th>
						<th><?=strtoupper($v2)?>冻结</th>
				<? } ?> -->
				<th style="min-width: 100px;">姓名</th>
				<th>手机</th>

				<th style="width: 150px;">注册时间</th>
				<th style="width: 150px;">更新时间</th>
				<th>查看资产</th>
				<th>认证状态</th>
			</tr>
		</thead>
		<tbody>
		<? foreach($datas['list'] as $v1){?>
		<tr>
			<td>
				<div>
					<? if($btnAuth['user_user_2fa']){ ?>
						<a title="清除双重验证" onclick="WVKE.confirm('/manage_user/usergaclose/uid/<?=$v1["uid"]?>', 'ok')">
							<img src="/img/pma/s_passwd.png" alt="修改">
						</a>
					<? } ?>
					<? if($btnAuth['user_user_pwd']){ ?>
						<a title="重置交易密码" onclick="WVKE.confirm('/manage_user/usertpchange/uid/<?=$v1["uid"]?>', 'ok')">
							<img src="/img/pma/b_usredit.png" alt="修改">
						</a>
					<? } ?>
					<? if($btnAuth['user_user_modify']){ ?>
						<a href="/manage_user/usersave?uid=<?=$v1["uid"]?>" title="修改账户资料">
							<img src="/img/pma/s_rights.png" alt="修改账户资料">
						</a>
					<? } ?>
					<? if($btnAuth['user_user_rmbin']){ ?>
						<a href="/manage_user/rmbin/uid/<?=$v1['uid']?>" title="充值">
							<img src="/img/pma/money.gif" alt="充值">
						</a>
					<? } ?>
				</div>
			</td>
			<td><?=$v1["uid"]?></td>
			<td><?=$v1["email"]?></td>
			<!-- <? foreach ($coinArr as $k2 => $v2) { ?>
				<td><?=$v1[$v2."_over"]?></td>
				<td><?=$v1[$v2."_lock"]?></td>
			<? } ?> -->
			<td><?=Tool_Str::safestr($v1["name"])?></td>
			<td><?=Tool_Str::safestr($v1["mo"])?></td>
			<td><?=date('Y-m-d H:i:s', $v1["created"])?></td>
			<td><? if($v1["updated"]) echo date('Y-m-d H:i:s', $v1["updated"])?></td>
			<td><a href="./userasset/uid/<?=$v1['uid']?>">查看资产</a></td>
			<td><?if(!$v1['isMod']){echo '未认证';}?></td>
		</tr>
		<?php }?>
		</tbody>
	</table>
	<?=$datas['pageinfo']?>
	<p class="tongji">
		<span>总注册人数：<?=$datas['total']?></span>
		<span>已认证人数：<?=$datas['auth']?></span>
	</p>
	</div>
</div>
</body>
</html>
<script>
	$(function(){
		var hasTime = "<?=$hasTime?>";
		if(hasTime==1){
			var start = $('#date-start').val();
			var end = $('#date-end').val();
			$('.pageUl li').each(function(){
				var oldHref = $(this).find('a').attr('href');

				var prega = oldHref.match(/p=(\d*)$/);
				var pregb = oldHref.match(/p=(\d*)&/);
				if( prega != null ){
					var p = prega[1];
				}else if( pregb != null ) {
					var p = pregb[1];
				}else{
					var p = 1;
				}

				var newHref = '?p=' + p + '&hasTime=1&stime=' + start + '&etime=' + end;

				$(this).find('a').attr('href', newHref);
			});
		}
	});
</script>
<script>
	$('#date-start').datetimepicker();
	$('#date-end').datetimepicker();
</script>
