<? include PATH_TPL."/manage/tpl.header.phtml";?>
<style>
	.asset{padding-left: 100px;}
	p{height: 30px;line-height: 30px;}
</style>
<?
if(isset($data)) {
	foreach ($data as $key => $value){
		if( strpos($key, '_over') !== false ){
			$ar = explode('_', $key);
			$coinArr[] = $ar[0];
		}
	}
}
?>
<div class="mod">
	<div class="hd">
		<h3 class="title">用户资产</h3>
	</div>
	<div class="bd">
		<div class="asset">
			<p>用户id：<?=$data['uid']?></p>
			<p>邮箱：<?=$data['email']?></p>
			<p>姓名：<?=$data['name']?></p>
			<p>手机：<?=$data['mo']?></p>
			<? foreach ($coinArr as $k2 => $v2) { ?>
				<p><?=strtoupper($v2)?>余额：<?=$data[$v2."_over"]?></p>
				<p><?=strtoupper($v2)?>冻结：<?=$data[$v2."_lock"]?></p>
			<? } ?>
		</div>
	</div>
</div>
</body>
</html>
