<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN">
<html xmlns="http://www.w3.org/1999/xhtml">
<head >
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>后台管理</title>
<link href="<?php  echo host()?>/css/admin/style.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?php  echo host()?>/js/jquery/1.9.1.min.js"></script>
<script type="text/javascript" src="<?php  echo host()?>/js/jquery/wvke.js"></script>
<script>
	menu = {
	 	"user" : {"name":"运营", "left":[
	 		{"name":"用户", "url":"/manage_user/user"},
			//{"name":"实名认证", "url":"/manage_user/isauth"},
	 		{"name":"人民币", "url":"/manage_user/rmb"},
	 		{"name":"短信到账", "url":"/manage_user/msg"},
	 		{"name":"对账", "url":"/manage_funds/summary"},
			{"name":"验证邮箱", "url":"/manage_user/email"},
			{"name":"变更用户资产", "url":"/manage_user/modifyassets"},
			{"name":"冻结用户", "url":"/manage_user/forbide"},
			{"name":"银行卡", "url":"/manage_user/bankcards"},
			{"name":"预警设置", "url":"/manage_funds/yujing"},
		//	{"name":"交易规则", "url":"/manage_coins/setrule"},
//			{"name":"代付平台充值", "url":"/manage_user/ghtPay"},
			{"name":"实名认证", "url":"/manage_user/autonym"},
			//{"name":"短信平台余額", "url":"/manage_info/MessageOver"}
	 	]},
	 	"ybc" : {"name":"数字货币", "left":[
	 		{"name":"数字货币", "url":"/manage_ybc/ybc"},
	 		{"name":"委托", "url":"/manage_ybc/trust"},
	 		{"name":"成交", "url":"/manage_ybc/order"},
	 		{"name":"一键撤单", "url":"/manage_ybc/cancel"},
	 		{"name":"持有量Top20", "url":"/manage_coins/have"},
	 		{"name":"交易日", "url":"/manage_ybc/tradingday"}
	 	]},
	 	"message" : {"name":"消息管理", "left":[
	 		{"name":"公告列表", "url":"/News_info/news"},
	 		{"name":"发布公告", "url":"/News_info/release"},
	 		{"name":"点对点消息", "url":"/News_info/to2to"},
	 		{"name":"点对点主题列表", "url":"/News_info/messagelist"},
	 		{"name":"点对点消息列表", "url":"/News_info/msglist"},
	 		]},
	 	"log" : {"name":"记录", "left":[
	 		{"name":"邀请关系记录", "url":"/manage_user/userrelation"},
	 		{"name":"邀请奖励记录", "url":"/manage_user/userreward"},
	 		{"name":"人民币导出记录", "url":"/manage_user/rmbcsv"},
	 		{"name":"用户登录记录", "url":"/manage_info/userlogin"},
	 		{"name":"用户信息修改日志", "url":"/manage_user/useredit"},
	 		{"name":"变更用户资产记录", "url":"/manage_user/assetlog"},
	 		{"name":"非富途币验证码", "url":"/manage_info/getcode"},
	 		{"name":"转币邮件查询", "url":"/manage_info/coinout"},
			{"name":"每日涨跌幅", "url":"/manage_coins/float"},
	 	]},
	 	"admin" : {"name":"官方", "left":[
	 		{"name":"管理员", "url":"/manage_admin/index"},
	 		{"name":"角色管理", "url":"/manage_role/index"},
	 		// {"name":"人民币提现手续费", "url":"/manage_fee/cny_out"},
	 		// {"name":"虚拟币手续费", "url":"/manage_coins/index"},
	 	]},
		"finance": {"name": "财务统计", "left": [
				{"name": "财务统计汇总", "url": "/manage_finance/summary"},
				{"name": "充值记录", "url": "/manage_finance/recharge"},
				{"name":"提现记录", "url":"/manage_finance/money"},
				{"name":"交易记录", "url":"/manage_finance/trade"},
				{"name": "转币记录", "url": "/manage_finance/outcoin"},
			]
		}
	 };

</script>
</head>

<body>

<div id="page_head" style="position: relative;z-index: 999;">
	<div class="l logo">后台</div>
	<nav id="nav"></nav>
  <div class="option r">
    您好，<?php  echo $user['name']?> <a href="/user/logout/">[退出]</a>
  </div>
</div>

<section id="page_body">
	<div class="left_bar" id="left_bar"></div>
	<div class="main_page">
		<iframe src="" class="main_iframe" id="main_iframe" name="main_iframe" frameborder="0" scrolling="yes" scrolling="yes" hidefocus=""></iframe>
	</div>
</section>

<footer id="page_foot"></footer>

<div id="block"><!--[if lt IE 7]><iframe style="position:absolute;z-index:-1;filter:alpha(opacity=0);"></iframe><![endif]--></div>
<div id="pop"></div>

<script type="text/javascript">
//框架
$("#main_iframe").attr("scrolling", navigator.appVersion.search(/MSIE 6/i)==-1? "auto": "yes");
//菜单
var menufirst = 0, menuhtml = '', menucur = 'class="cur"';
for(var i in menu){
	menuhtml += "<a "+menucur+" onclick=\"WVKE.menu('"+i+"')\">"+menu[i].name+"</a>";
	if(0==menufirst){ WVKE.menu(i); menufirst = 1; menucur = ''; }
}
$('#nav').html(menuhtml);
//绑定点击事件
$('#nav > a').bind("click", function(){
	$('#nav > a').removeClass("cur");
	$(this).addClass("cur");
});
$(document).ready(function(){
	$(".addbox").hover(function(){$(".addbox").css('height','auto'); $(".addbox dd").css('display','block')},function(){$(".addbox dd").css('display','none')});
	$(".addbox p").hover(function(){$(".addbox").css('height','auto')});
	$(".addbox dd").hover(function(){$(this).find("p").show();},function(){$(this).find("p").hide();});
});
</script>
</body>
</html>
