<?php  include PATH_TPL.'/tpl.header.phtml'?>
<div class="content clear">
	<div class="center">
		<div class="RightBox">
			<div class="wrap">
				<div class="box">
					<div class="TitleBox">
						<h3 class="PlateTitle">修改登录邮箱</h3>
					</div>

					<form class="form-horizontal uadd_pwdfm" id="form" method="post" onsubmit="return changePwd();">
						<?php  if(isset($msg_updated)){?>
							<div class="rePWBtn" style="font-size:14px;color:red;">您的操作太快了，请休息一会儿吧！
							</div><?php }?>
						<!-- 联系邮箱 -->
						<div class="buyText clear rePW">
							<span><b class="importantB">*</b>联系邮箱： </span>
							<span><b class="importantB"></b><?php  echo $user['email']?></span>

						</div>
						<!-- 邮箱 -->
						<div class="buyText clear rePW">
							<span>新联系邮箱：</span> <input type="text" value="" id="email" name="email" class="loginValue" placeholder="不修改请留空">
							<!-- <b class="phone" id="pwdmsg">不修改请留空</b> -->
						</div>


						<div class="buyText clear rePW">
							<span>验证码：</span><input style="width:138px;" class="loginValue signinCode" name="captcha" id="captcha" placeholder="请输入验证码">
							<img id="captchaimg" src="/index/captcha?t=<?php  echo rand(100000, 999999)?>" style="float:left;margin-left: 10px;"> <a id="changeCode" href="javascript:void(0);" onclick="$('#captchaimg').attr('src', '/index/captcha?t='+Math.random())" style="float:left; line-height:40px; padding-left:10px;">看不清，再换一张</a>
						</div>
						<div class="buyText clear rePW"> <span>手机验证码：</span>
							<input type="code" name="code" id="code" value="" class="loginValue">
						</div>
						<div class="phone_verify clearfix">
							<a class="aButton1 left" data-time="60" onclick="verifySub(this,7,'人民币');">获取短信验证码</a>
							<a class="aButton1 right" data-time="60" onclick="verifySub(this,8,'人民币');">获取语音验证码</a>
							<input type="hidden" value=0 id="tip">
						</div>

						<div class="errorTips userinfoErrorTips" id="errorTips" style="display: <?php  echo isset($errorTips) ? 'block' : 'none'; ?>;"><?php  echo isset($errorTips) ? $errorTips : ''; ?></div>

						<!-- 注册按钮 -->
						<div class="rePWBtn">
							<input type="submit" value="保存" class="rePWButton">
							<?php  if(isset($msg_ok)){ ?>
								<a class="save" href="#">保存成功</a>
							<?php  }?>
						</div>

					</form>
				</div>
			</div>
		</div>
		<script>
			//验证邮箱是否注册
			$("#email").blur(function(){
				var email=$("#email").val();
				var filter  = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
				if (!filter.test(email))
				{$('#errorTips').html('邮箱格式不对').show();
					$('#tip').val(0);
					return false;
				}
				else{

					$.ajax({
						url:'/modifyemail/checkemail',
						type:'POST', //GET
						data:{
							'email':email
						},
						dataType:'json',    //返回的数据格式：json/xml/html/script/jsonp/text
						success:function(data,textStatus,jqXHR){
							if(data['status']==1){
								$('#errorTips').html('该邮箱已被注册').show();
								$('#tip').val(0);
								console.log('邮箱已经注册');
							}else{
								$('#tip').val(1);
								$('#errorTips').hide();
								console.log('可以注册');
							}
						},
						error:function(xhr,textStatus){
							console.log(xhr);
						}

					})
				}

			});
			function changePwd() {

				var pLen = $('#oldpwd').val().length;
				if(pLen < 6 || pLen > 20) {
					$('#errorTips').html('原始密码长度在6-20个字符之间').show();
					return false;
				}

				var pwdLen = $('#pwd').val().length;
				if(pwdLen < 6 || pwdLen > 20) {
					$('#errorTips').html('新密码长度在6-20个字符之间').show();
					return false;
				}

				var repwdLen = $('#repwd').val().length;
				if(repwdLen < 6 || repwdLen > 20) {
					$('#errorTips').html('重复密码长度在6-20个字符之间').show();
					return false;
				}

				if($('#pwd').val() != $('#repwd').val()) {
					$('#errorTips').html('新登录密码不一致，请重新输入').show();
					return false;
				}

				return true;
			}

			// 验证码
			function verifySub(obj, num, name){
				$('#tip').val();
				if ($('#tip').val()==0) //等于0 不发送短信验证码
				{
					return false;
				}
				if( !$('#captcha').val() ){
					$('#errorTips').html('请填写图形验证码').show();
					return false;
				}
				$.post('/user_exchange/verifycheck', {'captcha':$('#captcha').val()}, function(data){
					if( data == 'fail' ){
						$('#errorTips').html('图形验证码错误').show();
						return false;
					}
					sendmsg(obj, num, name);
				})
			}
			function time(obj) {
				var times = parseInt($(obj).data('time'));
				if (times == 0) {
					$(obj).removeClass('aButton2').addClass('aButton1');
					$(obj).html("重新获取验证码");
					$(obj).data("time", "60");
					wait = 60;
				} else {
					times--;
					$(obj).removeClass('aButton1').addClass('aButton2');
					$(obj).data("time", times);
					$(obj).html("重新发送(" + times + ")");
					setTimeout(function() {
							time(obj);
						},
						1000);
				}
			}
		</script>

	</div>
</div>
</div>
</div>
</div>
<script src="<?php  echo host()?>/js/form.js"></script>

<?php  include PATH_TPL.'/tpl.footer.phtml'?>







