<?php include PATH_TPL."/manage/tpl.header.phtml"?>
<?$tTS = $type.$status?>
<div class="mod">
	<div class="hd">
		<h3 class="title">人民币</h3>
		<ul class="tabs">
			<li<?if($tTS=='out等待') echo ' class="cur"'?>><a href="/manage_user/rmb/type/out/status/<?=urlencode('等待')?>">等待转出</a></li>
			<li<?if($tTS=='out成功') echo ' class="cur"'?>><a href="/manage_user/rmb/type/out/status/<?=urlencode('成功')?>">成功转出</a></li>
			<li<?if($tTS=='in成功') echo ' class="cur"'?>><a href="/manage_user/rmb/type/in/status/<?=urlencode('成功')?>">充值成功</a></li>
			<li<?if($tTS=='in等待') echo ' class="cur"'?>><a href="/manage_user/rmb/type/in/status/<?=urlencode('等待')?>">充值等待</a></li>
		</ul>
		<?search_form(array('uid'=>'用户', 'email'=>'邮箱'))?>
	</div>
	<div class="bd">
	<table class="table_s01">
		<thead>
			<tr>
				<?if('等待'==$status){?>
				<th width="100">操作</th>
				<?}?>
				<th>id</th>
				<th>用户id</th>
				<th>姓名</th>
				<th>邮箱</th>
				<th>金额</th>
				<?if($tTS!='in成功' && $tTS!='in等待'){?><th>实付金额</th><?}?>
				<th>汇款单号</th>
				<th>汇款账号</th>
				<th>开户行</th>
				<th>收款类别</th>
				<th width="150">创建时间</th>
				<th class="hide">创建ip</th>
				<th class="hide">更新时间</th>
				<th class="hide">更新ip</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($datas as $v1){?>
		<tr>
			<?if($tTS=='out等待'){?>
			<td>
				<button onclick="WVKE.confirm('/manage_user/rmbout/id/<?=$v1['id']?>', 'ok')">成功</button>
				<button onclick="WVKE.confirm('/manage_user/rmbout/id/<?=$v1['id']?>/cancel/1', 'ok')">撤消</button>
			</td>
			<?}else if($tTS=='in等待'){?>
			<td><button onclick="WVKE.confirm('/manage_user/rmbpay/id/<?=$v1['id']?>', 'ok')">到账</button></td>
			<?}?>
			<td><?=$v1["id"]?></td>
			<td><?=$v1["uid"]?></td>
			<td><?=Tool_Str::safestr($v1["name"])?></td>
			<td><?=$v1["email"]?></td>
			<td><?=$v1["money"]?></td>
			<?if($tTS!='in成功' && $tTS!='in等待'){?><td><?=Tool_Str::format($v1['money'] - $v1['money']*0.005, 2)?></td><?}?>
			<td><?=Tool_Str::safestr($v1["order"])?></td>
			<td><?=Tool_Str::safestr($v1["account"])?></td>
			<td><?=Tool_Str::safestr($v1["bank"])?></td>
			<td><?=$v1["accounttype"]?></td>
			<td><?=date('Y-m-d H:i:s', $v1["created"])?></td>
			<td class="hide"><?=$v1["createip"]?></td>
			<td class="hide"><?=date('Y-m-d H:i:s', $v1["updated"])?></td>
			<td class="hide"><?=$v1["updateip"]?></td>
		</tr>
		<?php }?>
		</tbody>
	</table>
	<?=$pageinfo?>
	</div>
</div>
</body>
</html>