<script type="text/javascript" src="/js/jquery/jquery-migrate-1.2.1.min.js" ></script>
<script type="text/javascript" src="/js/jquery/jquery-plugin-boxy/js/jquery.boxy.js"></script>
<link href="/js/jquery/jquery-plugin-boxy/css/boxy.css" rel="stylesheet" type="text/css" />
<style>
.name {
    border-top: 1px solid #D5D5D5;
    border-left: 1px solid #D5D5D5;
    border-bottom: 1px solid #D5D5D5;
    float: left;
    height: 29px;
    line-height: 29px;
    padding: 3px;
    width: 187px;
}
#cards {
    padding:17px 0px 0px 15px;
    overflow-y:auto;
    overflow-x:hidden;
}
#cards .notice{
   height:157px; 
}
#cards .noticeD{
   text-align:center; 
}
#cards ul{
    width:486px;
}
#cards ul li{
    height:66px;
    background-color:#efefef;
    border-bottom:1px dashed #d0d0d0;
    padding:9px 0px 0px 26px;
    cursor:'pointer';
}

#cards ul li span{
    position:relative;
    left:435px;
    top:7px;
    z-index:99;
    display:none;
 
}
#cards ul li span a{
    width:15px;
    height:15px;
    display:block;
}
#cards ul li span a:link{
background:url('<?=host_img()?>/images/dele.png') no-repeat;    
}
#cards ul li span a:hover{
background:url('<?=host_img()?>/images/deleHover.png') no-repeat;    
}
#cards ul li span label{
    visibility:hidden;
}
#cards ul li dl dt{
    font-size:16px;
    color:#222;
    height:39px;
    display:block;
}

#cards ul li dl dt img{
    vertical-align:middle;
    padding-right:13px;
}
#cards ul li dl dd{
    float:left;
    font-size:14px;
    color:#222,
    display:block;
}
.account_name{
    width:197px;
}
.account{
    width:263px;
}
</style>
<div class="RightBox">
	<div class="wrap">
		<div class="box">
			<form method="post" onsubmit="">
				<div class="TitleBox">
					<h3 class="PlateTitle">人民币提现</h3>
				</div>
                <p class="payText"><b>提现须知：</b><br />
                1. 最小提现金额为500元<br />
                2. 人民币提现每天处理三次：上午10点、下午14点和17点<br />
                3. 提现手续费率为<?=($user['member']['fee_rmbout']*100).'%'?><br />
                </p>
				<p class="prompt1"></p>
                <!-- 姓名 -->
				<div class="buyText clear rePW">
					<span><b class="importantB">*</b>姓名：</span>
                    <input type="text" name="name" id="name" value="" class="loginValue" />
                   <!-- <span style='width:44px;margin-right:15px;'>
                        <a href='javascript:void(0)' id='bankcards'><img src='../images/contact.jpg' /></a>
                    </span>-->
					<?if(isset($msg_name)){?>
						<b class="false" id="namemsg"><?=$msg_name?></b>
					<? } else {?>
						<b class="rePWB" id="namemsg">请输入提款人姓名<!--<b style='color:red'>点击图标可选择常用提现账户</b>--></b>
					<?}?>
				</div>
				<!-- 提现方式 -->
                <input type='hidden' name='accounttype' id='accounttype' value='银行卡' />
			    <!-- 银行名称 -->
				<div class="buyText clear rePW">
					<span><b class="importantB">*</b>银行名称：</span>
                    <select name="bank" id="bank" class="loginValue">
                        <option value="">请选择银行</option>
                        <option>工商银行</option>
                        <option>建设银行</option>
                        <option>农业银行</option>
                        <option>中国邮政储蓄</option>
                        <option>交通银行</option>
                        <option>中国银行</option>
                        <option>光大银行</option>
                        <option>中信银行</option>
                        <option>招商银行</option>
                        <option>浦发银行</option>
                        <option>民生银行</option>
                        <option>兴业银行</option>
                        <option>平安银行</option>
                        <option>广发银行</option>
                    </select>
					<b class="rePWB" id="bankmsg"></b>
				</div>
				<div class="buyText clear rePW">
					<span><b class="importantB">*</b>银行卡所在地：</span>
    <select name="province" id="p1">
    </select>&nbsp;
    <select name="city" id="c1">
    </select>
                </div>
				<!-- 提现账户 -->
				<div class="buyText clear rePW">
					<span><b class="importantB">*</b>银行卡号：</span>
					<input type="text"  onkeyup="value=value.replace(/[^\d]/g,'')"  name="account" id="account" value="" class="loginValue">
					<?if(isset($msg_account)){?>
						<b class="false" id="accountmsg"><?=$msg_account?></b>
					<? } else {?>
						<b class="rePWB" id="accountmsg">请在这里输入银行卡号。</b>
					<?}?>
				</div>
				<!-- 提现金额 -->
				<div class="buyText clear rePW">
					<span><b class="importantB">*</b>提现金额(￥)：</span>
					<input type="text" value="" id="money" name="money" class="loginValue">
					<?if(isset($msg_money)){?>
						<b class="false" id="moneymsg"><?=$msg_money?></b>
					<? } else {?>
						<b class="rePWB" id="moneymsg">最少提现金额为500.00元人民币。</b>
					<?}?>
				</div>
				<!-- 交易密码 -->
				<div class="buyText clear rePW">
					<span><b class="importantB">*</b>交易密码：</span>
					<input type="password" name="pwdtrade" id="pwdtrade" value="" class="loginValue">
					<?if(isset($msg_pwdtrade)){?>
						<b class="false" id="pwdtrademsg"><?=$msg_pwdtrade?></b>
					<? } else {?>
						<b class="rePWB" id="pwdtrademsg">请输入交易密码。</b>
					<?}?>
				</div>
				<div class="buyText clear rePW">
					<span><b class="importantB">*</b>手机验证码：</span>
					<input type="code" name="code" id="code" value="" class="loginValue">
					<a class="aButton1" onclick="sendmsg(this,1);">获取短信验证码</a>
					<a class="aButton1" onclick="sendmsg(this,5);">获取语音验证码</a> 
					
				</div>
				<div class="buyText clear rePW" style="margin-top:0;">
					<span><b class="importantB">&nbsp;</b></span>
					
					<?if(isset($codemsg)){?>
						<b class="false" id="codemsg" style="width:180px;"><?=$codemsg?></b>
					<?}else{?>
						<b class="phone" id="codemsg" style="width:180px;">如果您的手机号为空或有误，请联系客服</b>
					<?}?>
				</div>
				<?if($ga['open']){?>
					<!-- 双重验证密码 -->
					<div class="buyText clear rePW">
						<span><b class="importantB">*</b>双重验证密码：</span>
						<input type="password" name="hotp" id="hotp" value="" class="loginValue">
						<?if(isset($msg_hotp)){?>
							<b class="false" id="hotpmsg"><?=$msg_hotp?></b>
						<? } else {?>
							<b class="rePWB" id="hotpmsg">请输入双重验证密码。</b>
						<? }?>
					</div>
				<?}?>
				<!-- 备注 -->
                <?if($user['uid']<6 || $user['uid'] == 22081){?>
				<div class="buyText clear rePW">
                    <span><b class="importantB">*</b>转出备注：</span>
                    <input type="text" name="bak" id='bak' value="" class="loginValue">
                    <b class="rePWB" id="bakmsg">必填</b>
				</div>
                <?}?>
				<!-- 提交请求 -->
				<div class="rePWBtn">
					<input type="submit" value="提现" class="rePWButton">
                    <b class="rePWB" style="color:#ff0000;" id="msg_sub"><?=isset($msg_sub)?$msg_sub:''?></b>
				</div>
			</form>
		</div>
		<script src="<?= host() ?>/js/form.js"></script>
<script>
$(function(){
    $('#bankcards').click(function(){
        Boxy.load('/user_exchange/bankcards',{'modal':true,'closeText':'X','title':'常用银行卡'});
    });                    
});
    var Items=new Array();
    function add(id,iArray) 
    { 
        Items[id] = iArray;
    } 
    add(0,["1:北京","2:天津","3:河北","4:山西","5:内蒙古","6:辽宁","7:吉林","8:黑龙江","9:上海","10:江苏","11:浙江","12:安徽","13:福建","14:江西","15:山东","16:河南","17:湖北","18:湖南","19:广东","20:广西","21:海南","22:重庆","23:四川","24:贵州","25:云南","26:西藏","27:陕西","28:甘肃","29:青海","30:宁夏","31:新疆","32:香港","33:澳门"]);
    add(1,["1:北京"]);
    add(2,["1:天津"]);
    add(3,["1:石家庄","2:张家口","3:承德","4:秦皇岛","5:唐山","6:廊坊","7:衡水","8:沧州","9:邢台","10:邯郸","11:保定","12:其他"]);
    add(4,["1:太原","2:朔州","3:大同","4:长治","5:晋城","6:忻州","7:晋中","8:临汾","9:吕梁","10:运城","11:其他"]);
    add(5,["1:呼和浩特","2:包头","3:赤峰","4:呼伦贝尔","5:鄂尔多斯","6:乌兰察布","7:巴彦淖尔","8:兴安盟","9:阿拉善盟","10:锡林郭勒盟","11:其他"]);
    add(6,["1:沈阳","2:朝阳","3:阜新","4:铁岭","5:抚顺","6:丹东","7:本溪","8:辽阳","9:鞍山","10:大连","11:营口","12:盘锦","13:锦州","14:葫芦岛","15:其他"]);
    add(7,["1:长春","2:白城","3:吉林","4:四平","5:辽源","6:通化","7:白山","8:延边朝鲜族自治州","9:其他"]);
    add(8,["1:哈尔滨","2:七台河","3:黑河","4:大庆","5:齐齐哈尔","6:伊春","7:佳木斯","8:双鸭山","9:鸡西","10:大兴安岭地区(加格达奇)","11:牡丹江","12:鹤岗","13:绥化　","14:其他"]);
    add(9,["1:上海"]);
    add(10,["1:南京","2:徐州","3:连云港","4:宿迁","5:淮安","6:盐城","7:扬州","8:泰州","9:南通","10:镇江","11:常州","12:无锡","13:苏州","14:其他"]);
    add(11,["1:杭州","2:湖州","3:嘉兴","4:舟山","5:宁波","6:绍兴","7:衢州","8:金华","9:台州","10:温州","11:丽水","12:其他"]);
    add(12,["1:合肥","2:宿州","3:淮北","4:亳州","5:阜阳","6:蚌埠","7:淮南","8:滁州","9:马鞍山","10:芜湖","11:铜陵","12:安庆","13:黄山","14:六安","15:巢湖","16:池州","17:宣城","18:其他"]);
    add(13,["1:福州","2:南平","3:莆田","4:三明","5:泉州","6:厦门","7:漳州","8:龙岩","9:宁德","10:其他"]);
    add(14,["1:南昌","2:九江","3:景德镇","4:鹰潭","5:新余","6:萍乡","7:赣州","8:上饶","9:抚州","10:宜春","11:吉安","12:其他"]);
    add(15,["1:济南","2:聊城","3:德州","4:东营","5:淄博","6:潍坊","7:烟台","8:威海","9:青岛","10:日照","11:临沂","12:枣庄","13:济宁","14:泰安","15:莱芜","16:滨州","17:菏泽","18:其他"]);
    add(16,["1:郑州","2:三门峡","3:洛阳","4:焦作","5:新乡","6:鹤壁","7:安阳","8:濮阳","9:开封","10:商丘","11:许昌","12:漯河","13:平顶山","14:南阳","15:信阳","16:周口","17:驻马店","18:其他"]);
    add(17,["1:武汉","2:十堰","3:襄樊","4:荆门","5:孝感","6:黄冈","7:鄂州","8:黄石","9:咸宁","10:荆 州","11:宜昌","12:随州","13:恩施土家族苗族自治州","14:仙桃","15:天门","16:潜江","17:神农架林区","18:其他"]);
    add(18,["1:长沙","2:张家界","3:常德","4:益阳","5:岳阳","6:株洲","7:湘潭","8:衡阳","9:郴州","10:永州","11:邵阳","12:怀化","13:娄底","14:湘西土家族苗族自治州","15:其他"]);
    add(19,["1:广州","2:清远","3:韶关","4:河源","5:梅州","6:潮州","7:汕头","8:揭阳","9:汕尾","10: 惠州","11:东莞","12:深圳","13:珠海","14:中山","15:江门","16:佛山","17:肇庆","18:云浮","19:阳江","20:茂名","21:湛江","22: 其他"]);
    add(20,["1:南宁","2:桂林","3:柳州","4:梧州","5:贵港","6:玉林","7:钦州","8:北海","9:防城港","10:崇左","11:百色","12:河池","13:来宾","14:贺州","15:其他"]);
    add(21,["1:海口","2:三亚","3:其他"]);
    add(22,["1:重庆"]);
    add(23,["1:成都","2:广元","3:绵阳","4:德阳","5:南充","6:广安","7:遂宁","8:内江","9:乐山","10:自 贡","11:泸州","12:宜宾","13:攀枝花","14:巴中","15:资阳","16:眉山","17:雅安","18:阿坝藏族羌族自治州","19:甘孜藏族自治州","20:凉山彝 族自治州县","21:其他"]);
    add(24,["1:贵阳","2:六盘水","3:遵义","4:安顺","5:毕节地区","6:铜仁地区","7:黔东南苗族侗族自治州","8:黔南布依族苗族自治州","9:黔西南布依族苗族自治州","10:其他"]);
    add(25,["1:昆明","2:曲靖","3:玉溪","4:保山","5:昭通","6:丽江","7:普洱","8:临沧","9:宁德","10:德宏傣族景颇族自治州","11:怒江傈僳族自治州","12:楚雄彝族自治州","13:红河哈尼族彝族自治州","14:文山壮族苗族自治州","15:大理白族自治州","16:迪庆藏族 自治州","17:西双版纳傣族自治州","18:其他"]);
    add(26,["1:拉萨","2:那曲地区","3:昌都地区","4:林芝地区","5:山南地区","6:日喀则地区","7:阿里地区","8:其他"]);
    add(27,["1:西安","2:延安","3:铜川","4:渭南","5:咸阳","6:宝鸡","7:汉中","8:安康","9:商洛","10:其他"]);
    add(28,["1:兰州 ","2:嘉峪关","3:金昌","4:白银","5:天水","6:武威","7:酒泉","8:张掖","9:庆阳","10:平凉","11:定西","12:陇南","13:临夏回族自治州","14:甘南藏族自治州","15:其他"]);
    add(29,["1:西宁","2:海东地区","3:海北藏族自治州","4:黄南藏族自治州","5:玉树藏族自治州","6:海南藏族自治州","7:果洛藏族自治州","8:海西蒙古族藏族自治州","9:其他"]);
    add(30,["1:银川","2:石嘴山","3:吴忠","4:固原","5:中卫","6:其他"]);
    add(31,["1:新疆"]);
    add(32,["1:香港"]);
    add(33,["1:澳门"]);
    var selpoc=$("<option value=-1>省份</option>");
    var selcty=$("<option value=-1>城市</option>");
    
        function initProvinceCity(provinceSel,citySel){
				provinceSel.append(selpoc.clone());
                provinceSel.append(createOptions(Items[0]));            
                provinceSel.change(function(){            
                    if($(this).val()==-1)
                        citySel.html(selcty.clone().html());
                    else
                    {
                        citySel.html("").append(selcty.clone());
                        citySel.append(createOptions(Items[$(this).val()]));
                    }
                });
                citySel.append(selcty.clone());
        }
        function createOptions(cs)
        {    
            var options="";
            var len = cs.length;
            for(var i=0;i<len;i++)
            {
                var temp="<option value=";
                temp+=cs[i].split(":")[0]+">"+cs[i].split(":")[1]+"</option>";
                options+=temp;
            }    
            return $(options);    
        }
        function getProvinceCity(p_c)
        {
            var pid=parseInt(p_c.split("_")[0]);
            var cid=parseInt(p_c.split("_")[1]);
            var pv=Items[0][pid].split(":")[1];
            var cv=Items[pid][cid].split(":")[1];
            return pv+"_"+cv;
        }
        //初始化
		$("document").ready(function(){
			initProvinceCity($("#p1"),$("#c1"));
		});
		vali = {money: 0, name: 0, bank: 0, account: 0, reaccount: 0, pwdtrade: 0,code:0};
		$('#money').bind('blur', function(){
			var money = $(this).val();
			if(money < 500) return validateMsg('money', '最少提现金额为500.00元人民币。', 0);
			if(money > 20000) return validateMsg('money', '单笔最大提现金额为20000元', 0);
			if(money > user.rmb_over) return validateMsg('money', '余额不足，当前可用余额为' + user.rmb_over + '元', 0);
			return validateMsg('money', '', vali.money = 1);
		});
		$('#name').bind('blur', function(){
			if($(this).val()) return validateMsg('name', '', vali.name = 1);
			return validateMsg('name', '请填写姓名', 0);
		});
		$('#bank').bind('blur', function(){
			vali.bank = 1;
			if($('#accounttype').val() == '银行卡'){
				if($(this).val()) return validateMsg('bank', '', vali.bank = 1);
				return validateMsg('bank', '请填写开户行', 0);
			}
		});
		$('#account').bind('blur', function(){
			if($(this).val()) return validateMsg('account', '', vali.account = 1);
			return validateMsg('account', '请填写银行卡号', 0);
		});
		$('#reaccount').bind('blur', function(){
			if(!$(this).val()) return validateMsg('reaccount', '请再填写一次银行卡号', 0);
			if($('#account').val() != $('#reaccount').val()) return validateMsg('reaccount', '输入不一致，请重新输入银行卡号。', 0);
			return validateMsg('reaccount', '', vali.reaccount = 1);
		});
		$('#pwdtrade').bind('blur', function(){
			var pLen = $(this).val().length;
			if(pLen < 6 || pLen > 20) return validateMsg('pwdtrade', '密码长度在6-20个字符之间', 0);
			return validateMsg('pwdtrade', '', vali.pwdtrade = 1);
		});
		/* $('#code').bind('blur', function(){
			var pLen = $(this).val().length;
			if(pLen != 6) return validateMsg('code', '手机验证码错误', 0);
			return validateMsg('code', '', vali.code = 1);
		}); */
		// 下拉框 change 事件
		function atchange(v){
			$('.yinhangka').attr('style', 'display:' + (v == '银行卡'? '': 'none'))
		}
	</script>
	</div>
</div>


<div class="RightBox">
	<div class="wrap">
		<div class="box">
			<div class="TitleBox">
				<h3 class="PlateTitle">提现记录</h3>
			</div>
			<table class="Transaction">
				<thead>
				<tr>
					<th>时间</th>
					<th>金额</th>
					<th>实收金额</th>
					<th>账号</th>
					<th>提现方式</th>
					<th>状态</th>
				</tr>
				</thead>
				<tbody>
				<? foreach($datas as $v1){ ?>
					<tr>
						<td><?=date('Y-m-d H:i', $v1['created'])?></td>
						<td><?=$v1['money']?></td>
						<td><?=$v1['money_u']==0?Tool_Str::format($v1['money']*0.995, 2):Tool_Str::format($v1['money_u'], 2)?></td>
						<td><?=substr($v1['account'],0,strlen($v1['account'])-4).'****'?></td>
						<td><?=$v1['accounttype']?></td>
                        <td class="tableEnd">
                        <?=$v1['status']=='等待'?'处理中':($v1['status']=='成功'?'已汇出':$v1['status'])?>
                        </td>
					</tr>
				<? }?>
				</tbody>
			</table>
			<?=$pageinfo?>
		</div>
	</div>
</div>

