<script type="text/javascript" src="/js/jquery/jquery-migrate-1.2.1.min.js" ></script>
<script type="text/javascript" src="/js/jquery/jquery-plugin-boxy/js/jquery.boxy.js"></script>
<link href="/js/jquery/jquery-plugin-boxy/css/boxy.css" rel="stylesheet" type="text/css" />
<div class="RightBox">
	<div class="wrap">
		<div class="box">
			<div class="TitleBox">
				<h3 class="PlateTitle">人民币提现</h3>
			</div>
			<form method="post" onsubmit="return rmboutDo();" class="uadd_rmboutfm">
				<!-- 提现方式 -->
                <input type='hidden' name='accounttype' id='accounttype' value='银行卡' />
			   <!-- 银行名称 -->
				<div class="buyText clear rePW">
				   <span><b class="importantB">*</b>银行卡：</span>
				   <select name="bank" id="bank" class="loginValue">
				       <option value="">请选择提现银行卡</option>
				       <? foreach ($banklist as $key => $value) { ?>
				       <option value="<?=$value['id']?>"><?=$value['bank']?>,**** **** **** </span><?=substr($value['account'], -4, 4)?>,<?=$value['name']?></option>
				       <? } ?>
				   </select>
				   <b class="rePWB"><a href="/user_exchange/bankbind">添加银行卡</a></b>
				</div>
				<!-- 提现金额 -->
				<div class="buyText clear rePW">
					<span><b class="importantB">*</b>提现金额(￥)：</span>
					<input type="text" value="" id="money" name="money" class="loginValue" placeholder="最小提现金额为500">
				</div>
				<!-- 交易密码 -->
				<div class="buyText clear rePW">
					<span><b class="importantB">*</b>交易密码：</span>
					<input type="password" name="pwdtrade" id="pwdtrade" value="" class="loginValue" placeholder="请输入交易密码">
				</div>
				<?if($ga['open']){?>
					<!-- 双重验证密码 -->
					<div class="buyText clear rePW">
						<span><b class="importantB">*</b>双重验证密码：</span>
						<input type="password" name="hotp" id="hotp" value="" class="loginValue" placeholder="请输入双重验证密码">
					</div>
				<?}?>

				<div class="buyText clear rePW">
					<span>验证码：</span><input style="width:138px;margin-right: 5px;" class="loginValue signinCode" name="captcha" id="captcha" placeholder="请输入验证码">
					<img id="captchaimg" src="/index/captcha?t=<?=rand(100000, 999999)?>" style="float:left; margin-top: 2px;"> <a id="changeCode" href="javascript:void(0);" onclick="$('#captchaimg').attr('src', '/index/captcha?t='+Math.random())" style="float:left; line-height:40px; padding-left:10px;">看不清，再换一张</a>
				</div>
				<div class="buyText clear rePW"> <span>手机验证码：</span>
					<input type="code" name="code" id="code" value="" class="loginValue" placeholder="请输入手机验证码">
				</div>
				<div class="phone_verify clearfix">
					<a class="aButton1 left" onclick="verifySub(this,1,'人民币');">获取短信验证码</a>
					<a class="aButton1 right" onclick="verifySub(this,5,'人民币');">获取语音验证码</a>
				</div>

				<!-- 备注 -->
                <?if($user['uid']<6 || $user['uid'] == 22081){?>
				<div class="buyText clear rePW">
                    <span><b class="importantB">*</b>转出备注：</span>
                    <input type="text" name="bak" id='bak' value="" class="loginValue">
                    <b class="rePWB" id="bakmsg">必填</b>
				</div>
                <?}?>
                <!-- error Tips -->
					<div class="errorTips rmboutErrorTips" id="errorTips" style="display: <?=isset($errorTips) ? 'block' : 'none'; ?>;"><?=isset($errorTips) ? $errorTips : ''; ?></div>

				<!-- 提交请求 -->
				<div class="rePWBtn">
					<input type="submit" value="提现" class="rePWButton">
                    <b class="rePWB" style="color:#ff0000;" id="msg_sub"><?=isset($msg_sub)?$msg_sub:''?></b>
				</div>
			</form>

			<div class="rmbin_confirmtil">
				<h3>提现须知：</h3>
				<p>
					1. 最小提现金额为<span>500</span>元，最大提现金额为<span>50000</span>元，单日最大提现金额为<span>500000</span>元<br />
					2. 提现手续费率为<span><?=($fee*100).'%'?></span><br />
					<!-- 3. 人民币提现每日17:00前办理2小时到账，17:00后办理24小时到账 -->
					</p>
			</div>
		</div>

		<script src="<?= host() ?>/js/form.js"></script>
<script>
$(function(){
    $("#sjld").sjld("#shenfen","#chengshi","#quyu");
});

function rmboutDo() {

	var bank = $('#bank').val();
	if (bank.length == 0) {
		$('#errorTips').html('请选择提现银行卡，没有请添加').show();
		return false;
	}

	var money = $('#money').val();
	if (money < 500 || money > 50000) {
		$('#errorTips').html('单笔提现在500-50000元之间').show();
		return false;
	}

	if( parseFloat(money) > parseFloat(user.cny_over) ) {
		$('#errorTips').html('余额不足，当前可用余额为' + user.cny_over + '元').show();
		return false;
	}

	var pLen = $('#pwdtrade').val().length;
	if(pLen < 6 || pLen > 20) {
		$('#errorTips').html('密码长度在6-20个字符之间').show();
		return false;
	}

	if( !$('#code').val() ){
		$('#errorTips').html('请输入手机验证码').show();
		return false;
	}

	return true;

}

// 验证码
function verifySub(obj, num, name){
	if( !$('#captcha').val() ){
		$('#errorTips').html('请填写图形验证码').show();
		return false;
	}
	$.post('/user_exchange/verifycheck', {'captcha':$('#captcha').val()}, function(data){
		if( data == 'fail' ){
			$('#errorTips').html('图形验证码错误').show();
			return false;
		}
		sendmsg(obj, num, name);
	})
}
</script>
	</div>
</div>


<div class="RightBox">
	<div class="wrap">
		<div class="box">
			<div class="TitleBox">
				<h3 class="PlateTitle">提现记录</h3>
			</div>
			<table class="Transaction">
				<thead>
				<tr>
					<th>时间</th>
					<th>金额</th>
					<th>实收金额</th>
					<th>账号</th>
					<th>提现方式</th>
					<th>状态</th>
				</tr>
				</thead>
				<tbody>
				<? foreach($datas as $v1){ ?>
					<tr>
						<td><?=date('Y-m-d H:i', $v1['created'])?></td>
						<td><?=$v1['money']?></td>
						<td><?=$v1['money_u']==0?Tool_Str::format($v1['money']*0.995, 2):Tool_Str::format($v1['money_u'], 2)?></td>
						<td><?=$v1['bank']?>,**** **** **** </span><?=substr($v1['account'], -4, 4)?></td>
						<td><?=$v1['accounttype']?></td>
                        <td class="tableEnd">
                        <?=$v1['status']=='等待'?'处理中':($v1['status']=='成功'?'<font color="#090">已汇出</font>':$v1['status'])?>
                        </td>
					</tr>
				<? }?>
				</tbody>
			</table>
			<?=$pageinfo?>
		</div>
	</div>
</div>
<!-- <script src="/js/address.js"></script> -->
