<?php include PATH_TPL."/manage/tpl.header.phtml"?>
<div class="mod">
	<div class="hd">
		<h3 class="title">对账日期：<?=$today?></h3>
		<form style="float:right">
			<input name="kw" value="<?=$today ?>">
			<input type="submit" value="查询">
		</form>
	</div>
	<div class="bd">
	<table class="table_s01">
		<thead>
			<tr>
				<th width="100px">名称</th>
				<th width="150px">转入</th>
				<th width="150px">转出</th>
				<th width="100px">结余</th>
				<th width="50px"></th>
				<th width="150px">网站总额</th>
				<th width="150px">可用总额</th>
				<th width="150px">冻结总额</th>
				<th width="50px"></th>
				<th width="100px">当日成交量</th>
				<th width="100px">24小时成交量</th>
				<th width="100px">当日手续费</th>
			</tr>
		</thead>
		<tbody>
		<tr><td>人民币</td>
			<td><?=$rmb_in?><br>支付宝：<?=$rmb_in_alipay?><br>财付通：<?=$rmb_in_tenpay?><br>银行卡：<?=$rmb_in_bank ?></td>
			<td>-<?=$rmb_out?><br>支付宝：<?=$rmb_out_alipay?><br>财付通：<?=$rmb_out_tenpay?><br>银行卡：<?=$rmb_out_bank ?></td>
			<td><?=$rmb_in - $rmb_out?></td>
			<td></td>
			<td><?=$cny_over+$cny_lock?></td>
			<td><?=(float)$cny_over ?></td>
			<td><?=(float)$cny_lock ?></td>
			<td></td>
			<td></td>
			<td></td>
			<td><?=(float)$fee_money ?></td>
		</tr>
		<? foreach ($pairs as $k1 => $v1) { ?>
			<tr>
				<td><?=strtoupper($v1['coin_from'])?></td>
				<td><?=(float)$v1[$v1['coin_from'].'_in']?></td>
				<td>-<?=(float)$v1[$v1['coin_from'].'_out']?></td>
				<td><?=number_format($v1[$v1['coin_from'].'_in'] - $v1[$v1['coin_from'].'_out'], 6)?></td>
				<td></td>
				<td><?=$v1[$v1['coin_from'].'_over']+$v1[$v1['coin_from'].'_lock']?></td>
				<td><?=$v1[$v1['coin_from'].'_over']?></td>
				<td><?=(float)$v1[$v1['coin_from'].'_lock']?></td>
				<td></td>
				<td><?=(float)$v1[$v1['coin_from'].'_vol']?></td>
				<td><?=(float)$v1[$v1['coin_from'].'_vol_24']?></td>
				<td><?=(float)$v1[$v1['coin_from'].'_fee'] ?></td>
			</tr>
		<? } ?>
        <!-- <tr>
        	<td>钱包余额</td>
        	<td><?=$balancein?></td>
            <td>-</td>
            <td colspan=9>总计：&nbsp;<?=$balancein?></td>
        </tr> -->
		</tbody>
	</table>
	</div>
</div>
</body>
</html>
