<?php  include PATH_TPL."/manage/tpl.header.phtml"?>
<div class="mod">
	<div class="hd">
		<h3 class="title">指数价格</h3>
	</div>
	<div class="bd">
	<table class="table_s01">
		<thead>
			<tr>
				<th>记录id</th>
				<th>时间</th>
				<th>当前价格</th>
				<th>结果</th>
			</tr>
		</thead>
		<tbody>
        <?php  $type=array('涨','跌','持平');?>
		<?php  foreach ($datas as $v1){?>
		<tr>
			<td><?php  echo $v1["id"]?></td>
			<td><?php  echo date('Y-m-d', $v1["hourtime"]).'&nbsp;&nbsp;&nbsp;'.date('H:i:s', $v1['hourtime']).' - '.date('H:i:s', $v1['hourtime']+3599)?></td>
			<td><?php  echo $v1["price"]?></td>
			<td><?php  echo $type[$v1["status"]]?></td>
		</tr>
		<?php  }?>
		</tbody>
	</table>
	<?php  echo $pageinfo?>
	</div>
</div>
</body>
</html>
