<?php  include PATH_TPL."/manage/tpl.header.phtml"; ?>
<style>
.hd{padding-bottom: 10px;}
.form{height:30px; line-height:30px;float:right;}
.date{width:150px; height:11px; line-height:11px; padding:5px; border:1px #AA9FFF solid; cursor:pointer; background:url(../images/dateIco.png) no-repeat right center;}
.calender{ width:200px; margin:50px auto; top:0; left:0; border:4px #D6D6D6 solid; background:#EBEBEB; position:absolute; display:none; z-index:999;}
.calendertb{width:100%;}
.calendertb td{width:35px; height:30px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; font-size:14px; font-weight:bold;}
.calendertb td.hover,.calendertb td.weekendhover{background:#D6D6D6;}
.calendertb th{width:35px; height:30px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; color:#979797; }
.tdtoday{ background:#0080FF;color:#fff;width:35px; height:35px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; font-size:14px; font-weight:bold;}
.getyear{ height:35px; line-height:35px; width:100%; text-align:center;}
.preMonth{ font-size:14px; font-weight:bold; cursor:pointer; margin-right:18px;color:#0080FF;}
.nextMonth{ font-size:14px; font-weight:bold; cursor:pointer; margin-left:18px;color:#0080FF;}
.zhezhao{width:100%; height:100%; position:fixed; z-index:998;	background:#fff;filter:alpha(opacity=10);opacity:0.1; display:none; }
.select{width:100px; height:24px; border:2px #AA9FFF solid;}
.page{float: left;}
.tongji{width:auto;float: right;height: 44px;}
.tongji span{margin-left: 20px;font-size: 18px;color:red;height: 44px;line-height: 44px;}
.searchInput{margin-left:10px;}
.outInput{margin:6px 0 0 10px;}
</style>
<link rel="stylesheet" type="text/css" href="/css/calendar/jquery.datetimepicker.css"/>
<script src="/js/calendar/jquery.datetimepicker.js"></script>
<?php  $allCoins = User_CoinModel::getInstance()->getList(); ?>
<?php $allCoins[] = array('name'=>'all','display'=>'全部');?>
<div class="mod">
	<div class="hd">
		<select onchange='window.location.href = "/manage_ybc/order/coin/"+this.value' class="title" style="width: 100px;height: 30px;font-size: 18px;font-weight: bolder;margin-left: 10px;">
			<?php  foreach ($allCoins as $key => $value) { ?>
				<option value="<?php  echo $value['name']?>" <?php if($value['name']==$coin){?>selected<?php }?> ><?php  echo $value['display']?></option>
			<?php  } ?>
		</select>
		<!-- <h3 class="title">成交</h3> -->
		<!-- <?php search_form(array('buy_tid'=>'买委托', 'buy_uid'=>'买家', 'sale_tid'=>'卖委托', 'sale_uid'=>'卖家', 'coin_from'=>'币种'))?> -->
		<div class="form">
			<form action="/manage_ybc/ordercsv" method="post" style="float: right">
				<input type="hidden" name="coin" value="<?php if(isset($coin)) echo $coin?>">
				<input type="hidden" name="kw" value="<?php if(isset($kw)) echo $kw?>">
				<input type="hidden" name="field" value="<?php  echo isset($field)?$field:'uid'?>">
				<input type="hidden" name="hasTime" value="<?php  echo ($hasTime==1)?1:0?>">
				<input type="hidden" name="stime" value="<?php  echo $stime?>">
				<input type="hidden" name="etime" value="<?php  echo $etime?>">
				<?php  if($btnAuth['ybc_order_out']){ ?>
					<input type="submit" class="outInput" value="导出">
				<?php  } ?>
			</form>
			<form method="post" style="float: right">
				<input name="kw" value="<?php if(isset($kw)) echo $kw?>">
				<select id="yaf_field" name="field">
					<option value="buy_tid">买委托</option>
					<option value="buy_uid">买家</option>
					<option value="sale_tid">卖委托</option>
					<option value="sale_uid">卖家</option>
					<!-- <option value="coin_from">币种</option> -->
				</select>
	      		<script>$('#yaf_field').val('<?php  echo isset($field)?$field:'uid'?>')</script>
	      		<span style="margin: 0 10px;"><input type="checkbox" name="hasTime" value="1" <?php if($hasTime==1){?>checked<?php }?> >是否筛选时间</span>
	      		开始时间:<input type="text" class="date" value="<?php  echo date('Y-m-d H:i', $stime)?>" id="date-start" name="stime" readonly="true" /> 结束时间:<input type="text" class="date" value="<?php  echo date('Y-m-d H:i', $etime)?>" id="date-end" name="etime" readonly="true" />
				<input type="submit" class="searchInput" value="搜索">
			</form>
		</div>
	</div>
	<div class="bd">
	<table class="table_s01">
		<thead>
			<tr>
				<th>id</th>
				<th>币种</th>
				<th>单价</th>
				<th>数量</th>
				<th>购买委托id</th>
				<th>购买用户id</th>
				<th>出售委托id</th>
				<th>出售用户id</th>
				<th>创建时间</th>
			</tr>
		</thead>
		<tbody>
		<?php  foreach ($datas['list'] as $v1){?>
		<tr>
			<td><?php  echo $v1["id"]?></td>
			<td><?php  echo $v1["coin_from"]?></td>
			<td><?php  echo $v1["price"]?></td>
			<td><?php  echo $v1["number"]?></td>
			<td><?php  echo $v1["buy_tid"]?></td>
			<td><?php  echo $v1["buy_uid"]?></td>
			<td><?php  echo $v1["sale_tid"]?></td>
			<td><?php  echo $v1["sale_uid"]?></td>
			<td><?php  echo date('Y-m-d H:i:s', $v1["created"])?></td>
		</tr>
		<?php  }?>
		</tbody>
	</table>
	<?php  echo $datas['pageinfo']?>
	<p class="tongji">
		<span>总人数：<?php  echo $datas['usertotal'][0]['total']?></span>
		<span>总笔数：<?php  echo $datas['total'][0]['num']?></span>
		<span>总数量：<?php  echo  isset($datas['total'][0]['number']) ? (float)$datas['total'][0]['number'] : 0?></span>
	</p>
	</div>
</div>
</body>
</html>
<script>
	$(function(){
		// 关键字和搜索字段
		var kw = "<?php  echo $kw?>";
		var field = "<?php  echo $field?>";
		if( kw ){
			var kwstr = '&kw=' + kw + '&field=' + field;
		}else{
			var kwstr = '';
		}

		var hasTime = "<?php  echo $hasTime?>";

		$('.pageUl li').each(function(){
			var oldHref = $(this).find('a').attr('href');

			var prega = oldHref.match(/p=(\d*)$/);
			var pregb = oldHref.match(/p=(\d*)&/);
			if( prega != null ){
				var p = prega[1];
			}else if( pregb != null ) {
				var p = pregb[1];
			}else{
				var p = 1;
			}

			if(hasTime==1){
				var start = $('#date-start').val();
				var end = $('#date-end').val();

				var newHref = '?p=' + p + '&hasTime=1&stime=' + start + '&etime=' + end + kwstr;
			}else{
				var newHref = '?p=' + p + kwstr;
			}

			$(this).find('a').attr('href', newHref);
		});
	});
</script>
<script>
	$('#date-start').datetimepicker();
	$('#date-end').datetimepicker();
</script>
