<?php  include PATH_TPL . "/manage/tpl.header.phtml" ?>
<style>
	.loginValue{border: 1px solid #D5D5D5;float: left;height: 29px;line-height: 29px;margin-right: 15px;padding: 3px;width: 400px;}
</style>
<?php 
	$coinlist = Coin_PairModel::getInstance()->getList();
	foreach ($coinlist as $key => $value) {
	}
?>

 <fieldset>
 	<legend><h3 class="title">修改</h3></legend>
 	<table class="formtable">
 		<form method="post">
 			<input id="yaf_id" name="id" type="hidden" value="<?php  echo $data["id"]?>"/>
 			<tbody>
 				<tr>
 					<th>币名</th>
 					<td><?php  echo $data["display"]."(".$data["coin_from"].")"?></td>
 				</tr>
 				<tr>
 					<th>休市规则总开关</th>
 					<td><input id="yaf_rule" name="rule_open" value="<?php  echo $data["rule_open"]?>" class="loginValue"/></td>
 					<td>0是关闭，1是打开<td>
 				</tr>
 				<tr>
 					<th>开盘时间</th>
 					<td><input id="yaf_start" name="open_start" value="<?php  echo $data["open_start"]?>" class="loginValue"/></td>
 					<td>例：0930<td>
 				</tr>
 				<tr>
 					<th>闭盘时间</th>
 					<td><input id="yaf_end" name="open_end" value="<?php  echo $data["open_end"]?>" class="loginValue"/></td>
 					<td>例：1730<td>
 				</tr>
 				<tr>
 					<th>周几休市</th>
 					<td><input id="yaf_week" name="open_week" value="<?php  echo $data["open_week"]?>" class="loginValue"/></td>
 					<td>0是周日，6是周六，例：6,0（用英文逗号隔开）<td>
 				</tr>
 				<tr>
 					<th>节假日休市</th>
 					<td><input id="yaf_date" name="open_date" value="<?php  echo $data["open_date"]?>" class="loginValue"/></td>
 					<td>3月3日和3月4日休市，例：0303,0304（用英文逗号隔开）<td>
 				</tr>
 			</tbody>
 		</table>
 	</fieldset>
 	<fieldset><input class="submit" type="submit" value="修改"></fieldset>
 </form>
</body>
</html>
