<?php  include PATH_TPL."/manage/tpl.header.phtml";?>
<style>
	// select{-webkit-appearance: none;-moz-appearance: none;-o-appearance: none; appearance: none;border-radius: 0;outline: none;border:none;}
.form{height:40px; line-height:40px;float:right;margin:10px 0;}
.date{width:150px; height:11px; line-height:11px; padding:5px; border:1px #AA9FFF solid; cursor:pointer; background:url(../images/dateIco.png) no-repeat right center;}
.calender{ width:200px; margin:50px auto; top:0; left:0; border:4px #D6D6D6 solid; background:#EBEBEB; position:absolute; display:none; z-index:999;}
.calendertb{width:100%;}
.calendertb td{width:35px; height:30px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; font-size:14px; font-weight:bold;}
.calendertb td.hover,.calendertb td.weekendhover{background:#D6D6D6;}
.calendertb th{width:35px; height:30px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; color:#979797; }
.tdtoday{ background:#0080FF;color:#fff;width:35px; height:35px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; font-size:14px; font-weight:bold;}
.getyear{ height:35px; line-height:35px; width:100%; text-align:center;}
.preMonth{ font-size:14px; font-weight:bold; cursor:pointer; margin-right:18px;color:#0080FF;}
.nextMonth{ font-size:14px; font-weight:bold; cursor:pointer; margin-left:18px;color:#0080FF;}
.zhezhao{width:100%; height:100%; position:fixed; z-index:998;	background:#fff;filter:alpha(opacity=10);opacity:0.1; display:none; }
.select{width:100px; height:24px; border:2px #AA9FFF solid;}
.page{float: left;}
.tongji{width:370px;float: right;height: 44px;}
.tongji span{margin-left: 20px;font-size: 18px;color:red;height: 44px;line-height: 44px;}
.searchInput{margin-left:10px;}
.outInput{margin:12px 0 0 10px;}
</style>
<link rel="stylesheet" type="text/css" href="/css/calendar/jquery.datetimepicker.css"/>
<script src="/js/calendar/jquery.datetimepicker.js"></script>
<?php 
$tTS = $type.$status;
if(isset($_GET['bak'])) $tTS = 'in内盘';
?>
<?php  $allCoins = User_CoinModel::getInstance()->getList(); ?>
<div class="mod">
	<div class="hd">
		<select onchange='window.location.href = "/manage_ybc/ybc/coin/"+this.value' class="title" style="width: 100px;height: 30px;font-size: 18px;font-weight: bolder;margin-left: 10px;">
			<?php  foreach ($allCoins as $key => $value) { ?>
				<option value="<?php  echo $value['name']?>" <?php if($value['name']==$coin){?>selected<?php }?> ><?php  echo $value['display']?></option>
			<?php  } ?>
		</select>
		<ul class="tabs">
			<li<?php if($tTS=='out等待') echo ' class="cur"'?>><a href="/manage_ybc/ybc/coin/<?php  echo $coin?>/type/out/status/<?php  echo urlencode('等待')?>">等待转出</a></li>
			<li<?php if($tTS=='in确认中') echo ' class="cur"'?>><a href="/manage_ybc/ybc/coin/<?php  echo $coin?>/type/in/status/<?php  echo urlencode('确认中')?>">转入确认</a></li>
			<li<?php if($tTS=='out成功') echo ' class="cur"'?>><a href="/manage_ybc/ybc/coin/<?php  echo $coin?>/type/out/status/<?php  echo urlencode('成功')?>">成功转出</a></li>
			<li<?php if($tTS=='in成功') echo ' class="cur"'?>><a href="/manage_ybc/ybc/coin/<?php  echo $coin?>/type/in/status/<?php  echo urlencode('成功')?>">成功转入</a></li>
			<li<?php if($tTS=='in已取消') echo ' class="cur"'?>><a href="/manage_ybc/ybc/coin/<?php  echo $coin?>/type/in/status/<?php  echo urlencode('已取消')?>">取消转入</a></li>
			<li<?php if($tTS=='out已取消') echo ' class="cur"'?>><a href="/manage_ybc/ybc/coin/<?php  echo $coin?>/type/out/status/<?php  echo urlencode('已取消')?>">取消转出</a></li>
		</ul>

		<div class="form">
			<form method="post" action="/manage_ybc/ybccsv" style="float: right">
				<input type="hidden" name="coin" value="<?php  echo $coin?>">
				<input type="hidden" name="type" value="<?php  echo $type?>">
				<input type="hidden" name="status" value="<?php  echo $status?>">
				<input type="hidden" name="kw" value="<?php if(isset($kw)) echo $kw?>">
				<input type="hidden" name="field" value="<?php  echo isset($field)?$field:'uid'?>">
				<input type="hidden" name="hasTime" value="<?php  echo ($hasTime==1)?1:0?>">
				<input type="hidden" name="stime" value="<?php  echo $stime?>">
				<input type="hidden" name="etime" value="<?php  echo $etime?>">
				<?php  if($btnAuth['ybc_ybc_out']){ ?>
					<input type="submit" class="outInput" value="导出">
				<?php  } ?>
			</form>
			<form method="post" style="float: right">
				<input name="kw" value="<?php if(isset($kw)) echo $kw?>">
				<select id="yaf_field" name="field">
					<option value="uid">uid</option>
					<option value="email">邮箱</option>
					<option value="wallet">钱包地址</option>
				</select>
	      		<script>$('#yaf_field').val('<?php  echo isset($field)?$field:'uid'?>')</script>
	      		<span style="margin: 0 10px;"><input type="checkbox" name="hasTime" value="1" <?php if($hasTime==1){?>checked<?php }?> >是否筛选时间</span>
	      		开始时间:<input type="text" class="date" value="<?php  echo date('Y-m-d H:i', $stime)?>" id="date-start" name="stime" readonly="true" /> 结束时间:<input type="text" class="date" value="<?php  echo date('Y-m-d H:i', $etime)?>" id="date-end" name="etime" readonly="true" />
				<input type="submit" class="searchInput" value="搜索">
			</form>
		</div>

	</div>
	<div class="bd">
	<table class="table_s01">
		<thead>
			<tr>
				<!-- <?php if($tTS=='out等待'){?>
					<th style="min-width: 115px;">管理</th>
				<?php }?> -->
				<th width="50">id</th>
				<th width="50">用户id</th>
				<th>邮箱</th>
				<th>双重验证</th>
				<th>钱包地址</th>
				<th>txid</th>
				<th width="80">数量</th>
				<?php if($tTS=='in确认中' || $tTS=='in成功'){?><th width="100">确认数</th><?php }?>
				<th style="min-width: 150px;">创建时间</th>
				<?php if($tTS=='out成功' || $tTS=='in成功'){?><th style="min-width: 150px;">成功时间</th><?php }?>
				<th width="125">创建ip</th>
				<?php if($tTS=='out等待'){?>
					<th style="min-width: 150px;">操作</th>
				<?php }?>
				<th width="100">备注</th>
			</tr>
		</thead>
		<tbody>
		<?php  foreach ($datas['list'] as $v1){?>
		<tr>
			<!-- <?php if('out等待'==$tTS){?>
				<td><form action="/manage_ybc/ybcout/id/<?php  echo $v1['id']?>/cancel/0/autosend/1" method="post"> <input name="pass" maxlength="6" size="6"><input type="submit" value="确定"></form></td>
			<?php }?> -->
			<td><?php  echo $v1["id"]?></td>
			<td><a href="/manage_user/usersave?uid=<?php  echo $v1["uid"]?>"><?php  echo $v1["uid"]?></a></td>
			<td><?php  echo $v1["email"]?></td>
			<td><?php  echo Cache_Redis::instance()->hGet('user_ga', $v1['uid'])?'有':'无'?></td>
			<td><?php  echo $v1["wallet"]?></td>
			<td><?php echo $v1["txid"] ?></td>
			<td><?php  echo (float)$v1["number"]?></td>
			<?php if($tTS=='in确认中' || $tTS=='in成功'){?><td><?php  echo $v1["confirm"]?></td><?php }?>
			<td><?php  echo date('Y-m-d H:i:s', $v1["created"])?></td>
			<?php if($tTS=='out成功' || $tTS=='in成功'){?><td><?php  if($v1["updated"]){ echo date('Y-m-d H:i:s', $v1["updated"]);}?></td><?php }?>
			<td><a href="http://www.ip138.com/ips1388.asp?ip=<?php  echo $v1["createip"]?>&action=2" target="_blank"><?php  echo $v1["createip"]?></a></td>

			<?php  $out_limit = (float)User_CoinModel::outlimit($coin); ?>
			<?php if('out等待'==$tTS){?>
				<td>
					<!-- <button onclick="WVKE.confirm('/manage_ybc/ybcout/id/<?php  echo $v1['id']?>', 'ok')">成功</button>　
					<button onclick="WVKE.confirm('/manage_ybc/ybcout/id/<?php  echo $v1['id']?>/cancel/1', 'ok')">撤消</button> -->
					<?php  if( $v1['admin'] == 6 && $v1['number'] >= $out_limit && $v1['confirm'] == 0){ ?>
					<button onclick="WVKE.confirm('/manage_ybc/coinout/id/<?php  echo $v1['id']?>/coin/<?php  echo $coin?>', 'ok')">通过</button>　
					<button onclick="WVKE.confirm('/manage_ybc/coinout/id/<?php  echo $v1['id']?>/coin/<?php  echo $coin?>/cancel/1', 'ok')">不通过</button>
					<?php  } ?>
					<span style="margin-left: 10px;">
					
					
					<?php  echo $v1['admin']==6 ? '已确认&nbsp&nbsp&nbsp&nbsp<a href="javascript:void(0);" onclick="testupdate(this,\''.$v1["uid"].'\',\''.$coin.'\',\''.$v1['id'].'\')">撤销</a>' : ''?>

					
					
					
					
					</span>
				</td>
			<?php }?>
			<td><?php  echo $v1["bak"]?></td>
		</tr>
		<?php  }?>
		</tbody>
	</table>
	<?php  echo $datas['pageinfo']?>
	<p class="tongji">
		<span>总笔数：<?php  echo $datas['total'][0]['num']?></span>
		<span>总数量：<?php  echo  isset($datas['total'][0]['number']) ? (float)$datas['total'][0]['number'] : 0?></span>
	</p>
	</div>
</div>
</body>
</html>
<script>
	$(function(){
		// 关键字和搜索字段
		var kw = "<?php  echo $kw?>";
		var field = "<?php  echo $field?>";
		if( kw ){
			var kwstr = '&kw=' + kw + '&field=' + field;
		}else{
			var kwstr = '';
		}

		var hasTime = "<?php  echo $hasTime?>";

		$('.pageUl li').each(function(){
			var oldHref = $(this).find('a').attr('href');

			var prega = oldHref.match(/p=(\d*)$/);
			var pregb = oldHref.match(/p=(\d*)&/);
			if( prega != null ){
				var p = prega[1];
			}else if( pregb != null ) {
				var p = pregb[1];
			}else{
				var p = 1;
			}

			if(hasTime==1){
				var start = $('#date-start').val();
				var end = $('#date-end').val();

				var newHref = '?p=' + p + '&hasTime=1&stime=' + start + '&etime=' + end + kwstr;
			}else{
				var newHref = '?p=' + p + kwstr;
			}

			$(this).find('a').attr('href', newHref);
		});
	});
</script>
<script>
	$('#date-start').datetimepicker();
	$('#date-end').datetimepicker();




	//撤销
	function testupdate(t,uid,coin,id)
	{
		t.onclick = '';
		var $this = $(t);
		$.ajax( {
			url:'/manage_ybc/cexiao?uid='+uid+'&coin='+coin+'&id='+id,// 跳转到 action
			type:'GET',
			cache:false,
			dataType:'json',
			success:function(data) {
				if(data=='1'){
					alert("撤销成功");
					$this.parents('tr').remove();
				}else if(data=='2'){
					alert("撤销失败,冻结币不足");
				}else if(data=='3'){
					alert("修改状态失败");
				}else if(data=='4'){
					alert("已撤销");
				}else{
					alert("修改余额失败");
				}
			},
			error : function(data) {
				alert('撤销失败');
				location.reload();
			}
			
		});
	}
</script>
