<?php  include PATH_TPL."/manage/tpl.header.phtml";?>
<style>
	.loginValue{border: 1px solid #D5D5D5;float: left;height: 29px;line-height: 29px;margin-right: 15px;padding: 3px;width: 400px;}
	select{width: 100px;height: 40px;font-size: 18px;font-weight: bolder;}
</style>
<div class="mod">
	<div class="hd">
		<h3 class="title"><a href="/manage_user/newforbide">添加冻结用户</a></h3>
		<ul class="tabs">
			<li <?php if($status=='0') echo 'class="cur"'?>><a href="/manage_user/forbide/status/0">冻结中</a></li>
			<li <?php if($status=='1') echo 'class="cur"'?>><a href="/manage_user/forbide/status/1">已解除冻结</a></li>
		</ul>
	</div>
	<div class="bd">
		<!-- <table class="formtable">
 			<form method="post" onsubmit="return checkForm();">
	 			<tbody>
	 				<tr>
	 					<th>用户ID</th>
	 					<td><input name="uid" id="uid" class="loginValue" placeholder="请输入要冻结的用户ID" /></td>
	 				</tr>
	 				<tr>
	 					<th>冻结原因</th>
	 					<td><input name="bak" id="bak" class="loginValue" placeholder="请填写冻结原因" /></td>
	 				</tr>
	 				<tr>
	 					<th>允许操作</th>
	 					<td>
	 						<input type="checkbox" name="canbuy"> 交易买
	 						<input type="checkbox" name="cansale"> 交易卖
	 						<input type="checkbox" name="canrmbout"> 人民币提现
	 						<input type="checkbox" name="cancoinout"> 数字货币提现
	 						<span style="">（选中代表冻结后仍可以进行的操作）</span>
	 					</td>
	 				</tr>
	 				<tr>
	 					<th>&nbsp;</th>
	 					<td>&nbsp;</td>
	 				</tr>
	 				<tr>
	 					<th>&nbsp;</th>
	 					<td><input class="submit" type="submit" value="确定"></td>
	 				</tr>
	 			</tbody>
	 		</form>
 		</table> -->
 		<table class="table_s01">
			<thead>
				<tr>
					<?php  if($status == '0'){ ?><th style="width: 88px;">操作</th><?php  } ?>
					<th>id</th>
					<th>用户ID</th>
					<th>管理员ID</th>
					<th>允许买</th>
					<th>允许卖</th>
					<th>允许人民币提现</th>
					<th>允许货币提现</th>
					<th>冻结原因</th>
					<th style="width: 150px;">创建时间</th>
					<th style="width: 150px;">更新时间</th>
				</tr>
			</thead>
			<tbody>
			<?php  foreach($datas as $v1){?>
			<tr>
				<?php  if($status == '0'){ ?>
				<td>
					<?php  if($btnAuth['user_forbidden_edit']){ ?>
						<a href="/manage_user/newforbide?id=<?php  echo $v1['id']?>">编辑</a>
					<?php  } ?>
					<?php  if($btnAuth['user_forbidden_del']){ ?>
						<a href="javascript:;" onclick="if(confirm('你确定要解除该用户的冻结状态吗？')){window.location.href='/manage_user/delforbide/id/<?php  echo $v1['id']?>'}">解除冻结</a>
					<?php  } ?>
				</td>
				<?php  } ?>
				<td><?php  echo $v1["id"]?></td>
				<td><?php  echo $v1["uid"]?></td>
				<td><?php  echo $v1["admin"]?></td>
				<td><?php  echo $v1["canbuy"]==1 ? '是' : '否'?></td>
				<td><?php  echo $v1["cansale"]==1 ? '是' : '否'?></td>
				<td><?php  echo $v1["canrmbout"]==1 ? '是' : '否'?></td>
				<td><?php  echo $v1["cancoinout"]==1 ? '是' : '否'?></td>
				<td><?php  echo $v1["bak"]?></td>
				<td><?php  echo date('Y-m-d H:i:s', $v1["created"])?></td>
				<td><?php  if($v1["updated"]) echo date('Y-m-d H:i:s', $v1["updated"])?></td>
			</tr>
			<?php  }?>
			</tbody>
		</table>
	</div>
</div>
</body>
</html>

<script>
	function checkForm(){
		if( !$('#uid').val() ){
			alert('请填写要冻结的用户ID');return false;
		}

		if( !$('#bak').val() ){
			alert('请填写冻结原因');return false;
		}

		if(confirm('确定要进行此操作吗？')){
			return true;
		} else{
			return false;
		}
	}
</script>
