<?php  include PATH_TPL . "/manage/tpl.header.phtml" ?>
<style>
	.loginValue{border: 1px solid #D5D5D5;float: left;height: 29px;line-height: 29px;margin-right: 15px;padding: 3px;width: 400px;}
</style>
 <fieldset>
 	<legend><h3 class="title">修改充值订单信息</h3></legend>
 	<table class="formtable">
 		<form method="post">
 			<input type="hidden" name="id" value="<?php  echo $data["id"]?>" />
 			<tbody>
 				<tr>
 					<th>用户UID：</th>
 					<td><input type="text" name="uid" value="<?php  echo $data['uid']?>" class="loginValue" readonly /></td>
 				</tr>
 				<tr>
 					<th>姓名：</th>
 					<td><input type="text" name="name" value="<?php  echo $data['name']?>" class="loginValue" readonly /></td>
 				</tr>
 				<tr>
 					<th>充值金额：</th>
 					<td><input name="money" value="<?php  echo $data['money']?>" class="loginValue"/></td>
 				</tr>
 			</tbody>
 		</table>
 	</fieldset>
 	<fieldset><input class="submit" type="submit" value="修改"></fieldset>
 </form>
</body>
</html>
