<?php  include PATH_TPL."/manage/tpl.header.phtml"; ?>
<style>
.form{height:40px; line-height:40px;}
.date{width:200px; height:16px; line-height:16px; padding:5px; border:2px #AA9FFF solid; cursor:pointer; background:url(../images/dateIco.png) no-repeat right center;}
.calender{ width:200px; margin:50px auto; top:0; left:0; border:4px #D6D6D6 solid; background:#EBEBEB; position:absolute; display:none; z-index:999;}
.calendertb{width:100%;}
.calendertb td{width:35px; height:30px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; font-size:14px; font-weight:bold;}
.calendertb td.hover,.calendertb td.weekendhover{background:#D6D6D6;}
.calendertb th{width:35px; height:30px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; color:#979797; }
.tdtoday{ background:#0080FF;color:#fff;width:35px; height:35px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; font-size:14px; font-weight:bold;}
.getyear{ height:35px; line-height:35px; width:100%; text-align:center;}
.preMonth{ font-size:14px; font-weight:bold; cursor:pointer; margin-right:18px;color:#0080FF;}
.nextMonth{ font-size:14px; font-weight:bold; cursor:pointer; margin-left:18px;color:#0080FF;}
.zhezhao{width:100%; height:100%; position:fixed; z-index:998;	background:#fff;filter:alpha(opacity=10);opacity:0.1; display:none; }
.select{width:100px; height:24px; border:2px #AA9FFF solid;}
</style>

<link rel="stylesheet" type="text/css" href="/css/calendar/jquery.datetimepicker.css"/>
<script src="/js/calendar/jquery.datetimepicker.js"></script>

<div class="mod">
	<div class="hd">
		<h3 class="title">人民币</h3>
	</div>
	<div class="hd" style="height:40px;">
	<form action="#" method="post">
		<div class="form">
			<!-- 开始时间:<input type="text" class="date" name="stime" readonly="true" /> 结束时间:<input type="text" class="date" name="etime" readonly="true" /> -->
			开始时间:<input type="text" class="date" value="2015-12-10 00:00" id="date-start" name="stime" readonly="true" /> 结束时间:<input type="text" class="date" value="2015-12-10 23:59" id="date-end" name="etime" readonly="true" />
			 状态:<select name="status" class="select">
    				<option value="成功" selected>成功</option>
    				<option value="等待">等待</option>
    				<option value="已取消">已取消</option>
    			</select>
			类型:<select name="type" class="select">	
    				<option value="in" selected>转入</option>
    				<option value="out" >转出</option>
			</select>
		<!--	<input type="submit" name="sub" value="搜索"/>-->
			<input type="submit" name="sub" value="导出"/>

		</div>
	</form>
	</div>
	<div class="bd">
	<!--<table class="table_s01">
		<thead>
			<tr>
				<th>id</th>
				<th>用户id</th>
				<th>姓名</th>
				<th>邮箱</th>
				<th>金额</th>
				<th>实付金额</th>
				<th>汇款单号</th>
				<th>汇款账号</th>
				<th>开户行</th>
				<th>收款类别</th>
				<th width="150">创建时间</th>
				<th class="hide">创建ip</th>
				<th class="hide">更新时间</th>
				<th class="hide">更新ip</th>
			</tr>
		</thead>
		<tbody>
-->
	</div>
</div>
</body>
<!-- <script type="text/javascript" src="/js/jquery/date.1.0.js"></script> -->
<script type="text/javascript">
// $(function (){
// 	$("input.date").manhuaDate({       
// 		Event : "click",//可选				       
// 		Left : 0,//弹出时间停靠的左边位置
// 		Top : -16,//弹出时间停靠的顶部边位置
// 		fuhao : "-",//日期连接符默认为-
// 		isTime : false,//是否开启时间值默认为false
// 		beginY : 2010,//年份的开始默认为1949
// 		endY :2015//年份的结束默认为2049
// 	});
	
// });
</script>

<script>
	$('#date-start').datetimepicker();
	$('#date-start').datetimepicker({value:getNowFormatDate()+' 00:00',step:1});
	$('#date-end').datetimepicker();
	$('#date-end').datetimepicker({value:getNowFormatDate()+' 23:59',step:1});


	function getNowFormatDate() {
		var date = new Date();
		var seperator1 = "-";
		var seperator2 = ":";
		var month = date.getMonth() + 1;
		var strDate = date.getDate();
		if (month >= 1 && month <= 9) {
			month = "0" + month;
		}
		if (strDate >= 0 && strDate <= 9) {
			strDate = "0" + strDate;
		}
		var currentdate = date.getFullYear() + seperator1 + month + seperator1 + strDate;

		return currentdate;
	} 
</script>
</html>
