<?php  include PATH_TPL."/manage/tpl.header.phtml";?>
<style>
	// select{-webkit-appearance: none;-moz-appearance: none;-o-appearance: none; appearance: none;border-radius: 0;outline: none;border:none;}
	.form{height:40px; line-height:40px;float:right;margin:10px 0;}
	.date{width:150px; height:11px; line-height:11px; padding:5px; border:1px #AA9FFF solid; cursor:pointer; background:url(../images/dateIco.png) no-repeat right center;}
	.calender{ width:200px; margin:50px auto; top:0; left:0; border:4px #D6D6D6 solid; background:#EBEBEB; position:absolute; display:none; z-index:999;}
	.calendertb{width:100%;}
	.calendertb td{width:35px; height:30px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; font-size:14px; font-weight:bold;}
	.calendertb td.hover,.calendertb td.weekendhover{background:#D6D6D6;}
	.calendertb th{width:35px; height:30px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; color:#979797; }
	.tdtoday{ background:#0080FF;color:#fff;width:35px; height:35px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; font-size:14px; font-weight:bold;}
	.getyear{ height:35px; line-height:35px; width:100%; text-align:center;}
	.preMonth{ font-size:14px; font-weight:bold; cursor:pointer; margin-right:18px;color:#0080FF;}
	.nextMonth{ font-size:14px; font-weight:bold; cursor:pointer; margin-left:18px;color:#0080FF;}
	.zhezhao{width:100%; height:100%; position:fixed; z-index:998;	background:#fff;filter:alpha(opacity=10);opacity:0.1; display:none; }
	.select{width:100px; height:24px; border:2px #AA9FFF solid;}
	.page{float: left;}
	.tongji{width:370px;float: right;height: 44px;}
	.tongji span{margin-left: 20px;font-size: 18px;color:red;height: 44px;line-height: 44px;}
	.searchInput{margin-left:10px;}
	.outInput{margin:12px 0 0 10px;}
</style>
<link rel="stylesheet" type="text/css" href="/css/calendar/jquery.datetimepicker.css"/>
<script src="/js/calendar/jquery.datetimepicker.js"></script>
<?php 
// $tTS = $type.$status;
// if(isset($_GET['bak'])) $tTS = 'in内盘';
?>
<?php  $allCoins = User_CoinModel::getInstance()->getList(); ?>
<div class="mod">
	<div class="hd">
		<select onchange='window.location.href = "/manage_user/tradingday/coin/"+this.value' class="title" style="width: 100px;height: 30px;font-size: 18px;font-weight: bolder;margin-left: 10px;">
			<?php  foreach ($allCoins as $key => $value) { ?>
			<option value="<?php  echo $value['name']?>" <?php if($value['name']==$coin){?>selected<?php }?> ><?php  echo $value['display']?></option>
			<?php  } ?>
		</select>

	</div>
	<div class="bd">
		<table class="table_s01">
			<thead>
				<tr>
				<!-- <?php if($tTS=='out等待'){?>
					<th style="min-width: 115px;">管理</th>
					<?php }?> -->
					<th width="50">id</th>
					<th width="50">用户id</th>
					<th>邮箱</th>
					<th>双重验证</th>
					<th>钱包地址</th>
					<th width="80">数量</th>
					<th style="min-width: 150px;">操作</th>
					<th width="100">备注</th>
				</tr>
			</thead>
			<tbody>
			</tbody>
		</table>
		</div>
</div>
</body>
</html>
<script>
	$(function(){
		// 关键字和搜索字段
		var kw = "<?php  echo $kw?>";
		var field = "<?php  echo $field?>";
		if( kw ){
			var kwstr = '&kw=' + kw + '&field=' + field;
		}else{
			var kwstr = '';
		}

		var hasTime = "<?php  echo $hasTime?>";

		$('.pageUl li').each(function(){
			var oldHref = $(this).find('a').attr('href');

			var prega = oldHref.match(/p=(\d*)$/);
			var pregb = oldHref.match(/p=(\d*)&/);
			if( prega != null ){
				var p = prega[1];
			}else if( pregb != null ) {
				var p = pregb[1];
			}else{
				var p = 1;
			}

			if(hasTime==1){
				var start = $('#date-start').val();
				var end = $('#date-end').val();

				var newHref = '?p=' + p + '&hasTime=1&stime=' + start + '&etime=' + end + kwstr;
			}else{
				var newHref = '?p=' + p + kwstr;
			}

			$(this).find('a').attr('href', newHref);
		});
	});
</script>
<script>
	$('#date-start').datetimepicker();
	$('#date-end').datetimepicker();
</script>
