<?php  include PATH_TPL."/manage/tpl.header.phtml";?>
<style>
	.asset{padding-left: 100px;}
	p{height: 30px;line-height: 30px;}
</style>
<?php 
if(isset($data)) {
	foreach ($data as $key => $value){
		if( strpos($key, '_over') !== false ){
			$ar = explode('_', $key);
			$coinArr[] = $ar[0];
		}
	}
}
?>
<div class="mod">
	<div class="hd">
		<h3 class="title">用户资产</h3>
	</div>
	<div class="bd">
		<div class="asset">
			<p>用户id：<?php  echo $data['uid']?></p>
			<p>邮箱：<?php  echo $data['email']?></p>
			<p>姓名：<?php  echo $data['name']?></p>
			<p>手机：<?php  echo $data['mo']?></p>
			<?php  foreach ($coinArr as $k2 => $v2) { ?>
				<p><?php  echo strtoupper($v2)?>余额：<?php  echo $data[$v2."_over"]?></p>
				<p><?php  echo strtoupper($v2)?>冻结：<?php  echo $data[$v2."_lock"]?></p>
			<?php  } ?>
		</div>
	</div>
</div>
</body>
</html>
