<? include PATH_TPL.'/tpl.header.phtml'?>
<div class="content clear">
	<div class="center">
		<div class="wrap">
			<div class="box">
				<div class="TitleBox">
					<h3 class="PlateTitle">完善资料</h3>
				</div>
				<div class="loginBox">
					<form id="form" method="post" onsubmit="return modifyDo();" class="modifyLeft">
							<!-- 真实姓名 -->
							<div class="login">
								<div class="clear">
									<span><b class="importantB">*</b>真实姓名：</span>
									<input type="text" value="<? if(isset($data['name'])) echo $data['name'] ?>" id="name" name="name" class="loginValue" placeholder="请输入真实姓名">
								</div>
							</div>
							<!-- 证件类型 -->
							<div class="login">
								<div class="clear">
									<span><b class="importantB">*</b>证件类型：</span>
									<select class="loginValue" id="cardtype" name="cardtype" style="width:232px;height:36px;line-height:36px;">
										<option value="1" selected>身份证</option>
										<option value="2">驾驶证</option>
										<option value="3">护照</option>
										<option value="4">军官证</option>
										<option value="5">港澳通行证</option>
									</select>
								</div>
							</div>
							<!-- 身份證号 -->
							<div class="login">
								<div class="clear">
									<span><b class="importantB">*</b>证件号：</span>
									<input type="text" value="<? if(isset($data['idcard'])) echo $data['idcard'] ?>" id="idcard" name="idcard" class="loginValue" placeholder="请输入有效的证件号">
								</div>
							</div>
							<!-- 手机号码 -->
							<div class="login">
								<div class="clear">
									<span><b class="importantB">*</b>手机号码：</span>
									<input type="text" value="<? if(isset($data['mo'])) echo $data['mo'] ?>" id="mo" name="mo" class="loginValue" placeholder="必须填写自己真实的手机号码">
								</div>
							</div>
							<!-- 图形验证码 -->
							<div class="login">
								<div class="clear">
									<span><b class="importantB">*</b>验证码：</span><input class="loginValue modifyCode" name="captcha" id="captcha" placeholder="请输入图形验证码">
									<img id="captchaimg" src="/index/captcha?t=<?=rand(100000, 999999)?>">
									<a href="javascript:void(0)" onclick="$('#captchaimg').attr('src', '/index/captcha?t='+Math.random())">看不清，再换一张</a>
								</div>
							</div>
							<!-- 手机验证码 -->
							<div class="login">
								<div class="clear">
									<span><b class="importantB">*</b>手机验证码：</span>
									<input type="text" id="vcode" name="vcode" class="loginValue" style="width: 100px;" placeholder="请输入手机验证码">
									<input type="button" id="btnSendCode" name="btnSendCode" class="loginValue" value="获取验证码" style="width:120px;height: 38px;">
								</div>
							</div>
							<!-- 交易密码 -->
							<div class="login">
								<div class="clear">
									<span><b class="importantB">*</b>交易密码：</span>
									<input type="password" class="loginValue" id="pwdtrade" name="pwdtrade" placeholder="必须是6-20个英语字母、数字、符号">
								</div>
							</div>
							<!-- 重复交易密码 -->
							<div class="login">
								<div class="clear">
									<span><b class="importantB">*</b>重复交易密码：</span>
									<input type="password" class="loginValue" value="" id="repwdtrade" name="repwdtrade" placeholder="确保两次输入完全一致">
								</div>
							</div>
						<!-- error Tips -->
						<div class="errorTips modifyErrorTips" id="errorTips" style="display: <?=isset($errorTips) ? 'block' : 'none'; ?>;"><?=isset($errorTips) ? $errorTips : ''; ?></div>

						<div class="loginBtn clear">
							<input type="submit" value="完善资料" class="regBtn modifyBtn">
						</div>
						<div style="clear: both; height: 30px;"></div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script src="<?=host()?>/js/form.js"></script>
<script>

function modifyDo() {

	if($('#name').val().length < 2) {
		$('#errorTips').html('为了以后方便识别，请用中文').show();
		return false;
	}

	if($('#cardtype').val() == 1 ){
		if(!($('#idcard').val().length == 8 || $('#idcard').val().length == 18)) {
			$('#errorTips').html('您输入的身份证号不正确').show();
			return false;
		}
	} else {
		if($('#idcard').val().length == '') {
			$('#errorTips').html('您输入的证件号不能为空').show();
			return false;
		}
	}

	if(!($('#mo').val().length == 8 || $('#mo').val().length == 11)) {
		$('#errorTips').html('您输入的手机号格式不正确').show();
		return false;
	}

	if($('#vcode').val().length < 2) {
		$('#errorTips').html('请输入手机验证码').show();
		return false;
	}

	var pLen = $('#pwdtrade').val().length;
	if(pLen < 6 || pLen > 20) {
		$('#errorTips').html('密码长度在6-20个字符之间').show();
		return false;
	}

	var repwdLen = $('#repwdtrade').val().length;
	if(repwdLen < 6 || repwdLen > 20) {
		$('#errorTips').html('密码长度在6-20个字符之间').show();
		return false;
	}

	if($('#repwdtrade').val() != $('#pwdtrade').val()) {
		$('#errorTips').html('密码不一致，请重新输入').show();
		return false;
	}

	if($('#captcha').val().length < 2) {
		$('#errorTips').html('请输入图形验证码').show();
		return false;
	}

	return true;

}

	var interValObj;
	var curCount = 2*60;
	$('#btnSendCode').bind('click', regCode);

	function regCode() {
		var mo 	= $('#mo').val();
		var reg = /^0?1[3|4|5|8][0-9]\d{8}$/;

    	if( !reg.test(mo) ) {
    		// return validateMsg('mo', '您输入的手机号格式不正确', 0);
    		$('#errorTips').html('您输入的手机号格式不正确').show();
			return false;
    	}

    	// 发送短信之前验证图形验证码
    	if( !$('#captcha').val() ){
			$('#errorTips').html('请填写图形验证码').show();
			return false;
		}
		$.post('/user_exchange/verifycheck', {'captcha':$('#captcha').val()}, function(data){
			if( data == 'fail' ){
				$('#errorTips').html('图形验证码错误').show();
				return false;
			}else{
				$('#errorTips').hide();

		    	$('#btnSendCode').unbind('click');
		    	// 取消绑定事件
				var sign 		= '<?=$sign?>';
				var timestamp 	= <?=$timestamp?>;
				var noncestr 	= '<?=$noncestr?>';
				var url  = '/user/sendmsg?timestamp=' + timestamp + '&noncestr=' + noncestr + '&sign=' + sign;
				var aj = $.ajax( {
					url:url,
					data:{
				        mo:mo
				    },
					type:'post',
					cache:false,
					dataType:'json',
					success:function(data) {
						if( 0 == data.Code ) {
							$("#btnSendCode").val("重新发送("+curCount+")");
							interValObj = window.setInterval(setRemainTime, 1000); //启动计时器，1秒执行一次
							return;
						}else{
							$('#errorTips').html(data.Msg).show();
							return false;
						}

						window.clearInterval(interValObj);//停止计时器
						$('#btnSendCode').bind('click', regCode);

						if(-2 == data.Code || -1 == data.Code) {
					   		alert(data.Msg);
							return;
						}

						return validateMsg('vcode', data.Msg, 0);
					},
					error:function() {
						$('#btnSendCode').bind('click', regCode);
						window.clearInterval(interValObj);//停止计时器
					    alert("异常！");
					}
				});
			}
		})
	}

	function setRemainTime() {
		 if (curCount <= 0) {
		    window.clearInterval(interValObj);//停止计时器
		    $("#btnSendCode").removeAttr("disabled");//启用按钮
		    $("#btnSendCode").val("重新发送验证码");
			$('#btnSendCode').bind('click', regCode);
			curCount = 2*60;
		} else {
		    curCount--;
		    $("#btnSendCode").val("重新发送("+curCount+")");
		}
	}
</script>
<? include PATH_TPL.'/tpl.footer.phtml'?>
<script>
var reloadPage = '<?= isset($errorTips) ? $errorTips : '' ?>';
if (reloadPage == '完善资料成功') {
	setTimeout(function() {
		top.location = '/user_index';
	}, 2000);
}
</script>
