<div class="RightBox">
	<div class="wrap">
		<div class="box">
			
			<div class="TitleBox">
				<h3 class="PlateTitle">银行汇款确认充值</h3>
			</div>
			<div style="margin-top: 46px;">
				<form method="post" action="http://ceshi.allinpay.com/gateway/index.do" onsubmit="return bankconfirm();" class="uadd_rmbinfm">
					<div class="buyText clearfix rePW"> <span>充值金额：</span>
						<div class="sellmonyr">
							<p class="ipt_outp">
								<input name="orderAmount" id="epaynumber" class="loginValue" type="text" onblur="return pullRand();" value="<?php  echo $orderAmount?>">
							</p>
							<input type="hidden" name="serverUrl" id="hide-rand" value="<?php  echo $serverUrl?>" />
							<input type="hidden" name="pickupUrl" id="hide-rands" value="<?php  echo $pickupUrl?>" />
							<input type="hidden" name="receiveUrl" id="hide-rands" value="<?php  echo $receiveUrl?>" />
							<input type="hidden" name="version" id="hide-rands" value="<?php  echo $version?>" />
							<input type="hidden" name="signType" id="hide-rands" value="<?php  echo $signType?>" />
							<input type="hidden" name="merchantId" id="hide-rands" value="<?php  echo $merchantId?>" />
							<input type="hidden" name="orderNo" id="hide-rands" value="<?php  echo $orderNo?>" />
							<input type="hidden" name="orderDatetime" id="hide-rands" value="<?php  echo $orderDatetime?>" />
							<input type="hidden" name="orderAmount" id="hide-rands" value="<?php  echo $orderAmount?>" />
							<input type="hidden" name="payType" id="hide-rands" value="<?php  echo $payType?>" />
							<input type="hidden" name="issuerId" id="hide-rands" value="<?php  echo $issuerId?>" />
							<input type="text" name="bufSignSrc" id="hide-rands" value="<?php  echo $bufSignSrc?>" />
							<input type="text" name="signMsg" id="hide-rands" value="<?php  echo $signMsg?>" />
						</div>
					</div>
				
					<!-- error Tips -->
					<div class="errorTips rmbinErrorTips" id="errorTips" style="display: <?php  echo isset($errorTips) ? 'block' : 'none'; ?>;"><?php  echo isset($errorTips) ? $errorTips : ''; ?></div>
					<div class="rePWBtn">
						<input type="submit" value="确认充值" class="rePWButton">
					</div>
				</form>
			</div>
			<div class="rmbin_confirmtil">
          		<h3>充值须知：</h3>
				<p>
					1. 最小充值金额<span><?php  echo Exchange_CnyModel::LOWEST_IN_MONEY?>元</span>。<br />
		            2. 按要求充值用户20分钟之内到账。<br />
					3. 充值免手续费（汇出行手续费自行承担）。<br>
					4. 请您在汇款之前确认已在此页面提交充值订单并严格按照此金额汇款，否则<span>无法快速到账</span>，给您带来的不便敬请见谅。
		        </p>
			</div>
	
		</div>
	</div>
</div>

<script type="text/javascript">
	function bankconfirm(){
		if( $("#epaynumber").val()<0 ){
			$('#errorTips').html('充值金额错误').show();
	        return false;
		}
	    if($("#epaynumber").val() < <?php  echo Exchange_CnyModel::LOWEST_IN_MONEY?>){
	    	$('#errorTips').html('充值最小金额为'+<?php  echo Exchange_CnyModel::LOWEST_IN_MONEY?>+'元，请重新输入').show();
	        return false;
	    }
		if($("#name").val() == ""){
			$('#errorTips').html('姓名不能为空').show();
	        return false;
	    }
	    //var nameReg = reg = /^[\u4E00-\u9FA5]{2,20}$/;
	    var nameReg = reg = /[\u4E00-\u9FA5]{2,5}(?:·[\u4E00-\u9FA5]{2,5})*/;
	    if(!nameReg.test($("#name").val())){
			$('#errorTips').html('请输入正确的中文姓名').show();
	        return false;
	    }
	    if($("#bankfrom").val() == ""){
			$('#errorTips').html('银行名称不能为空').show();
	        return false;
	    }
	    var accountReg = reg = /^[\u4E00-\u9FA5]{4,8}$/;
	    if(!accountReg.test($("#bankfrom").val())){
			$('#errorTips').html('请输入4-8位中文银行名称').show();
	        return false;
	    }
		if($("#account").val() == ""){
			$('#errorTips').html('银行账号不能为空').show();
	        return false;
	    }else{
			var p = /^(\d{16}|\d{17}|\d{18}|\d{19})$/;
			if(!p.exec($("#account").val())){
				$('#errorTips').html('银行账号不正确1').show();
				return false;
			}
	    }
	    if(confirm('您本次充值金额'+num+'.'+<?php  echo $rand?>+'元')){
	        return true;
	    } else{
	        return false;
	    }
	}

	function pullRand(){
		var money = $("#epaynumber").val();
		if( money < 100){
			$('#errorTips').html('充值最小金额为100元，请重新输入').show();
	        return false;
	    }else{
	    	$('#errorTips').html('').hide();
	    }

	    var index = money.indexOf('.');
	    if(index == -1){
	    	money = money.substr(0, money.length-1);
	    }else{
			money = money.substr(0, index-1);
	    }


	    money = parseFloat( money + $('#hide-rand').val() );

	    $("#epaynumber").val(money);
	}

</script>
