<style type="text/css" media="screen">
	.RightBox {
    	margin: -20px 0 40px 0;
    	
	}
	.slogan {
	    margin-top: 28px;
	    display: block;
	    float: none;
	}
    .slogan span.number {
	    display: inline-block;
	    width: 14px;
	    height: 14px;
	    line-height: 14px;
	    text-align: center;
	    color: #ffffff;
	    background: #0096df;
	    margin: 0px 8px 0px 30px;
	    border-radius: 7px;
	}
	.slogan span {
	    color: #ff9900;
	}
	.numberBlock {
	    padding: 0px 0px 10px 0px;
	    
	}
	.numberBlock ul li {
	    line-height: 35px;
	    margin-top: 20px;
	    padding-bottom: 0px;
	}
	.rmbin_confirmtil p {
	    border: none;
	    padding: 0;
	}
	.numberBlock ul li span.c2 {
	    display: inline-block;
	    font-size: 14px;
	    padding-left: 20px;
	    text-align: left;
	    position: relative;
	}
	.numberBlock ul li span.c2 em.exp {
	    color: #999;
	    font-size: 12px;
	    font-style: inherit;
	}
	.numberBlock ul li span.c2 {
	    display: inline-block;
	    font-size: 14px;
	    padding-left: 20px;
	    text-align: left;
	    position: relative;
	}
	.numberBlock ul li span.c2 .bindedBank {
	    display: inline-block;
	    width: 348px;
	    padding-left: 10px;
	    height: 38px;
	    line-height: 38px;
	    border: 1px solid #e6e6e6;
	    position: relative;
	}
	.numberBlock ul li span.c2 .bindedBank em img {
	    vertical-align: middle;
	    margin-bottom: 2px;
	}
	.numberBlock ul li em.tail{
		font-style: inherit;
		font-size: 12px;
	    color: #767676;
	    margin-left: 5px;
	    font-weight: 100;
	}
	.numberBlock ul li span.c2 .bankBindedSelChange {
	    float: right;
	    display: inline-block;
	    padding-left: 10px;
	    border-left: 1px solid #e6e6e6;
	    color: #0096e0;
	    height: 18px;
	    line-height: 18px;
	    margin: 10px 30px 0px 0px;
	    font-size: 14px;
	    cursor: pointer;
	}
	.numberBlock ul li span.c2 .arrow-down {
	    position: absolute;
	    right: 10px;
	    top: 17px;
	    width: 0;
	    height: 0;
	    border-left: 5px solid transparent;
	    border-right: 5px solid transparent;
	    border-top: 5px solid #999;
	}
	.numberBlock ul li span.c2 .bindedContent {
	    position: absolute;
	    top: 38px;
	    right: -1px;
	    background: #ffffff;
	    border: 1px solid #e6e6e6;
	    width: 358px;
	    z-index: 3;
	    padding: 5px 0px 10px;
	}
	#ulFinCnyAddress li{
		 margin: 0 0 0 10px;
	}
	.numberBlock ul li span.c2 .bindedContent div {
	    margin: 0px 10px;
	}
	.numberBlock ul li span.c2 .bindedContent div a.addNewBankCard {
	    width: 340px;
	    background: #f5f5f5;
	    height: 34px;
	    line-height: 34px;
	    text-align: center;
	    display: inline-block;
	    color: #333;
	    font-size: 14px;
	    text-decoration: none;
	}
	.numberBlock ul li span.c2 .bindedContent div a.addNewBankCard em {
	    color: #d8d8d8;
	    margin-right: 5px;
	    font-style: inherit;
	}
	.numberBlock ul li span input[type='text'] {
	    height: 40px;
	    width: 360px;
	    padding-left: 10px;
	    border: 1px solid #e6e6e6;
	    font-size: 14px;
	    color: #555;
	    border-radius: 2px;
	}
	.numberBlock ul li span.c1 {
	    display: inline-block;
	    text-align: right;
	    width: 115px;
	    font-size: 14px;
	}
	
	.numberBlock ul li span.c2 em.number {
	    position: absolute;
	    right: 10px;
	    top: 5px;
	    color: #f39800;
	    font-style: inherit;
	}
	.numberBlock ul li p.care {
	    display: inline-block;
	    font-size: 12px;
	    margin-left: 20px;
	    text-align: left;
	    color: #666;
	    line-height: 17px;
	    padding: 5px;
	    margin-left: 139px;
	}
	.numberBlock ul li.submit {
	    padding-left: 140px;
	    margin-top: 0px;
	}
	.numberBlock .numberBlock ul li {
	    line-height: 35px;
	    margin-top: 20px;
	    padding-bottom: 0px;
	}
	.numberBlock ul li.submit a {
	    height: 40px;
	    line-height: 40px;
	    font-size: 14px;
	}
	.button_blue {
	    background: #faad09;
	    border: 1px solid #faad09;
	    color: #fff;
	    font-size: 14px;
	    padding: 0px 30px;
	    text-align: center;
	    height: 34px;
	    line-height: 34px;
	    border-radius: 2px;
	    cursor: pointer;
	    display: inline-block;
	}
	.button_blue:hover {
	    background: #ee8d02;
	    border: 1px solid #ee8d02;
	    color: #fff;
	    text-decoration: none;
	}
	.rmbin_confirmtil {
	    margin: 40px auto 0 auto;
	}
</style>
<div class="RightBox" onclick="closeBank()">
   
	<div class="wrap">
        <div class="box">
            <div class="TitleBox">
                <h3 class="PlateTitle">银行汇款充值</h3>
            </div>
			<form action="http://ceshi.allinpay.com/gateway/index.do" method="post">
            <div class="rmbin_confirmtil">
                <p class="slogan">
                    <img width="18" height="18" style="vertical-align: middle;margin-bottom: 2px;" src="https://img.bafang.com/v_20170412008/okcoin/image/recharge/icon_bank.png">
                    <span>两步完成充值</span>
                    <span class="number">1</span>
                    <span>提交汇款单</span>
                    <span class="number">2</span>
                    <span>网银转账</span>
                </p>
                <div class="numberBlock">
                    <ul>
                        <li style="margin: 0;">
                            <span class="c1">汇款人姓名:</span>
                            <span class="c2">陈某某<em class="exp">（仅支持您本人银行卡充值）</em></span>
                        </li>
                        <li>
                            <span class="c1">
                        
                          选择银行
                        
                        :
                      </span>
                            <span class="c2" style="display: ;">
                        <span class="bindedBank">
                          
                          <span id="bankBindedSel" class="bankBindedSel" addressvalue="235327" codevalue="3">
                            <em><img width="24" height="24" src="/img/icon/bank3.png"></em>
                            <span>招商银行</span>
                            <em class="tail">尾号：8243</em>
                            </span>
                            <span class="bankBindedSelChange" style="" onclick="replaceBank()">更换银行卡</span>
                            <span class="arrow-down" style=""></span>
                            <ul id="ulFinCnyAddress" class="selContent bindedContent" style="display: none;">
                                <!-- 其它银行没有银行信息 -->
                                <div class="liOuter" id="addressDiv_235327">
                                    <li onclick="addBankInfo(this)" id="addressLi_235327" class="addressBindedSel" addressid="235327" code="3">
                                        <em><img width="24" height="24" src="/img/icon/bank3.png"></em>
                                        <span>招商银行</span>
                                        <em class="tail">尾号：8243</em>
                                    </li>
                                </div>
                                <span id="addressNone" style="display:none;" >
                              <em></em>
                              <span></span>
                                <em class="tail"></em>
                                </span>
                                <div code="-1">
                                    <a class="addNewBankCard" href="javascript:void(0)" ><em>+</em>添加新银行卡</a>
                                </div>
                            </ul>
                            </span>
                            </span>
                        </li>
                        <li>
                            <span class="c1">充值金额:</span>
                            <span class="c2"><input id="subMoney" class="blankInformation" type="text" value="" placeholder="最低100元" name="orderAmount" ><em class="number orange">.40</em></span>
                            <p class="care">*汇款时金额请包含小数点后两位，未包含会造成汇款延迟到账</p>
                        </li>
                        <li>
                            <span class="c1">汇款人手机:</span>
                            <span class="c2"><input id="fromPhone" class="blankInformation" type="text" value="13713668351" name="payerTelephone" placeholder="请填写能联系到您的电话号码"></span>
                            <p style="margin-left: 140px;margin-top: 10px;display: none;">
                                <input id="ischinaphone" type="checkbox" checked="">&nbsp;&nbsp;该手机号为大陆手机号</p>
                        </li>
                        <li class="errorTipsOuter" style="">
                            <span class="red" id="finTigs"></span>
                        </li>
							<input type="hidden" name="serverUrl" id="serverUrl" value="<?php  echo $serverUrl ?>">
							<input type="hidden" name="key" id="key" value="1234567890">
							<input type="hidden" name="pickupUrl" id="pickupUrl" value="https://www.bijiaosuo.com/user_index">
							<input type="hidden" name="receiveUrl" id="receiveUrl" value="https://www.bijiaosuo.com/user_index">
							<input type="hidden" name="version" id="version" value="v1.0">
							<input type="hidden" name="signType" id="signType" value="1">
							<input type="hidden" name="merchantId" id="merchantId" value="100020091218001">
							<input type="hidden" name="orderNo" id="orderNo" value="<?php  echo date('Ymd').substr(implode(NULL, array_map('ord', str_split(substr(uniqid(), 7, 13), 1))), 0, 7).'1'; ?>">
							<input type="hidden" name="orderDatetime" id="orderDatetime" value="<?php  echo time;?>">
							<input type="hidden" name="payType" id="payType" value="0">
							<input type="hidden" name="bufSignSrc" id="bufSignSrc" value="0">
							<input type="hidden" name="signMsg" id="signMsg" value="strtoupper(md5($bufSignSrc))">
                        <li class="submit">
                           <!-- <a class="button_blue" style="float: left;" href="Exchangetest/rmbin2test" id="" onclick="javascript:createOrder(1);">提交汇款单</a>-->
                            <input type="submit" id="finType" name="payType" value="提交汇款单">
                            
                        </li>
                    </ul>
                </div>
            </div>
			</form>
            <div class="rmbin_confirmtil">
                <h3>充值须知：</h3>
                <p>
                    1. 最小充值金额<span><?php  echo Exchange_CnyModel::LOWEST_IN_MONEY?>元</span>。
                    <br /> 2. 按要求充值用户20分钟之内到账。
                    <br /> 3. 充值免手续费（汇出行手续费自行承担）。
                    <br> 4. 请您在汇款之前确认已在此页面提交充值订单并严格按照此金额汇款，否则<span>无法快速到账</span>，给您带来的不便敬请见谅。
                </p>
            </div>
        </div>
    </div>
</div>

<div class="RightBox">
	<div class="wrap">
		<div class="box">
			<div class="TitleBox">
				<h3 class="PlateTitle">充值记录</h3>
			</div>
			<table class="Transaction">
				<thead>
					<tr>
						<th>订单ID</th>
						<th>时间</th>
						<th>金额</th>
						<th>充值方式</th>
						<th>状态</th>
					</tr>
				</thead>
				<tbody>
					<?php  foreach($datas as $v1){ ?>
					<tr>
						<td><?php  echo $v1['id']?></td>
						<td><?php  echo date('Y-m-d H:i', $v1['created'])?></td>
						<td><?php  echo $v1['money']?></td>
						<td><?php if($v1['accounttype'] == '双乾'){echo "直充";}else{echo $v1['accounttype'];}?></td>
						<td class="tableEnd<?php if('成功'==$v1['status'])echo ' sell'?>"><?php  echo $v1['status']=='等待'?'处理中':$v1['status']?></td>
					</tr>
					<?php  }?>
				</tbody>
			</table>
			<?php  echo $pageinfo?>
		</div>
	</div>
</div>

<script type="text/javascript">
	/*更换银行卡*/
	function replaceBank(e){
		e && e.stopPropagation ? e.stopPropagation() : window.event.cancelBubble = true;
		$("#ulFinCnyAddress").show();
	}
	function closeBank(){
		$("#ulFinCnyAddress").hide();
	}
	
 	$("#finType").click(function(){
		var serverUrl=$('#serverUrl').val();
		var subMoney=$('#subMoney').val();
		var key=$('#key').val();
		var fromPhone=$('#fromPhone').val();
		var pickupUrl=$('#pickupUrl').val();
		var receiveUrl=$('#receiveUrl').val();
		var version=$('#version').val();
		var signType=$('#signType').val();
		var merchantId=$('#merchantId').val();
		var orderNo=$('#orderNo').val();
		var orderDatetime=$('#orderDatetime').val();
		var payType=$('#payType').val();
		$.ajax({
			type:'get',
			url: 'rmbintestajax',
			data:{fromPhone:fromPhone},
			success:function(data){
				
				 if(data !='')
				{
					
					//$("#bufSignSrc").val();alert(1);
				} 
			}
		});
		return false;
	}); 
	
</script>
