<?php include PATH_TPL."/manage/tpl.header.phtml"; ?>
<style>
.loginValue {
    border: 1px solid #D5D5D5;
    float: left;
    height: 29px;
    line-height: 29px;
    margin-right: 15px;
    padding: 3px;
    width: 100px;
}
</style>
<div class="mod">
	<div class="hd">
		<h3 class="title">分类</h3>
		<form style="float:right">
			<input name="kw" value="<?if(isset($_GET['kw']))echo $_GET['kw']?>">
			<select id="yaf_field" name="field">
				<option value="uid">uid</option>
				<option value="email">邮箱</option>
			</select>
      <script>$('#yaf_field').val('<?=isset($_GET['field'])?$_GET['field']:'uid'?>')</script>
			<input type="submit" value="搜索">
		</form>
	</div>
	<div>
		<input type="text" name="catrgory" id="catrgory"/>
		<input type="button" name="sub" id="addcategory" value="添加分类" />
	</div>
	<div class="bd">
	<table class="table_s01">
		<thead>
			<tr>
				<th width="100">id</th>
				<th>分类名称</th>
				<th width="100">操作</th>
			</tr>
		</thead>
		<tbody>
		<? foreach($datas as $v1){?>
		<tr>
			<td><?=Tool_Str::safestr($v1["id"])?></td>
			<td><?=Tool_Str::safestr($v1["name"])?></td>
		    <td><a href="./categories/?id=<?=Tool_Str::safestr($v1["id"])?>&ac=rm">删除</a></td>
		</tr>
		<?php }?>
		</tbody>
	</table>
	<?=$pageinfo?>
	</div>
</div>
<script type="text/javascript">

	$('#addcategory').click(function() {
		var name = $('#catrgory').val();
		if(!name) alert('分类不能为空');

		var aj = $.ajax( {  
		    url:'./addCategory',// 跳转到 action  
		    data:{  
		        name:name
		    },  
		    type:'post',  
		    cache:false,  
		    dataType:'json',  
		    success:function(data) {  
		        if(data.code ==0 ){  
		            alert("添加成功！");  
		            window.location.reload();  
		        }else{  
		           
		        }  
		     },  
		     error : function() {
		          alert("异常！");  
		     }  
		});
	});


</script>
</body>
</html>
