<?php include PATH_TPL . "/manage/tpl.header.phtml" ?>
<style>
.loginValue {
    border: 1px solid #D5D5D5;
    float: left;
    height: 29px;
    line-height: 29px;
    margin-right: 15px;
    padding: 3px;
    width: 200px;
}
</style>
<script>
	var editor;
	KindEditor.ready(function(K) {
		editor = K.create('textarea[name="content"]', {
			resizeType : 1,
			allowPreviewEmoticons : false,
			allowImageUpload : false,
			items : [
				'source', 'fontname', 'fontsize', 'forecolor','|',  'bold', 'italic', 'underline',
				'removeformat', '|', 'justifyleft', 'justifycenter', 'justifyright', 'link'],
			colorTable : [
					['#FF0000', '#E56600', '#FF9900', '#64451D', '#DFC5A4', '#FFE500'],
					['#009900', '#006600', '#99BB00', '#B8D100', '#60D978', '#00D5FF'],
					['#337FE5', '#003399', '#4C33E5', '#9933E5', '#CC33E5', '#EE33EE'],
					['#FFFFFF', '#CCCCCC', '#999999', '#666666', '#333333', '#000000']
			]
		});
	});
</script>
<form method="post">
<input id="yaf_id" name="id" type="hidden" value="<?=$data["id"]?>"/>
  <fieldset>
    <legend><h3 class="title">发布文章</h3></legend>
    <table class="formtable">
      <tbody>
			<tr>
				<th>主题</th>
				<td><input class="loginValue" type='text' name ='title' value="<?=Tool_Str::safestr($data["title"], '无')?>" readonly> </td>
			</tr>
            <tr>
                <th>分类</th>
                <td>
                    <select name="category_id">
                        <?php foreach ($categorys as $v) { ?>
                        <option value="<?=$v['id']?>" <? echo ($data["category_id"] == $v['id'])?'selected':'';?>><?=$v['name']?></option>
                        <?php } ?>
                    </select>
                </td>
            </tr>
            <tr>
                <th>操作</th>
                <td>
                    <label><input name="opt" type="checkbox" value="1" <?php echo (1==$data["is_top"]) ? "checked" : ''; ?>/>置顶 </label> 
                </td>
            </tr>
			<tr>
				<th>文章内容</th>
				<td>
			<!--	<script type="text/plain" id="myEditor" name="content" style="width:800px;height:240px;">-->
					<textarea name="content" style="width:700px;height:300px;visibility:hidden;"><?=$data['content'];?></textarea>
			<!--	</script>-->
   <!-- <script type="text/javascript">
    //实例化编辑器
    var ue = UM.getEditor('myEditor');
    ue.addListener('blur',function(){
        $('#focush2').html('编辑器失去焦点了')
    });
    ue.addListener('focus',function(){
        $('#focush2').html('')
    }); 
</script> -->
</td>
			</tr>
         
      </tbody>
    </table>
  </fieldset>
 <fieldset><input class="submit" type="submit" value="保存"></fieldset>
</form>
</body>
</html>