<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="<?=host()?>/css/admin/style.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?=host()?>/js/jquery/wvke.js"></script>
<script type="text/javascript" src="<?=host()?>/js/jquery/1.9.1.min.js"></script>
<script type="text/javascript" src="<?=host()?>/editor/ueditor/editor_config.js"></script>
<script type="text/javascript" src="<?=host()?>/editor/ueditor/editor_all.js"></script>
</head>
<body class="iframe_page">

<?php
/**
 * 搜索表单
 * @param array $pField 搜索字段
 */
function search_form($pField, $pAction=''){ ?>
<form style="float:right"<?if($pAction)echo ' action="'.$pAction.'"'?>>
	<input name="kw" value="<?if(isset($_GET['kw']))echo $_GET['kw']?>">
	<select id="yaf_field" name="field">
    <? foreach ($pField as $k1 => $v1) {?>
		<option value="<?=$k1?>"><?=$v1?></option>
    <? }?>
	</select>
  <? if(isset($_GET['field'])){ ?>
	<script>$('#yaf_field').val('<?=$_GET['field']?>')</script>
  <? } ?>
	<input type="submit" value="搜索">
</form>
<? } ?>
