<?php  include PATH_TPL.'/tpl.header.phtml'; ?>
<style>
	.aboutText-categoty {
		float:left;
		display: block;
	}
	.aboutText-date {
		float:right;
		display: block;
	}
	.aboutText-other {
		height: 40px;
		line-height: 40px;
		border-bottom: #e3e3e3 1px solid;
		margin-bottom: 20px;
	}
	.artile-title{padding: 10px 0px;font-size: 15px;}
</style>
<div class="content clear">
	<div class="Left">
		<div class="accountBox">
			<div class="wrap">
				<div class="box">
					<div class="TitleBox">
						<h3 class="PlateTitle">文章分类</h3>
					</div>
					<div class="about clear">
						<?php  foreach($categorys as $v1){?>
							<a  href="./?cid=<?php  echo $v1['id']?>"><?php  echo $v1['name']?></a>
						<?php  }?>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="Right">
		<div class="accountBox">
			<div class="wrap">
				<div class="box">
					<div class="TitleBox">
						<h3 class="PlateTitle">文章详情</h3>
					</div>
					<div class="aboutText">
						<h4  class="artile-title"><?php  echo $data['title']?></h4>
						<div class="aboutText-other"><span style="aboutText-categoty">文章分类：<?php  echo $data['category']?></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="aboutText-date ">发布时间：<?php  echo date('Y-m-d H:i:s', $data['created'])?></span></div>
						<div>
							<?php  echo $data['content']?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<?php  include PATH_TPL.'/tpl.footer.phtml'?>