<?php  include PATH_TPL."/manage/tpl.header.phtml"?>
<style>
.loginValue {
    border: 1px solid #D5D5D5;
    float: left;
    height: 29px;
    line-height: 29px;
    margin-right: 15px;
    padding: 3px;
    width: 100px;
}
</style>
<div class="mod">
	<div class="hd">
		<h3 class="title">用户</h3>
		<form style="float:right">
			<input name="kw" value="<?php if(isset($_GET['kw']))echo $_GET['kw']?>">
			<select id="yaf_field" name="field">
				<option value="uid">uid</option>
				<option value="email">邮箱</option>
			</select>
      <script>$('#yaf_field').val('<?php  echo isset($_GET['field'])?$_GET['field']:'uid'?>')</script>
			<input type="submit" value="搜索">
		</form>
	</div>
	<div class="bd">
	<table class="table_s01">
		<thead>
			<tr>
				<th>操作</th>
				<th>id</th>
				<th>公告主题</th>
				<th>发布时间</th>
				<th>是否最新</th>
				<th>新闻类型</th>
				<th>排序</th>
			</tr>
		</thead>
		<tbody>
		<?php  foreach($datas as $v1){?>
		<tr>
		    <td>
		    	<?php  if($btnAuth['message_news_edit']){ ?>
		    		<a href="./release/?id=<?php  echo Tool_Str::safestr($v1["id"])?>">编辑</a>/
		    	<?php  } ?>
		    	<?php  if($btnAuth['message_news_del']){ ?>
		    		<a href="javascript:;" onclick="if(confirm('你确定要删除吗？')){window.location.href='./newsdel/?id=<?php  echo Tool_Str::safestr($v1["id"])?>'}">删除</a>/
		    	<?php  } ?>
		    	<a href="javascript:;" class="view" name="<?php  echo $v1['category']?>" nid="<?php  echo Tool_Str::safestr($v1["id"])?>">预览</a>
		    </td>
			<td><?php  echo Tool_Str::safestr($v1["id"])?></td>
			<td><?php  echo Tool_Str::safestr($v1["title"])?></td>
			<td><?php  echo date('Y-m-d H:i:s', $v1["created"])?></td>
			<td><?php  if($v1["is_new"]== 'Y') echo '是'; else echo '否';?></td>
			<td><?php  if($v1["category"]== 1) echo '系统公告'; else echo '行业新闻';?></td>
			<td><input class="loginValue" type="text" name="sort" value="<?php  echo $v1['sort']?>" idv="<?php  echo $v1['id']?>" /></td>
		</tr>
		<?php  }?>
		</tbody>
	</table>
	<?php  echo $pageinfo?>
	</div>
</div>
<script type="text/javascript">
$(function() {
	$(".loginValue").blur(function(){
		var id = $(this).attr('idv');
		var val = $(this).val();
		var data = {id:id, val:val};
		$.post('/News_info/news', data, function(txt){
			var msg = eval('('+txt+')');
			alert(msg.msg);

		});
	});

	$('.view').click(function(){
		var type = ( $(this).attr('name') == 1 ) ? 1 : 2;
		window.open('/index/newsid?nid='+$(this).attr('nid')+'&type='+type);
	});
});

</script>
</body>
</html>
