<?php  include PATH_TPL . "/manage/tpl.header.phtml" ?>
<style>
.loginValue {
    border: 1px solid #D5D5D5;
    float: left;
    height: 29px;
    line-height: 29px;
    margin-right: 15px;
    padding: 3px;
    width: 200px;
}
</style>
<script>
	var editor;
	KindEditor.ready(function(K) {
		editor = K.create('textarea[name="content"]', {
			resizeType : 1,
			allowPreviewEmoticons : false,
			allowImageUpload : false,
			items : [
				'source', 'fontname', 'fontsize', 'forecolor','|',  'bold', 'italic', 'underline',
				'removeformat', '|', 'justifyleft', 'justifycenter', 'justifyright', 'link', 'image'],
			colorTable : [
					['#FF0000', '#E56600', '#FF9900', '#64451D', '#DFC5A4', '#FFE500'],
					['#009900', '#006600', '#99BB00', '#B8D100', '#60D978', '#00D5FF'],
					['#337FE5', '#003399', '#4C33E5', '#9933E5', '#CC33E5', '#EE33EE'],
					['#FFFFFF', '#CCCCCC', '#999999', '#666666', '#333333', '#000000']
			]
		});
	});
</script>
<form method="post">
<input id="yaf_id" name="id" type="hidden" value="<?php if(!empty($data['id'])) echo $data["id"]?>"/>
  <fieldset>
    <legend><h3 class="title">发布消息</h3></legend>
    <table class="formtable">
      <tbody>
			<tr>
				<th>主题</th>
				<td><input class="loginValue" type='text' name ='title' value="<?php if(!empty($data['title']))echo Tool_Str::safestr($data["title"], '无')?>"> </td>
			</tr>
			<tr>
				<th>消息内容</th>
				<td>
			<!--	<script type="text/plain" id="myEditor" name="content" style="width:800px;height:240px;">-->
					<textarea name="content" style="width:700px;height:400px;visibility:hidden;"><?php if(!empty($data['content'])) echo $data['content'];?></textarea>
			<!--	</script>-->
   <!-- <script type="text/javascript">
    //实例化编辑器
    var ue = UM.getEditor('myEditor');
    ue.addListener('blur',function(){
        $('#focush2').html('编辑器失去焦点了')
    });
    ue.addListener('focus',function(){
        $('#focush2').html('')
    });
</script> -->
</td>
			</tr>
            <tr>
            	<td>针对终端类型</td>
            	<td>
            	<?php  $type=array(); if(!empty($data['receive'])) $type = explode(',', $data['receive']);?>
            	<input type="checkbox" name="receive[]" value='1' <?php  if(in_array(1, $type)){?> checked<?php  }?>> 手机
            	<input type="checkbox" name="receive[]" value='2' <?php  if(in_array(2, $type)){?> checked<?php  }?>> 平台
            	</td>
            </tr>
            <tr>
                <td>新闻类型</td>
                <td>
                <input type="radio" name="category" value='1' <?php  if( isset($data) && $data['category'] == 1){?> checked<?php  }?>> 系统公告
                <input type="radio" name="category" value='2' <?php  if( isset($data) && $data['category'] == 2){?> checked<?php  }?>> 行业新闻
                </td>
            </tr>
      </tbody>
    </table>
  </fieldset>
 <fieldset><input class="submit" type="submit" value="发布"></fieldset>
</form>
</body>
</html>
