<?php  include PATH_TPL . "/manage/tpl.header.phtml" ?>
<style>
.loginValue {
    border: 1px solid #D5D5D5;
    float: left;
    height: 29px;
    line-height: 29px;
    margin-right: 15px;
    padding: 3px;
    width: 200px;
}
.select{width:80px; height:30px; border:1px #D5D5D5 solid;}
</style>
<script>
	var editor;
	KindEditor.ready(function(K) {
		editor = K.create('textarea[name="message"]', {
			resizeType : 1,
			allowPreviewEmoticons : false,
			allowImageUpload : false,
			items : [
				'source', 'fontname', 'fontsize', 'forecolor','|',  'bold', 'italic', 'underline',
				'removeformat', '|', 'justifyleft', 'justifycenter', 'justifyright', 'link'],
			colorTable : [
					['#FF0000', '#E56600', '#FF9900', '#64451D', '#DFC5A4', '#FFE500'],
					['#009900', '#006600', '#99BB00', '#B8D100', '#60D978', '#00D5FF'],
					['#337FE5', '#003399', '#4C33E5', '#9933E5', '#CC33E5', '#EE33EE'],
					['#FFFFFF', '#CCCCCC', '#999999', '#666666', '#333333', '#000000']
			]
		});
	});
</script>
<form method="post">
  <fieldset>
    <legend><h3 class="title">发布消息</h3></legend>
    <table class="formtable">
      <tbody>
			<tr>
				<th>主题</th>
				<td><input class="loginValue" type='text' name ='title' value="" style="width:600px;"> </td>
			</tr>
			<tr>
				<th>消息内容</th>
				<td>
					<textarea name="message" style="width:400px;height:200px;visibility:hidden;"></textarea>
				</td>
			</tr>
            <tr>
            	<td>针对用户</td>
            	<td>
                用户等级:<select name="lv" class="select">
                            <option value="">等级</option>
                            <?php foreach($lv as $k=>$v){?>
                            <option value="<?php  echo $v['credit']?>"><?php  echo $v['level']?></option>
                            <?php }?>
    					</select>

            	<input type="checkbox" name="ybc" value='ybc' style="margin-left:10px;"> YBC余额≥1
				<input type="checkbox" name="rmb" value='rmb' style="margin-left:10px;"> 人民币余额≥100
            	</td>
            </tr>
			<tr>
            	<td>针对用户UID</td>
            	<td>
					<input class="loginValue" type='text' name ='uid' style="width:600px" value="">
            	</td>
            </tr>
			<tr>
            	<td>是否对全部用户</td>
            	<td>
					<input type="Radio" name="user" value='0' style="margin-left:10px;" checked> 否
					<input type="Radio" name="user" value='1' style="margin-left:10px;"> 是
            	</td>
            </tr>
      </tbody>
    </table>
  </fieldset>
 <fieldset><input class="submit" type="submit" value="发布"></fieldset>
</form>
</body>
</html>
