<?php  include PATH_TPL . "/manage/tpl.header.phtml" ?>
<?php  if(isset($msg)){?><div class="msg<?php  echo isset($msg[1])?$msg[1]:''?>"><?php  echo $msg[0]?></div><?php  }?>
<form method="post">
	<input id="yaf_cid" name="cid" type="hidden"/>
	<fieldset>
		<legend><h3 class="title">分类编辑</h3></legend>
		<table class="formtable">
			<tbody>
			<tr>
				<th>上级分类</th>
				<td>
          <?php  echo Tool_Fnc::cattree('pid')?>
				</td>
			</tr>
			<tr>
				<th>名称</th>
				<td><input id="yaf_name" name="name" onblur="ajax.pinyin(this.value, 'yaf_py')"/></td>
			</tr>
			<tr>
				<th>拼音</th>
				<td><input id="yaf_py" name="py"/></td>
			</tr>
			<tr>
				<th>排序</th>
				<td>
					<select name="ob" id="yaf_ob">
            <?php  for ($i = 0; $i < 256; ++$i) { ?>
						<option value="<?php  echo $i?>"><?php  echo $i?></option>
            <?php  }?>
					</select> 数字愈大，排序愈靠前
				</td>
			</tr>
			</tbody>
		</table>
	</fieldset>
	<fieldset><input type="submit" value="保存" class="submit"></fieldset>
</form>
<script type="text/javascript">
	$(document).ready(function () {
  <?php  if (isset($data)) { ?>
		$('#yaf_cid').val('<?php  echo $data['cid']?>');
		$('#yaf_pid').val('<?php  echo $data['pid']?>');
		$('#yaf_name').val('<?php  echo $data['name']?>');
		$('#yaf_py').val('<?php  echo $data['py']?>');
		$('#yaf_ob').val('<?php  echo $data['ob']?>');
  <?php  } elseif(isset($_GET['pid'])) { ?>
		$('#yaf_pid').val('<?php  echo $_GET['pid']?>');
  <?php  } ?>
	});
</script>
</body>
</html>