<?php  include PATH_TPL."/manage/tpl.header.phtml"?>
<script type="text/javascript">
function saveOB(pk){
	$.post('/manage_editor/ob',{ob:$('#'+pk).val(), id:pk, type:'category'},"JSON");
}
</script>
<div class="mod">
	<div class="hd">
		<h3 class="title">
      分类 <a href='/manage_setting/categorysave' title='添加顶级分类'><img src='/img/pma/b_snewtbl.png'></a>
    </h3>
	</div>
	<div class="bd">
	<table class="table_s01">
		<thead>
			<tr>
        <th width="60">操作</th>
				<th width="70">排序</th>
				<th width='100'>id</th>
				<th>分类名称</th>
				<th width='210'>url</th>
			</tr>
		</thead>
		<tbody>
<?php 
function tree(&$datas, $i, $count){
foreach ($datas[$i] as $v1){
echo '<tr>',
	"<td class='ta-right'>",
		"<a href='/manage_setting/categorysave?pid={$v1['cid']}' title='添加下级分类'><img src='/img/pma/b_snewtbl.png'></a> ",
		"<a href='/manage_setting/categorysave?cid={$v1['cid']}' title='修改'><img src='/img/pma/b_edit.png'></a> ",
		"<a href='/manage_setting/categorydel/id/{$v1['cid']}' title='删除'><img src='/img/pma/b_drop.png'></a>",
		"</td>",
	"<td><input size='3' id='ob{$v1['cid']}' value='{$v1['ob']}' title='{$v1['ob']}' onblur='WVKE.blurpost(\"/manage_setting/categoryajaxsave\", {cid:{$v1['cid']},ob:this.value}, \"ob{$v1['cid']}\")'/></td>",
	"<td>{$v1['cid']}</td>",
	"<td>",str_repeat("　　",$count),
		"{$v1['name']}";
		if(in_array($v1['mid'], array(CategoryModel::MID_ARTICLE_LIST, CategoryModel::MID_PRODUCT_LIST)))
		echo " <a href='/manage_editor/info/cid/{$v1['cid']}' target='_blank' title='查看列表'><img src='/img/pma/b_sbrowse.png'></a>";
		echo "</td>",
	"<td><input id='py{$v1['cid']}' value='{$v1['py']}' title='{$v1['py']}' onblur='WVKE.blurpost(\"category\", {cid:{$v1['cid']},py:this.value}, \"py{$v1['cid']}\")'></td>",
	"</tr>";
isset($datas[$v1['cid']]) && tree($datas, $v1['cid'], $count+1);
}
}
$datas && tree($datas, 0, 0);
?>
		</tbody>
	</table>
	</div>
</div>
</body>
</html>