<?php include PATH_TPL."/manage/tpl.header.phtml";?>
<style>
	.bind-user {width: 400px;height: 300px;margin-left: 50px;font-size:14px;}
	.bind-user h3 {height: 80px;line-height: 80px;}
	.bind-user p {margin-bottom: 20px;}
	.bind-user input[type=text] {width: 300px;height: 25px;border: #e3e3e3 1px solid;}
	.bind-user input[type=submit] {width: 120px;height: 30px;border: #e3e3e3 1px solid;color: #fff;background: #163483;border-radius: 5px;}
	#role-id {width: 300px;height: 25px;border: #e3e3e3 1px solid;}
</style>
<div class="mod">
	<div class="hd">
		<h3 class="title">设置角色</h3>
	</div>
	<div class="bind-user">
		<h3>绑定管理员角色关系</h3>
		<form method="post" onsubmit="return checkForm();">
			<p><span style="display:block;">用户ID：</span><input type="text" id="uid" value="<?=$uid?>" readonly /></p>
			<p><span style="display:block;">角色：</span>
				<select name="role" id="role-id">
					<option value="">--请选择角色--</option>
					<?foreach ($role_select as $v) {?>
						<option value="<?=$v['role_id']?>" <?if(isset($roleData) && $roleData['role_id']==$v['role_id']){?>selected<?}?> ><?=$v['role_name']?></option>
					<?}?>
				</select>
			</p>
			<p>
				<span><input type="submit" id="bind-user-btn" value="确定" /></span>
				<!-- <span><input type="submit" id="unbind-user-btn" value="解除绑定" /></span> -->
			</p>
		</form>
	</div>
</div>

<script>
	function checkForm(){
		if( !$('#role-id').val() ){
			alert('请选择角色');return false;
		}
	}
</script>

</body>
</html>
