<?php  include PATH_TPL.'/manage/tpl.header.phtml'?>
<?php  if(isset($msg)){?><div class="msg<?php  echo isset($msg[1])?$msg[1]:''?>"><?php  echo $msg[0]?></div><?php  }?>
<form>
<fieldset>
	<legend>生成模板</legend>
		<table class="formtable">
			<tbody>
			<tr>
				<th>标题：</th>
				<td>
					<select name="table" onchange="setFileName(this.value)">
					<option value="">请选择数据表</option>
					<?php  foreach ($tables as $v1){?>
					<option value="<?php  echo $v1[0]?>"><?php  echo $v1[0]?></option>
					<?php  }?>
					</select>
				</td>
			</tr>
			<tr>
				<th>文件名：</th>
				<td>
					<input id="list" name="list" /> 列表页<br />
					<input id="save" name="save" /> 增改页<br />
					[user/userlist] = [views/admin/user/userlist.html]
				</td>
			</tr>
		</tbody>
		</table>
</fieldset>
<fieldset><input class="submit" type="submit" value="生成"></fieldset>
</form>
<script type="text/javascript">
function setFileName(t){
	$('#list').val(t+'/list');
	$('#save').val(t+'/save');
}
</script>
</body>
</html>