<?php  include PATH_TPL . "/manage/tpl.header.phtml" ?>
<style>
.loginValue{border: 1px solid #D5D5D5;float: left;height: 29px;line-height: 29px;margin-right: 15px;padding: 3px;width: 224px;}
</style>
<form method="post" onsubmit="return checkInput();">
  <fieldset>
    <legend><h3 class="title">获取用户转出币邮件链接</h3></legend>
    <table class="formtable">
      <tbody>
			<tr>
				<th>请输入用户ID</th>
				<td>
					<input type="text" name="uid" id="uid" placeholder="请输入用户ID" class="loginValue"/>
				    <input type="text" name="coin" id="coin" placeholder="请输入转出币种" class="loginValue"/>
				    <input type="text" name="oid" id="oid" placeholder="请输入订单ID" class="loginValue"/>
				</td>
			</tr>
			<tr>
				<th>邮箱确认链接</th>
                <td><input type="text" value="<?php  echo $ok_str?>" class="loginValue" style="width:800px;"/></td>
			</tr>
			<tr>
				<th>邮箱取消链接</th>
                <td><input type="text" value="<?php  echo $cancel_str?>" class="loginValue" style="width:800px;"/></td>
			</tr>
      </tbody>
    </table>
  </fieldset>
	<fieldset><input class="submit" type="submit" value="获取"></fieldset>
</form>
</body>
</html>
<script>
	function checkInput(){
		if( !$('#uid').val() || !$('#coin').val() || !$('#oid').val() ){
			alert('请确保用户ID、转出币种和订单ID填写完整');return false;
		}
	}
</script>
