<?php  include PATH_TPL . "/manage/tpl.header.phtml" ?>
<style>
.loginValue{border: 1px solid #D5D5D5;float: left;height: 29px;line-height: 29px;margin-right: 15px;padding: 3px;width: 224px;}
</style>
<form method="post">
  <fieldset>
    <legend><h3 class="title">获取用户绿色通道唯一绑定码</h3></legend>
    <table class="formtable">
      <tbody>
			<tr>
				<th>请输入用户ID</th>
				<td><input type="text" name="uid" value="" placeholder="请输入用户ID" class="loginValue"/></td>
			</tr>
			<tr>
				<th>绿色通道唯一绑定码</th>
                <td><input type="text" value="<?php  echo $ok_str?>" class="loginValue" style="width:800px;"/></td>
			</tr>
      </tbody>
    </table>
  </fieldset>
	<fieldset><input class="submit" type="submit" value="获取"></fieldset>
</form>
</body>
</html>
