<?php  include PATH_TPL . "/manage/tpl.header.phtml" ?>
<style>
.loginValue{border: 1px solid #D5D5D5;float: left;height: 29px;line-height: 29px;margin-right: 15px;padding: 3px;width: 224px;}
.date{ cursor:pointer; background:url(../images/dateIco.png) no-repeat right center;}
.calender{ width:200px; margin:50px auto; top:0; left:0; border:4px #D6D6D6 solid; background:#EBEBEB; position:absolute; display:none; z-index:999;}
.calendertb{width:100%;}
.calendertb td{width:35px; height:30px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; font-size:14px; font-weight:bold;}
.calendertb td.hover,.calendertb td.weekendhover{background:#D6D6D6;}
.calendertb th{width:35px; height:30px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; color:#979797; }
.tdtoday{ background:#0080FF;color:#fff;width:35px; height:35px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; font-size:14px; font-weight:bold;}
.getyear{ height:35px; line-height:35px; width:100%; text-align:center;}
.preMonth{ font-size:14px; font-weight:bold; cursor:pointer; margin-right:18px;color:#0080FF;}
.nextMonth{ font-size:14px; font-weight:bold; cursor:pointer; margin-left:18px;color:#0080FF;}
.zhezhao{width:100%; height:100%; position:fixed; z-index:998;	background:#fff;filter:alpha(opacity=10);opacity:0.1; display:none; }
.select{width:100px; height:24px; border:2px #AA9FFF solid;}
textarea{width:396px; height:100px; border:1px solid #d5d5d5; font-size:14px; padding:5px;}
</style>
<form method="post">
<input name="uid" class="loginValue" value="<?php  echo $uid?>" type="hidden"/>
<input name="id" class="loginValue" value="<?php  echo $id?>" type="hidden"/>
  	<fieldset>
    		<legend><h3 class="title">发货信息修改</h3></legend>
    		<table class="formtable">
      			<tbody>
					<tr>
						<th>uid</th>
						<td><input name="ybuid" class="loginValue" value=""/></td>
					</tr>
      				<tr>
        				<th>email</th>
        				<td><input name="ybemail" class="loginValue" value=""/></td>
      				</tr>
      			</tbody>
    		</table>
  	</fieldset>
	<fieldset><input class="submit" type="submit" value="确定"></fieldset>
</form>
</body>
</html>
