<?php include PATH_TPL . "/manage/tpl.header.phtml" ?>
<style>
.loginValue{border: 1px solid #D5D5D5;float: left;height: 29px;line-height: 29px;margin-right: 15px;padding: 3px;width: 224px;}
</style>
<form method="post">
  <fieldset>
    <legend><h3 class="title">添加黑名单IP库</h3></legend>
    <table class="formtable">
      <tbody>
			<tr>
				<th>IP</th>
				<td><input type="text" name="ip" value="" class="loginValue"/></td>
			</tr>
      </tbody>
    </table>
  </fieldset>
	<fieldset><input class="submit" type="submit" value="添加"></fieldset>
	<fieldset>
	<legend><h3 class="title">黑名单IP库</h3></legend>
	<table class="table_s01">
      <tbody>
			<tr>
				<th>IP</th>
				<th>添加人UID</th>
			</tr>
		<?foreach($data as $v){?>
			<tr>
				<td><?=$v['ip']?></td>
				<td><?=$v['auid']?></td>
			</tr>
		<?}?>
      </tbody>
    </table>
	</fieldset>
</form>
</body>
</html>
