<?php include PATH_TPL."/manage/tpl.header.phtml"?>
<?$type = array('未发货','已发货','确认收货', '取消订单')?>
<div class="mod">
	<div class="hd">
		<h3 class="title">人民币</h3>
		<ul class="tabs">
			<li<?if($status=='') echo ' class="cur"'?>><a href="/manage_info/cardout/">全部</a></li>
			<li<?if($status=='0') echo ' class="cur"'?>><a href="/manage_info/cardout/status/0">未发货</a></li>
			<li<?if($status=='1') echo ' class="cur"'?>><a href="/manage_info/cardout/status/1">已发货</a></li>
			<li<?if($status=='2') echo ' class="cur"'?>><a href="/manage_info/cardout/status/2">确认收货</a></li>
			<li<?if($status=='3') echo ' class="cur"'?>><a href="/manage_info/cardout/status/3">取消订单</a></li>
		</ul>
		<form style="float:right" method='get' action=''>
        <input name="kw" value="<?=isset($_GET['kw'])&&!empty($_GET['kw']) ? $_GET['kw'] : ''?>">
			<select id="yaf_field" name="id">
				<option value="" <?if(!isset($_GET['id'])){echo 'selected';} else {'';}?>>全部</option>
				<option value="uid" <?if(isset($_GET['id'])&&$_GET['id']=='uid'){echo 'selected';} else {'';}?>>购买者ID</option>
				<option value="cid" <?if(isset($_GET['id'])&&$_GET['id']=='cid'){echo 'selected';} else {'';}?>>订单ID</option>
			</select>
			<input type="submit" value="搜索">
		</form>
	</div>
	<div class="bd">
	<table class="table_s01">
		<thead>
			<tr>
				<th width="100">操作</th>
				<th>订单id</th>
				<th>购买用户id</th>
				<th>姓名</th>
				<th>电话</th>
				<th>地址</th>
				<th>订单信息</th>
				<th>状态</th>
				<th>创建时间</th>
				<th>快递单号</th>
			<!--	<th>发货卡号</th>-->
			</tr>
		</thead>
		<tbody>
		<?php foreach ($datas as $v1){?>
		<tr>	
			<td>
			<?if($v1["status"]=='0'){?>
				<button onclick="WVKE.confirm('/manage_info/cancel/id/<?=$v1['id']?>', 'ok')">取消</button>
				<button onclick="WVKE.confirm('/manage_info/cardedit/id/<?=$v1['id']?>', 'ok')">修改信息</button>
				<button onclick="WVKE.confirm('/manage_info/cardok/id/<?=$v1['id']?>', 'ok')">确认发货</button>
			<?}else if($v1["status"]=='1'){?>
				<button onclick="WVKE.confirm('/manage_info/confirm/id/<?=$v1['id']?>', 'ok')">确认收货</button>
           
			<?}?>
			</td>
			<td><?=$v1["cid"]?></td>
			<td><?=$v1["uid"]?></td>
			<td><?=Tool_Str::safestr($v1["name"])?></td>
			<td><?=$v1["phone"]?></td>
			<td><?=$v1["address"]?></td>
			<td><?=$v1["info"]?></td>
			<td><?=$type[$v1["status"]]?></td>
			<td><?=date('Y-m-d H:i:s', $v1["ctime"])?></td>
			<td><?=$v1["kdid"]?></td>
		</tr>
		<?php }?>
		</tbody>
	</table>
	<?=$pageinfo?>
	</div>
</div>
</body>
</html>
