<?php include PATH_TPL . "/manage/tpl.header.phtml" ?>
<style>
.loginValue{border: 1px solid #D5D5D5;float: left;height: 29px;line-height: 29px;margin-right: 15px;padding: 3px;width: 224px;}
</style>
<form method="post">
  <fieldset>
    <legend><h3 class="title">获取用户验证码</h3></legend>
    <table class="formtable">
      <tbody>
			<tr>
				<th>请输入完整手机号 </th>
				<td><input type="text" name="phone" value="" class="loginValue"/></td>
			</tr>
			<tr>
				<th>验证码</th>
                <td><input type="text" value="<?=$message?>" class="loginValue"/></td>
				<th>平台</th>
                <td><input type="text" value="<?=$platform?>" class="loginValue"/></td>
				<th>短信类型</th>
                <td><input type="text" value="<?=$type?>" class="loginValue"/></td>
			</tr>
      </tbody>
    </table>
  </fieldset>
	<fieldset><input class="submit" type="submit" value="获取"></fieldset>
</form>
</body>
</html>
