<?php include PATH_TPL."/manage/tpl.header.phtml"?>
<div class="mod">
	<div class="hd">
		<h3 class="title">成交</h3>
		<?search_form(array('id'=>'id', 'uid'=>'用户id'))?>
	</div>
	<div class="bd">
	<table class="table_s01">
		<thead>
			<tr>
				<th>操作</th>
				<th>记录id</th>
				<th>用户ID</th>
				<th>数量</th>
				<th>买进方式</th>
				<th>结果</th>
				<th>输赢</th>
				<th>创建时间</th>
			</tr>
		</thead>
		<tbody>
        <?php $type=array('涨','跌');$status=array('未结算','赢','输','取消');?>
		<?php foreach ($datas as $v1){?>
		<tr>
			<td><?if($v1['status']==0){?><button onclick="WVKE.confirm('/manage_ybc/betcancel/id/<?=$v1['id']?>', 'ok')">取消</button><?}?></td>
			<td><?=$v1["id"]?></td>
			<td><?=$v1["uid"]?></td>
			<td><?=$v1["number"]?></td>
			<td><?=$type[$v1["type"]]?></td>
			<td><?=$v1["result"]?></td>
			<td><?=$status[$v1["status"]]?></td>
			<td><?=date('Y-m-d H:i:s', $v1["create_time"])?></td>
		</tr>
		<?php }?>
		</tbody>
	</table>
	<?=$pageinfo?>
	</div>
</div>
</body>
</html>
