<?php include PATH_TPL."/manage/tpl.header.phtml";?>
<style>
	.loginValue{border: 1px solid #D5D5D5;float: left;height: 29px;line-height: 29px;margin-right: 15px;padding: 3px;width: 400px;}
	select{width: 100px;height: 40px;font-size: 18px;font-weight: bolder;}
</style>
<div class="mod">
	<div class="hd">
		<h3 class="title">一键撤单</h3>
	</div>
	<div class="bd">
		<table class="formtable">
 			<form method="post" onsubmit="return checkForm();">
	 			<tbody>
	 				<tr>
	 					<th>用户ID</th>
	 					<td><input name="uid" id="uid" class="loginValue" placeholder="选填，填写则撤销所填id的所有委托单" /></td>
	 				</tr>
	 				<tr>
	 					<th>币种</th>
	 					<td>
	 						<select name="coin" id="coin">
	 							<option value="">请选择币种</option>
	 							<? foreach ($pairs as $v) { ?>
	 								<option value="<?=$v['coin_from']?>"><?=strtoupper($v['coin_from'])?></option>
	 							<? } ?>
	 						</select>
	 					</td>
	 				</tr>
	 				<tr>
	 					<th>&nbsp;</th>
	 					<td>&nbsp;</td>
	 				</tr>
	 				<tr>
	 					<th>&nbsp;</th>
	 					<td><input class="submit" type="submit" value="确定"></td>
	 				</tr>
	 			</tbody>
	 		</form>
 		</table>
	</div>
</div>
</body>
</html>

<script>
	function checkForm(){
		if( !$('#coin').val() ){
			alert('请先选择要撤单的币种');return false;
		}

		var str = '';
		if( $('#uid').val() ){
			str += '您确定要撤销 '+$('#uid').val()+' 所有的 '+$('#coin').val().toUpperCase()+' 委托单？';
		}else{
			str += '您确定要撤销所有用户的 '+$('#coin').val().toUpperCase()+' 委托单？';
		}

		if(confirm(str)){
			return true;
		} else{
			return false;
		}
	}
</script>
