<?php include PATH_TPL."/manage/tpl.header.phtml"; ?>
<style>
.form{height:40px; line-height:40px;float:right;margin:10px 0;}
.date{width:150px; height:11px; line-height:11px; padding:5px; border:1px #AA9FFF solid; cursor:pointer; background:url(../images/dateIco.png) no-repeat right center;}
.calender{ width:200px; margin:50px auto; top:0; left:0; border:4px #D6D6D6 solid; background:#EBEBEB; position:absolute; display:none; z-index:999;}
.calendertb{width:100%;}
.calendertb td{width:35px; height:30px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; font-size:14px; font-weight:bold;}
.calendertb td.hover,.calendertb td.weekendhover{background:#D6D6D6;}
.calendertb th{width:35px; height:30px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; color:#979797; }
.tdtoday{ background:#0080FF;color:#fff;width:35px; height:35px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; font-size:14px; font-weight:bold;}
.getyear{ height:35px; line-height:35px; width:100%; text-align:center;}
.preMonth{ font-size:14px; font-weight:bold; cursor:pointer; margin-right:18px;color:#0080FF;}
.nextMonth{ font-size:14px; font-weight:bold; cursor:pointer; margin-left:18px;color:#0080FF;}
.zhezhao{width:100%; height:100%; position:fixed; z-index:998;	background:#fff;filter:alpha(opacity=10);opacity:0.1; display:none; }
.select{width:100px; height:24px; border:2px #AA9FFF solid;}
.page{float: left;}
.tongji{width:auto;float: right;height: 44px;}
.tongji span{margin-left: 20px;font-size: 18px;color:red;height: 44px;line-height: 44px;}
.searchInput{margin-left:10px;}
.outInput{margin:12px 0 0 10px;}
</style>
<link rel="stylesheet" type="text/css" href="/css/calendar/jquery.datetimepicker.css"/>
<script src="/js/calendar/jquery.datetimepicker.js"></script>
<? $status = Trust_CoinModel::$status?>
<? $allCoins = User_CoinModel::getInstance()->getList(); ?>
<div class="mod">
	<div class="hd">
		<select onchange='window.location.href = "/manage_ybc/trust?coin="+this.value' class="title" style="width: 100px;height: 30px;font-size: 18px;font-weight: bolder;margin-left: 10px;">
			<option value="all" <?if('all'==$coin){?>selected<?}?> >全部</option>
			<? foreach ($allCoins as $key => $value) { ?>
				<option value="<?=$value['name']?>" <?if($value['name']==$coin){?>selected<?}?> ><?=$value['display']?></option>
			<? } ?>
		</select>
		<!-- <h3 class="title">委托</h3> -->
		<ul class="tabs">
			<li<?if($cur==-2) echo ' class="cur"'?>><a href="/manage_ybc/trust?coin=<?=$coin?>">全部</a></li>
			<li<?if($cur==-1) echo ' class="cur"'?>><a href="/manage_ybc/trust?isnew=1&coin=<?=$coin?>">未处理</a></li>
			<? foreach($status as $k1 => $v1){?>
				<li<?if($cur==$k1) echo ' class="cur"'?>><a href="/manage_ybc/trust?status=<?=$k1?>&coin=<?=$coin?>"><?=$v1?></a></li>
			<? }?>
		</ul>
		<!-- <?search_form(array('uid'=>'用户', 'flag'=>'买卖标志', 'coin_from'=>'币种'))?> -->
		<div class="form">
			<form action="/manage_ybc/trustcsv" method="post" style="float: right">
				<input type="hidden" name="status" value="<?=$cur?>">
				<input type="hidden" name="coin" value="<?if(isset($coin)) echo $coin?>">
				<input type="hidden" name="kw" value="<?if(isset($kw)) echo $kw?>">
				<input type="hidden" name="field" value="<?=isset($field)?$field:'uid'?>">
				<input type="hidden" name="hasTime" value="<?=($hasTime==1)?1:0?>">
				<input type="hidden" name="stime" value="<?=$stime?>">
				<input type="hidden" name="etime" value="<?=$etime?>">
				<? if($btnAuth['ybc_trust_out']){ ?>
					<input type="submit" class="outInput" value="导出">
				<? } ?>
			</form>
			<form method="post" style="float: right">
				<input name="kw" value="<?if(isset($kw)) echo $kw?>">
				<select id="yaf_field" name="field">
					<option value="uid">uid</option>
					<option value="flag">买卖标识</option>
					<!-- <option value="coin_from">币种</option> -->
				</select>
	      		<script>$('#yaf_field').val('<?=isset($field)?$field:'uid'?>')</script>
	      		<span style="margin: 0 10px;"><input type="checkbox" name="hasTime" value="1" <?if($hasTime==1){?>checked<?}?> >是否筛选时间</span>
	      		开始时间:<input type="text" class="date" value="<?=date('Y-m-d H:i', $stime)?>" id="date-start" name="stime" readonly="true" /> 结束时间:<input type="text" class="date" value="<?=date('Y-m-d H:i', $etime)?>" id="date-end" name="etime" readonly="true" />
				<input type="submit" class="searchInput" value="搜索">
			</form>
		</div>
	</div>
	<div class="bd">
	<table class="table_s01">
		<thead>
			<tr>
				<th>操作</th>
				<th>id</th>
				<th>用户id</th>
				<th>币种</th>
				<th>单价</th>
				<th>数量</th>
				<th>剩余数量</th>
				<th>买卖标志</th>
				<th>新委托</th>
				<th>状态</th>
				<th style="min-width: 135px;">创建时间</th>
				<th style="min-width: 135px;">更新时间</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($datas['list'] as $v1){?>
		<tr>
			<td>
				<? if($btnAuth['ybc_trust_cancel']){ ?>
					<?if(in_array($v1['status'],array(0,1))){?><button onclick="WVKE.confirm('/manage_ybc/trustcancel/id/<?=$v1['id']?>', 'ok')">撤销</button><?}?>
				<? } ?>
			</td>
			<td><?=$v1["id"]?></td>
			<td><?=$v1["uid"]?></td>
			<td><?=$v1["coin_from"]?></td>
			<td><?=$v1["price"]?></td>
			<td><?=$v1["number"]?></td>
			<td><?=$v1["numberover"]?></td>
			<td><?=$v1["flag"]?></td>
			<td><?=$v1["isnew"]?></td>
			<td><?=$status[$v1["status"]]?></td>
			<td><?=date('Y-m-d H:i:s', $v1["created"])?></td>
			<td><? if($v1["updated"]) echo date('Y-m-d H:i:s', $v1["updated"])?></td>
		</tr>
		<?php }?>
		</tbody>
	</table>
	<?=$datas['pageinfo']?>
	<p class="tongji">
		<span>总笔数：<?=$datas['total'][0]['num']?></span>
		<span>总数量：<?= isset($datas['total'][0]['number']) ? (float)$datas['total'][0]['number'] : 0?></span>
	</p>
	</div>
</div>
</body>
</html>
<script>
	$(function(){
		// 关键字和搜索字段
		var kw = "<?=$kw?>";
		var field = "<?=$field?>";
		var coin = "<?=$coin?>";
		if( kw ){
			var kwstr = '&kw=' + kw + '&field=' + field;
		}else if( coin != 'all' ){
			var kwstr = '&coin=' + coin;
		}else{
			var kwstr = '';
		}

		var hasTime = "<?=$hasTime?>";

		$('.pageUl li').each(function(){
			var oldHref = $(this).find('a').attr('href');

			var prega = oldHref.match(/p=(\d*)$/);
			var pregb = oldHref.match(/p=(\d*)&/);
			if( prega != null ){
				var p = prega[1];
			}else if( pregb != null ) {
				var p = pregb[1];
			}else{
				var p = 1;
			}

			if(hasTime==1){
				var start = $('#date-start').val();
				var end = $('#date-end').val();

				var newHref = '?p=' + p + '&hasTime=1&stime=' + start + '&etime=' + end + kwstr;
			}else{
				var newHref = '?p=' + p + kwstr;
			}

			$(this).find('a').attr('href', newHref);
		});
	});
</script>
<script>
	$('#date-start').datetimepicker();
	$('#date-end').datetimepicker();
</script>
