<? include PATH_TPL.'/tpl.header.phtml'?>
<!-- <div class="content clear">
	<div class="Left">
		<div class="accountBox">
			<div class="wrap"><? include PATH_TPL.'/index/tpl.left.phtml'?></div>
		</div>
	</div>
	<div class="Right">
		<div class="accountBox">
			<div class="wrap">
				<div class="box">
					<div class="TitleBox">
						<h3 class="PlateTitle">关于我们</h3>
					</div>
					<div class="aboutText">
						<p></p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div> -->
<div class="about_content">
	<div class="ab_listinfo">
		<div class="abcontent_info1 clear">
			<div class="abinfolt left">
				<h2>平台</h2>
				<h6>顶级交易平台</h6>
				<em></em>
				<p>币交所（www.bijiaosuo.com）成立于2016年，是面向全球开放的数字货币交易平台，隶属于深圳布罗克城网络科技有限公司，注册资金达1000万人民币，致力于提供行业内最优质的客户服务，及打造行业内最优最顶级的系统平台。</p>
			</div>
			<div class="abinfort right">
				<img src="/img/about_01.png" alt="币交所">
			</div>
		</div>
	</div>
	<div class="ab_listinfo">
		<div class="abcontent_info2 clear">
			<div class="abinfort left">
				<img src="/img/about_02.png" alt="币交所">
			</div>
			<div class="abinfolt right">
				<h2>优势</h2>
				<h6>最合理的架构</h6>
				<em></em>
				<p>我们拥有一套完善的独属于本公司的运营方案。24小时平台交易，多重加密安全技术，十年金融经验安全团队，全球顶级区块链技术支持，以保障币交所平台的安全稳定。充值即时到账，取款最快两小时，全天候客服为客户提供专业的指导服务，最大化的让客户体验到币交所的各项优势。</p>
			</div>
		</div>
	</div>
	<div class="ab_listinfo">
		<div class="abcontent_info3 clear">
			<div class="abinfolt left">
				<h2>团队</h2>
				<h6>精英团队</h6>
				<em></em>
				<p>我们的团队成员有着丰富的互联网运营经验，主要来自百度、阿里、腾讯等大型互联网公司与金融机构，包括互联网线上线下各方面的精英人才，他们打大多拥有博士硕士研究生学历，在国内外很多大型平台积累了极为丰富的工作经验，为平台的稳定和长远发展提供了坚实的保障，致力让客户感受到专业、安全、稳定的交易体验。</p>
			</div>
			<div class="abinfort right">
				<img src="/img/about_03.png" alt="币交所">
			</div>
		</div>
	</div>
	<!-- <div class="ab_listinfo ab_listinfo4">
		<div class="abcontent_info4 clear">
			<div class="abcontent_safety left">
				<img src="/img/about_04.png" alt="币交所安全">
				<h6>安全</h6>
				<p>钱包多层加密，离线存储于银行<br/>保险柜资金第三方托管，确保安全</p>
			</div>
			<div class="abcontent_zy left">
				<img src="/img/about_05.png" alt="币交所专业">
				<h6>专业</h6>
				<p>专业的客服团队，400电话和24小时<br/>在线VIP一对一专业服务</p>
			</div>
			<div class="abcontent_world right">
				<img src="/img/about_06.png" alt="币交所全球互通">
				<h6>全球互通</h6>
				<p>为您提供国际平台<br/>更多的选择，更便捷的交易</p>
			</div>
		</div>
	</div>-->

</div>
<? include PATH_TPL.'/tpl.footer.phtml'?>
