<? include PATH_TPL.'/tpl.header.phtml';?>
<style>
	.faqWrap{width: 100%; position: relative;overflow: hidden;margin-top: -20px;background: #fff;}
	.topImg{width: 100%;}
	.topImg img{width: 100%;}
	.mainCon{width: 1000px;max-width: 1000px;overflow: hidden; margin:20px auto 0;padding:20px 0;}
	.mainCon h2{font-size:26px;color: #333;line-height: 32px;margin-bottom: 30px;}
	.leftNum{float: left;width: 310px;margin-left: -20px;}
	.leftNum div{overflow: hidden;}
	.leftNum em{float: left;width: 48px;height: 48px;}
	.tel em{background: url(/img/contacticon.png) 12px -7px no-repeat; background-size: 100% auto;}
	.kefu em{background: url(/img/contacticon.png) 12px -68px no-repeat; background-size: 100% auto;}
	.email em{background: url(/img/contacticon.png) 12px -125px no-repeat; background-size: 100% auto;}
	.leftNum span{font-size: 14px;color: #666;display: block;line-height: 40px;text-indent: 10px;float: left;}
</style>
<div class="faqWrap">
	<div class="topImg">
		<img src="/img/contactus_01.jpg" alt="联系我们">
	</div>
	<div class="mainCon">
		<h2>联系我们</h2>
		<div class="leftNum">
			<div class="tel">
				<em></em>
				<span>客服电话：400-051-8422</span>
				<span>监督电话：400-051-8422</span>
			</div>
			<div class="kefu">
				<em></em>
				<div>
					<span>客服QQ1：1662906650</span>
					<span>客服QQ2：994984584</span>
					<span>官方交流群1：264880083</span>
					<span>官方交流群2：513279526</span>
				</div>
			</div>
			<div class="email">
				<em></em>
				<span>投诉邮箱：tousu@bijiaosuo.com</span>
				<span>客服邮箱：kefu@bijiaosuo.com</span>
			</div>
		</div>
	</div>
</div>
<? include PATH_TPL.'/tpl.footer.phtml';?>
