<? include PATH_TPL.'/tpl.header.phtml';?>
<style>
	.faqWrap{width: 100%; position: relative;overflow: hidden;margin-top: -20px;background: #fff;}
	.topImg{width: 100%;}
	.topImg img{width: 100%;}
	.mainCon{width: 1000px;max-width: 1000px;overflow: hidden; margin:20px auto 0;padding:20px 0;}
	.mainCon h2{font-size:26px;color: #333;line-height: 32px;}
	.mainCon h6{font-size: 18px;color: #333;line-height: 32px;margin:20px 0;}
	.mainCon p{font-size: 14px;color: #666;line-height: 26px;margin-bottom:10px;}
	.mainCon p a{text-decoration: none;color: #edad02;}
</style>
<div class="faqWrap">
	<div class="topImg">
		<img src="/img/hfaq_01.jpg" alt="常见问题">
	</div>
	<div class="mainCon">
		<h2>常见问题</h2>
		<h6>1. 登录密码是什么？忘记登录密码怎么办？ </h6>
		<p>登录密码是您登录币交所平台的重要信息，是保障您在币交所财产安全的重要凭证，请不要泄露给任何人，不要设置的过于简单，不要设置和其它平台一样的登录密码。如果您忘记登录密码：邮箱注册的用户，点击登录界面的“忘记密码”通过邮箱找回。如果由于其它原因造成你不能通过以上方式找回登录密码，请联系币交所客服拨打我们的400-051-8422，联系我们帮你解决。  </p>
		<h6>2. 交易密码是什么？忘记交易密码怎么办？</h6>
		<p>交易密码是您在币交所平台进行交易时需输入的密码，是确认交易操作是您本人操作的唯一验证方法。新注册的用户请到“个人中心”里，交易密码处，设置交易密码。如果您忘记交易密码了请联系币交所客服电话：400-051-8422 。</p>
		<h6>3. 如何绑定手机，绑定的手机丢失或者想修改绑定的手机号怎么办？  </h6>
 		<p>登录您在币交所平台的账户，在“个人中心”里，选择绑定手机号，根据提示完成绑定操作，就会绑定成功了。绑定的手机是您帐户非常重要的安全保证，如果手机丢失请立即与我们客服联系。如果要修改绑定的手机号，可以登录账户，在安全中心绑定手机处，选择“修改手机号”，根据提示修改绑定的手机号。 </p>
 		<h6>4. 如何绑定谷歌身份验证器，怎么解绑谷歌身份验证器？ </h6>
 		<p>登录您在币交所平台的账户，在“个人中心”里，选择账户双重验证，根据提示完成绑定操作。</p>
 		<h6>5. 如何充值？</h6>
 		<p>登录您在币交所平台的账户，在“个人中心”里，选择账户资产，点击人民币充值，当您充值人民币时，请您务必按照系统给你分配的小数点数额进行转账，否则会造成您无法到账，最小充值金额100元，在汇款之前确认完善订单信息，如您严格按照要求完善充值信息，将在20分钟之内到账。</p>
 		<h6>6. 如何提现？</h6>
 		<p>登录您在币交所平台的账户，在“个人中心”里，选择账户资产，点击人民币提现，先添加提现银行卡，最小提现金额为500元，完善提现信息后点击提现按钮将在24小时之内到账。</p>
	</div>
</div>
<? include PATH_TPL.'/tpl.footer.phtml';?>
