<? include PATH_TPL.'/tpl.header.phtml';?>
<?php
		// type：新闻分类，1是系统公告，2是行业新闻
		$type = $_GET['type'];
		$tMO = new NewsModel;
		$str = ($type == 1) ? ' category=1 ' : ' category=2 ';
		$data = $tMO->query("select * from {$tMO->table} where {$str} and sort>0 and receive=2 order by sort desc, id desc");
		//echo $_GET['p'];
		$tPage = new Tool_Page($tMO->where("{$str} and sort>0 and receive=2")->count(), 20);
		$data = $tMO->where("{$str} and sort>0 and receive=2")->limit($tPage->limit())->order('sort desc, id desc')->fList();
?>
<style>
.aboutText li{padding: 8px 0px;border-bottom:1px dotted #BFCBCE}

.news-row {min-height:80px;border-bottom: 1px dashed #ddd;padding:15px 0;overflow: hidden;}
/*.news-left {width: 200px;float:left;}*/
.news-right {float:left;width:100%;clear: both;}
.news-right h3 {padding: 10px 0;}
.news-desc {color:#666;font-size:13px;}
a.title-link {font-size: 18px;color:#333;}
a.title-link:hover {color:#e69e18;}
.news-detail {width:100%;height:30px;line-height: 30px;}
.news-detail span {display: block;float:right;height:30px;padding:0 5px;text-align: center;}
</style>
<div class="content clear">
	<div class="Right" style="width: 1000px;">
		<div class="accountBox">
			<div class="wrap">
				<div class="box">
					<div class="TitleBox">
						<h3 class="PlateTitle"><?if($type == 1) echo '历史公告'; else echo '历史新闻';?></h3>
					</div>
					<div class="aboutText">
						<?foreach($data as $v){?>
							<div class="news-row">
									<!-- <div class="news-left">

									</div> -->
									<div class="news-right">
										<h3>
											<a href="/index/newsid?nid=<?=$v['id']?>&type=<?=$type?>" class="title-link"><?=$v['title'];?></a>
										</h3>
										<div class="news-desc">
											<?=Tool_Str::msubstr(strip_tags($v['content'],'<a>'), 0, 200)?>...
										</div>
										<div class="news-detail">
											<span class="news-time">发布时间：<?=date('Y-m-d', $v["created"])?></span>
											<?if(1==$type) {?><span class="news-author">发布人：官方</span><?}?>
										</div>
									</div>
							</div>
						<?}?>
						<?if($data) echo $tPage->show();?>
					</div>

					<!-- <div class="aboutText">
						<ul>
							<?foreach($data as $v){?>
								<li>
										<span style="color:#666;font-size:12px; margin-right:10px;">[<?=date('Y-m-d H:i', $v["created"])?>]</span><span style="color:#666;font-size:12px; margin-right:10px;line-height:20px;font-family: 宋体;"><?=strip_tags($v['content'],'<a>')?></span>
								</li>
							<?}?>
						</ul>
						<?if($data) echo $tPage->show();?>
					</div> -->
				</div>
			</div>
		</div>
	</div>
</div>
<? include PATH_TPL.'/tpl.footer.phtml';?>
