<? include PATH_TPL.'/tpl.header.phtml';?>
<style>
	.faqWrap{width: 100%; position: relative;overflow: hidden;margin-top: -20px;background: #fff;}
	.topImg{width: 100%;}
	.topImg img{width: 100%;}
	.mainCon{width: 1000px;max-width: 1000px;overflow: hidden; margin:20px auto 0;padding:20px 0;}
	.mainCon h2{font-size:26px;color: #333;line-height: 32px;margin-bottom: 30px;}
	.mainCon p{font-size: 14px;color: #333;line-height: 26px;margin:20px 0;}
	.mainCon p a,.mainCon p span{text-decoration: none;color: #edad02;}
	.mainCon p img{width: 100%;}
</style>
<div class="faqWrap">
	<div class="topImg">
		<img src="/img/contactus_01.jpg" alt="联系我们">
	</div>
	<div class="mainCon">
		<h2>注册指南</h2>
		<p>1.首先进入币交所官网<a href="https://www.bijiaosuo.com" target="_blank;">https://www.bijiaosuo.com</a>，首页点击【注册】；</p>
		<p><img src="/img/hguide_01.jpg" alt="注册指南"></p>
		<p>2.按照页面提示填写账户基本信息（请牢记您的登录密码及交易密码），填写完成后请仔细阅读《注册协议》，如同意，请点击【同意以下协议，提交】；</p>
		<p><img src="/img/hguide_02.jpg" alt="注册指南"></p>
		<p>3.注册成功点击【立即激活邮箱】，进行邮箱激活： </p>
		<p><img src="/img/hguide_03.jpg" alt="注册指南"></p>
		<p>4.页面跳转到您注册邮箱，点击链接激活此账号。邮箱激活成功。</p>
		<p><img src="/img/hguide_04.jpg" alt="注册指南"></p>
		<p>注册中遇到问题可咨询在线客服<span>400-051-8422</span>我们24小时为您服务。</p>
	</div>
</div>
<? include PATH_TPL.'/tpl.footer.phtml';?>
