<? include PATH_TPL.'/tpl.header.phtml'?>
<div class="content clear">
	<div class="Left">
		<div class="accountBox">
			<div class="wrap"><? include PATH_TPL.'/index/tpl.left.phtml'?></div>
		</div>
	</div>
	<div class="Right">
		<div class="accountBox">
			<div class="wrap">
				<div class="box">
					<div class="TitleBox">
						<h3 class="PlateTitle">法律声明</h3>
					</div>
					<div class="aboutText">
						<p>富途币是出于教育和娱乐的目的设计的一种电子计量符号。</p>

<p>富途币的服务和运营均设在海外，目的是为了全球的富途币爱好者提供一个安全可靠的交易交流平台。本站的所有服务均出于教育和娱乐的目的，而非商业使用的目的提供。</p>

<p>我们强烈建议您遵守所在国的法律，切勿将富途币用于违法用途！否则一切后果自负，本网站不承担任何责任！</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<? include PATH_TPL.'/tpl.footer.phtml'?>