<? include PATH_TPL.'/tpl.header.phtml'?>
<div class="content clear">
	<div class="Left">
		<div class="accountBox">
			<div class="wrap"><? include PATH_TPL.'/index/tpl.left.phtml'?></div>
		</div>
	</div>
	<div class="Right">
		<div class="accountBox">
			<div class="wrap">
				<div class="box">
					<div class="TitleBox">
						<h3 class="PlateTitle">常见问题</h3>
					</div>
					<div class="aboutText">
                        <ul>
                        <li>
                        <p>
<font style="color:#ff0000;">一、人民币充值</font><br />
1、充值处理时间：1小时内到账<br>
2、充值金额最低10元<br>
3.、充值订单会在次日进行清除，用户需当日订单，当日充值，次日需要重新提交订单
</p>
                        </li>
                        <li>
<p>
 <font style="color:#ff0000;">二、人民币提现</font><br />
1、批量处理时间：9:00 -- 17:00<br>
2、到账时间：24小时内（前提必须保证收款信息填写准确，包括：开户名、开户行名称、账号，不能是信用卡）<br>
3、人民币提现单笔限额最低500元， 最高50000元，每天最高提现20万
</p>
                        </li>
                        <li>
<p>
 <font style="color:#ff0000;">三、修改密码</font><br />
1、忘记交易密码，需要联系人工客服核实身份后，帮你重置交易密码。为保证账户安全，重置后的新交易密码会发到您的注册邮箱里<br>
2、忘记登录密码，需要在网站点击忘记密码后，去注册时邮箱修改
</p>
                        </li>
                        <li>
<p>
 <font style="color:#ff0000;">四、更新账户信息</font><br />
1、如需更新个人账户信息（注册邮箱、姓名、证据号码、手机号码），需要联系人工客服核实身份后处理
</p>
                        </li>
			<li>
<p>
 <font style="color:#ff0000;">五、提现验证码</font><br />
1、使用语音验证码<br>
2、无法收到短信验证码<br>
&nbsp;&nbsp;&nbsp;&nbsp;1）检查手机号是否正确绑定<br>
&nbsp;&nbsp;&nbsp;&nbsp;2）手机是否设置了垃圾短信或黑名单<br>
&nbsp;&nbsp;&nbsp;&nbsp;3）重新发送一次试试<br>
&nbsp;&nbsp;&nbsp;&nbsp;4）联系人工客服
</p>
                        </li>
<li><p>
 <font style="color:#ff0000;">六、工作时间</font><br />
1、大盘交易时间：早6:30至晚0:30 （收盘期间所有未成交挂单将全部清除，用户需要于次日开盘后重新挂单<br>
2、人工充值工作时间：9:00 -- 17:00<br>
3、客服工作时间：9:00 -- 17:00
</p></li>
                        </ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<? include PATH_TPL.'/tpl.footer.phtml'?>
