<? include PATH_TPL.'/tpl.header.phtml'?>
<div class="content clear">
	<div class="Left">
		<div class="accountBox">
			<div class="wrap"><? include PATH_TPL.'/index/tpl.left.phtml'?></div>
		</div>
	</div>
	<div class="Right">
		<div class="accountBox">
			<div class="wrap">
				<div class="box">
					<div class="TitleBox">
						<h3 class="PlateTitle">费用说明</h3>
					</div>
					<div class="aboutText">
						<h2>交易手续费</h2>
						<p>交易手续费收取卖方0.2%</p>
						<h2>充值费用</h2>
						<p>支持网银在线支付，免手续费</p>
                        <p>1万以上充值接受银行直接转账，免手续费，银行会收取转账费用</p>
						<h2>提现费用</h2>
                        <p>转出富途币：1%手续费</p>
                        <p>人民币提现：0.5%手续费</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<? include PATH_TPL.'/tpl.footer.phtml'?>
