<? include PATH_TPL.'/tpl.header.phtml'?>
<div class="content clear">
	<div class="Left">
		<div class="accountBox">
			<div class="wrap"><? include PATH_TPL.'/index/tpl.left.phtml'?></div>
		</div>
	</div>
	<div class="Right">
		<div class="accountBox">
			<div class="wrap">
				<div class="box">
					<div class="TitleBox">
						<h3 class="PlateTitle">退款协议</h3>
					</div>
					<div class="aboutText">
						<p>我们实行无条件退款政策，您可以放心入驻。</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<? include PATH_TPL.'/tpl.footer.phtml'?>