<? include PATH_TPL.'/tpl.header.phtml'?>
<div class="content clear">
	<div class="Left">
		<div class="accountBox">
			<div class="wrap"><? include PATH_TPL.'/index/tpl.left.phtml'?></div>
		</div>
	</div>
	<div class="Right">
		<div class="accountBox">
			<div class="wrap">
				<div class="box">
					<div class="TitleBox">
						<h3 class="PlateTitle">隐私保护</h3>
					</div>
					<div class="aboutText">
						<p>保护您的隐私安全，是我们的责任和义务。</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<? include PATH_TPL.'/tpl.footer.phtml'?>