<title>上币说明-币交所-数字货币交易平台</title>
<? include PATH_TPL.'/tpl.header.phtml';?>
<div style="margin-top: -20px; width: 100%;overflow: hidden;">
<img src="/img/2_03.png" style=" display: block; width: 100%;overflow: hidden;margin: 0 auto;">
</div>
<div class="coin_clearfix">
	<h1>币交所上新币说明</h1>
	<hr  class="coin_clearf coin_width" />
	<p>申请上币请发送相关资料至邮箱：<a href="mailto:shangbi@bijiaosuo.com">shangbi@bijiaosuo.com</a>，币交所收到邮件后会发送上币申请表，请耐心等待！</p>
	<h2>特别提示</h2>
	<p>请新币团队尽可能提供完整、准确的新币相关信息，如有额外相关资料（新币白皮书、新币介绍资料等）</p>
	<p>请通过邮件附件提供，谢谢您的配合！</p>
	<h2> 特别声明</h2>
	<p class="coin_clearf">币交所不接受任何涉及非法行为的上币申请！</p>
	<hr />
	<div class="coin_clearfi">
	<p ><span>风险提示：</span>数字货币交易具有极高的风险（预挖、暴涨暴跌、庄家操控、团队解散、技术缺陷等）据国家五部委《关于防范比特币风险的通知》币交所仅为数字货币的爱好者提供一个自由的网上交换平台对币的投资价值不承担任何审查、担保、赔偿的责任，如果您不能接受,请不要进行交易！谢谢！</p>
	</div>
</div>
<? include PATH_TPL.'/tpl.footer.phtml';?>
