<div class="RightBox">
	<div class="wrap">
		<div class="box">
			<div class="TitleBox">
				<h3 class="PlateTitle">我的资产</h3>
			</div>
            <table class="Transaction">
                <thead>
                <tr>
                    <th></th>
                    <th>可用余额</th>
                    <th>冻结量</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><strong>人民币</strong></td>
                    <td><span id="ua_cny_over">加载中...</span></td>
                    <td><span id="ua_cny_lock">加载中...</span></td>
                    <td><span><a href="/user_exchange/rmbin2">充值</a>&nbsp;|&nbsp;<a href="/user_exchange/rmbout">提现</a></span></td>
                </tr>
                <script>var userPairs = [];</script>
                <? foreach ($pairs as $k => $v1) { ?>
                    <script>userPairs.push("<?=$v1['name'];?>");</script>
                    <tr>
                        <td><strong><?=$v1['display']?></strong></td>
                        <td><span id="ua_<?=$v1['name']?>_over">加载中...</span></td>
                        <td><span id="ua_<?=$v1['name']?>_lock">加载中...</span></td>
                        <td><span><a href="/user_exchange/coinin/name/<?=$v1['name']?>">充值</a>&nbsp;|&nbsp;<a href="/user_exchange/coinout/name/<?=$v1['name']?>">提现</a><?if($v1['block_url']) {?>&nbsp;|&nbsp;<a href="<?=$v1['block_url']?>" target="_blank">区块</a><?}?></span></td>
                    </tr>
                <? } ?>
                <tr>
                    <td><strong>总资产</strong></td>
                    <td colspan='3'><span id="ua_cny">计算中..</span> 元</td>
                </tr>
                </tbody>
            </table>
            <script type="text/javascript">
                ua_refresh(userPairs);
                setInterval(refresh, 6000);

                function refresh(){
                    ua_refresh(userPairs);
                }
            </script>
		</div>
	</div>
</div>
