<div class="RightBox">
	<div class="wrap">
		<div class="box">
			<div class="TitleBox">
				<h3 class="PlateTitle">修改登录密码</h3>
			</div>
			<form class="form-horizontal uadd_pwdfm" id="form" method="post" onsubmit="return changePwd();">
				<? if(isset($msg_updated)){?>
				<div class="rePWBtn" style="font-size:14px;color:red;">您的操作太快了，请休息一会儿吧！
				</div><?}?>
				<!-- 登录密码 -->
				<div class="buyText clear rePW">
					<span><b class="importantB">*</b>登录密码：</span>
					<input type="password" value="" id="oldpwd" name="oldpwd" class="loginValue" placeholder="请输入您当前的登录密码">
					<!--<b class="<?= isset($msg_oldpwd)? 'false': 'phone' ?>" id="oldpwdmsg"><?=isset($msg_oldpwd)? $msg_oldpwd: '请输入您当前的登录密码'?></b>-->
				</div>
				<!-- 密码 -->
				<div class="buyText clear rePW">
					<span>新登录密码：</span> <input type="password" value="" id="pwd" name="pwd" class="loginValue" placeholder="不修改请留空">
					<!-- <b class="phone" id="pwdmsg">不修改请留空</b> -->
				</div>
				<!-- 重复密码 -->
				<div class="buyText clear rePW">
					<span>再次输入新密码：</span> <input type="password" value="" id="repwd" name="repwd" class="loginValue" placeholder="不修改请留空">
					<!-- <b class="<?= isset($msg_repwd)? 'false': 'phone' ?>" id="repwdmsg"><?=isset($msg_repwd)? $msg_repwd: '不修改请留空'?></b> -->
				</div>

				<div class="buyText clear rePW">
					<span>验证码：</span><input style="width:138px;" class="loginValue signinCode" name="captcha" id="captcha" placeholder="请输入验证码">
					<img id="captchaimg" src="/index/captcha?t=<?=rand(100000, 999999)?>" style="float:left;margin-left: 10px;"> <a id="changeCode" href="javascript:void(0);" onclick="$('#captchaimg').attr('src', '/index/captcha?t='+Math.random())" style="float:left; line-height:40px; padding-left:10px;">看不清，再换一张</a>
				</div>
				<div class="buyText clear rePW"> <span>手机验证码：</span>
					<input type="code" name="code" id="code" value="" class="loginValue">
				</div>
				<div class="phone_verify clearfix">
					<a class="aButton1 left" onclick="verifySub(this,7,'人民币');">获取短信验证码</a>
					<a class="aButton1 right" onclick="verifySub(this,8,'人民币');">获取语音验证码</a>
				</div>

				<!-- error Tips -->
				<div class="errorTips userinfoErrorTips" id="errorTips" style="display: <?=isset($errorTips) ? 'block' : 'none'; ?>;"><?=isset($errorTips) ? $errorTips : ''; ?></div>

				<!-- 注册按钮 -->
				<div class="rePWBtn">
					<input type="submit" value="保存" class="rePWButton">
					<? if(isset($msg_ok)){ ?>
						<a class="save" href="#">保存成功</a>
					<? }?>
				</div>
			</form>
		</div>
	</div>
</div>
<script>
function changePwd() {

	var pLen = $('#oldpwd').val().length;
	if(pLen < 6 || pLen > 20) {
		$('#errorTips').html('原始密码长度在6-20个字符之间').show();
		return false;
	}

	var pwdLen = $('#pwd').val().length;
	if(pwdLen < 6 || pwdLen > 20) {
		$('#errorTips').html('新密码长度在6-20个字符之间').show();
		return false;
	}

	var repwdLen = $('#repwd').val().length;
	if(repwdLen < 6 || repwdLen > 20) {
		$('#errorTips').html('重复密码长度在6-20个字符之间').show();
		return false;
	}

	if($('#pwd').val() != $('#repwd').val()) {
		$('#errorTips').html('新登录密码不一致，请重新输入').show();
		return false;
	}

	return true;
}
// 验证码
function verifySub(obj, num, name){
	if( !$('#captcha').val() ){
		$('#errorTips').html('请填写图形验证码').show();
		return false;
	}
	$.post('/user_exchange/verifycheck', {'captcha':$('#captcha').val()}, function(data){
		if( data == 'fail' ){
			$('#errorTips').html('图形验证码错误').show();
			return false;
		}
		sendmsg(obj, num, name);
	})
}
</script>
