<table width="648" cellspacing="0" cellpadding="0" border="0" align="center" style="margin: 25px auto;">
    <tbody>
        <tr><td style="color:#40AA53;"><h1 style="margin-bottom:10px;">币交所</h1></td></tr>
        <tr>
            <td style="border-left: 1px solid #D1FFD1; padding: 20px 20px 0px; background: none repeat scroll 0% 0% #ffffff; border-top: 5px solid #40AA53; border-right: 1px solid #D1FFD1;">
                <p>{name}, 您好 </p>
            </td>
        </tr>
        <tr>
            <td style="border-left: 1px solid #D1FFD1; padding: 10px 20px; background: none repeat scroll 0% 0% #ffffff; border-right: 1px solid #D1FFD1;">
                <p>您已经成功注册为<strong>币交所</strong>会员！</p>
                <p style="font-weight:bold">请点击以下链接激活此帐号：<br>
                    <a href="{activate_url}" target="_blank">{activate_url}</a></p>
            </td>
        </tr>
        <tr>
            <td style="border-bottom: 1px solid #D1FFD1; border-left: 1px solid #D1FFD1; padding: 0px 20px 20px; background: none repeat scroll 0% 0% #ffffff; border-right: 1px solid #D1FFD1;">
                <hr style="color:#ccc;">
            </td>
        </tr>
    </tbody>
</table>
