<?php include PATH_TPL."/manage/tpl.header.phtml"?>
<div class="mod">
	<div class="hd">
		<h3 class="title">消息列表</h3>
		<form style="float:right">
			<input name="kw" value="<?if(isset($_GET['kw']))echo $_GET['kw']?>">
			<select id="yaf_field" name="field">
				<option value="uid">uid</option>
			</select>
      <script>$('#yaf_field').val('<?=isset($_GET['field'])?$_GET['field']:'uid'?>')</script>
			<input type="submit" value="搜索">
		</form>
	</div>
	<div class="bd">
	<table class="table_s01">
		<thead>
			<tr>
				<th>ID</th>
				<th>主题ID</th>
				<th>接收人UID</th>
				<th>发送时间</th>
				<th>阅读状态</th>
				<th>更新时间</th>
			</tr>
		</thead>
		<tbody>
		<? foreach($datas as $v1){?>
		<tr>
			<td><?=$v1["id"]?></td>
			<td><?=$v1["mid"]?></td>
			<td><?=$v1["uid"]?></td>
			<td><?=date('Y-m-d H:i:s', $v1["ctime"])?></td>
			<td><?=$v1["status"]?'已读':'未读'?></td>
			<td><?=date('Y-m-d H:i:s', $v1["utime"])?></td>
		</tr>
		<?php }?>
		</tbody>
	</table>
	<?=$pageinfo?>
	</div>
</div>
</body>
</html>