<?php include PATH_TPL . "/manage/tpl.header.phtml" ?>
<form method="post">
  <fieldset>
    <legend><h3 class="title">用户</h3></legend>
    <table class="formtable">
      <tbody>
			<tr>
				<th>用户ID</th>
				<td><input name="uid" value="<?=$uid?$uid:(isset($data)?$data['uid']:'')?>"/></td>
			</tr>
      <tr>
        <th>充值方式</th>
        <td>
					<select name="accounttype">
						<option value="支付宝">支付宝</option>
						<option value="财付通">财付通</option>
						<option value="银行卡">银行卡</option>
					</select>
        </td>
      </tr>
      <tr>
        <th>金额</th>
        <td><input name="money"/></td>
      </tr>
			<tr>
				<th>姓名</th>
				<td><input name="name"/></td>
			</tr>
      <tr>
        <th>账号</th>
        <td><input name="account"/></td>
      </tr>
      <tr>
        <th>订单号</th>
        <td><input name="order"/></td>
      </tr>
      <tr>
        <th>开户行</th>
        <td><input name="bank"/></td>
      </tr>
      </tbody>
    </table>
  </fieldset>
	<fieldset><input class="submit" type="submit" value="生成"></fieldset>
</form>
</body>
</html>