<?php include PATH_TPL."/manage/tpl.header.phtml"?>
<style>
.form{height:40px; line-height:40px;}
.date{width:200px; height:16px; line-height:16px; padding:5px; border:2px #AA9FFF solid; cursor:pointer; background:url(../images/dateIco.png) no-repeat right center;}
.calender{ width:200px; margin:50px auto; top:0; left:0; border:4px #D6D6D6 solid; background:#EBEBEB; position:absolute; display:none; z-index:999;}
.calendertb{width:100%;}
.calendertb td{width:35px; height:30px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; font-size:14px; font-weight:bold;}
.calendertb td.hover,.calendertb td.weekendhover{background:#D6D6D6;}
.calendertb th{width:35px; height:30px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; color:#979797; }
.tdtoday{ background:#0080FF;color:#fff;width:35px; height:35px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; font-size:14px; font-weight:bold;}
.getyear{ height:35px; line-height:35px; width:100%; text-align:center;}
.preMonth{ font-size:14px; font-weight:bold; cursor:pointer; margin-right:18px;color:#0080FF;}
.nextMonth{ font-size:14px; font-weight:bold; cursor:pointer; margin-left:18px;color:#0080FF;}
.zhezhao{width:100%; height:100%; position:fixed; z-index:998;	background:#fff;filter:alpha(opacity=10);opacity:0.1; display:none; }
.select{width:150px; height:24px; border:2px #AA9FFF solid;}
input{padding-left:10px;padding-right:10px;margin-right:30px;}
</style>
<div class="mod">
	<div class="hd">
		<h3 class="title">礼品卡</h3>
	</div>
	<div class="hd" style="height:40px;">
	<form action="#" method="get" id="form">
		<div class="form">
			批次号:<select name="pid" class="select">
					<option value="">全部</option>
					<?foreach($pid as $v){?>
						<option value="<?=$v['pid']?>" <?if(isset($_GET['pid']) && $_GET['pid'] == $v['pid']){echo 'selected';}else{'';}?>><?=$v['pid']?></option>
    				<?}?>
			</select>
			<input type="submit" name="sub" value="搜索"/>
			<input type="submit" name="sub" value="导出" onclick="$('form').attr('method', 'post')"/>
		</div>
	</form>
	</div>
	<div class="bd">
	<table class="table_s01">
		<thead>
			<tr>
				<th>id</th>
				<th>批次号</th>
				<th>卡号</th>
				<th>密码</th>
				<th>金额</th>
				<th>状态</th>
				<th>创建时间</th>
				<th>更新时间</th>
			</tr>
		</thead>
		<tbody>
		<?//$type=array('未导出', '已导出', '已售出', '已发货', '已使用')
		$type=array('未导出', '已导出', '已售出', '已发货', '未使用','已使用')?>
			<?foreach($datas as $v){?>
			<tr>
				<td><?=$v['id']?></td>
				<td><?=$v['pid']?></td>
				<td><?=$v['card']?></td>
				<td><?//=$v['pwd']?></td>
				<td><?=$v['money']?></td>
				<td><?=$type[$v['status']]?></td>
				<td><?=date('Y-m-d H:i:s', $v['ctime'])?></td>
				<td><?=date('Y-m-d H:i:s', $v['utime'])?></td>
			</tr>
			<?}?>
		</tbody>
		</table>
		<?=$pageinfo?>
	</div>
</div>
</body>
<script type="text/javascript" src="/js/jquery/date.1.0.js"></script>
<script type="text/javascript">
$(function (){
	$("input.date").manhuaDate({					       
		Event : "click",//可选				       
		Left : 0,//弹出时间停靠的左边位置
		Top : -16,//弹出时间停靠的顶部边位置
		fuhao : "-",//日期连接符默认为-
		isTime : false,//是否开启时间值默认为false
		beginY : 2010,//年份的开始默认为1949
		endY :2015//年份的结束默认为2049
	});
	
});
</script>
</html>
