<?php include PATH_TPL . "/manage/tpl.header.phtml" ?>
<style>
.loginValue{border: 1px solid #D5D5D5;float: left;height: 29px;line-height: 29px;margin-right: 15px;padding: 3px;width: 224px;}
.date{ cursor:pointer; background:url(../images/dateIco.png) no-repeat right center;}
.calender{ width:200px; margin:50px auto; top:0; left:0; border:4px #D6D6D6 solid; background:#EBEBEB; position:absolute; display:none; z-index:999;}
.calendertb{width:100%;}
.calendertb td{width:35px; height:30px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; font-size:14px; font-weight:bold;}
.calendertb td.hover,.calendertb td.weekendhover{background:#D6D6D6;}
.calendertb th{width:35px; height:30px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; color:#979797; }
.tdtoday{ background:#0080FF;color:#fff;width:35px; height:35px;border:1px #CCCCCC solid; text-align:center; vertical-align:middle; cursor:pointer; font-size:14px; font-weight:bold;}
.getyear{ height:35px; line-height:35px; width:100%; text-align:center;}
.preMonth{ font-size:14px; font-weight:bold; cursor:pointer; margin-right:18px;color:#0080FF;}
.nextMonth{ font-size:14px; font-weight:bold; cursor:pointer; margin-left:18px;color:#0080FF;}
.zhezhao{width:100%; height:100%; position:fixed; z-index:998;	background:#fff;filter:alpha(opacity=10);opacity:0.1; display:none; }
.select{width:100px; height:24px; border:2px #AA9FFF solid;}
</style>
<form method="post">
  	<fieldset>
    		<legend><h3 class="title">用户</h3></legend>
    		<table class="formtable">
      			<tbody>
				<tr>
					<th>数量</th>
					<td><input name="num" class="loginValue" value=""/></td>
				</tr>
				<tr>
					<th>金额</th>
					<td><input name="money" class="loginValue" /></td>
				</tr>
      			<!--	<tr>
        				<th>充值方式</th>
        				<td>
						<select name="accounttype">
							<option value="支付宝">支付宝</option>
							<option value="财付通">财付通</option>
							<option value="银行卡">银行卡</option>
						</select>
        				</td>
      				</tr>
      				<tr>
        				<th>过期时间</th>
        				<td><input name="time" class="date loginValue" /></td>
      				</tr>-->
      			</tbody>
    		</table>
  	</fieldset>
	<fieldset><input class="submit" type="submit" value="生成"></fieldset>
</form>
</body>
<script src="/js/jquery/date.1.0.js" type="text/javascript"></script>
<script type="text/javascript">
$(function (){
	$("input[name='time']").manhuaDate({					       
		Event : "click",//可选				       
		Left : 0,//弹出时间停靠的左边位置
		Top : -16,//弹出时间停靠的顶部边位置
		fuhao : "-",//日期连接符默认为-
		isTime : false,//是否开启时间值默认为false
		beginY : 2010,//年份的开始默认为1949
		endY :2015//年份的结束默认为2049
	});
	
});
</script>
</html>
