<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="<?php  echo host()?>/css/admin/style.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?php  echo host()?>/js/jquery/wvke.js"></script>
<script type="text/javascript" src="<?php  echo host()?>/js/jquery/1.9.1.min.js"></script>
<script type="text/javascript" src="<?php  echo host()?>/editor/ueditor/editor_config.js"></script>
<script type="text/javascript" src="<?php  echo host()?>/editor/ueditor/editor_all.js"></script>
</head>
<body class="iframe_page">

<?php 
/**
 * 搜索表单
 * @param array $pField 搜索字段
 */
function search_form($pField, $pAction=''){ ?>
<form style="float:right"<?php if($pAction)echo ' action="'.$pAction.'"'?>>
	<input name="kw" value="<?php if(isset($_GET['kw']))echo $_GET['kw']?>">
	<select id="yaf_field" name="field">
    <?php  foreach ($pField as $k1 => $v1) {?>
		<option value="<?php  echo $k1?>"><?php  echo $v1?></option>
    <?php  }?>
	</select>
  <?php  if(isset($_GET['field'])){ ?>
	<script>$('#yaf_field').val('<?php  echo $_GET['field']?>')</script>
  <?php  } ?>
	<input type="submit" value="搜索">
</form>
<?php  } ?>
