<?php include PATH_TPL."/manage/tpl.header.phtml";?>
<? $allCoins = User_CoinModel::getInstance()->getList(); ?>
<div class="mod">
	<div class="hd">
		<select onchange='window.location.href = "/manage_coins/have/status/<?=$status?>/coin/"+this.value' class="title" style="width: 100px;height: 30px;font-size: 18px;font-weight: bolder;margin-left: 10px;">
			<? foreach ($allCoins as $key => $value) { ?>
				<option value="<?=$value['name']?>" <?if($value['name']==$coin){?>selected<?}?> ><?=$value['display']?></option>
			<? } ?>
		</select>
		<ul class="tabs">
			<li<?if(0==$status) echo ' class="cur"'?>><a href="/manage_coins/have/status/<?=urlencode('0')?>">全部</a></li>
			<li<?if(1==$status) echo ' class="cur"'?>><a href="/manage_coins/have/status/<?=urlencode('1')?>">去除官方</a></li>
		</ul>
	</div>
	<div class="bd">
	<table class="table_s01">
		<thead>
			<tr>
				<th>排名</th>
				<th>UID</th>
				<th>邮箱</th>
				<th>姓名</th>
				<th>手机</th>
				<th>总量/<?=$coin?></th>
				<th>可用/<?=$coin?></th>
				<th>冻结/<?=$coin?></th>
				<th style="min-width: 150px;">注册时间</th>
			</tr>
		</thead>
		<tbody>
		<? foreach($datas as $k1=>$v1){?>
			<tr>
				<td><?=$k1+1?></td>
				<td><?=$v1["uid"]?></td>
				<td><?=$v1["email"]?></td>
				<td><?=$v1["name"]?></td>
				<td><?=$v1["mo"]?></td>
				<td><?=$v1["total"]?></td>
				<td><?=$v1["over"]?></td>
				<td><?=$v1["lock"]?></td>
				<td><?=date('Y-m-d H:i:s', $v1["created"])?></td>
			</tr>
		<?php }?>
		</tbody>
	</table>
	</div>
</div>
</body>
</html>
