<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<? isset($seot) || $seot = isset($this->layout['seot']) ? $this->layout['seot'] : '币交所-数字货币交易平台'; ?>
	<title><?=$seot?></title>
	<meta name="keywords" content="币交所,虚拟货币,虚拟货币交易平台,多币种,数字货币,富途币,比特币,莱特币,富途币行情,富途币交易,买富途币,购买富途币" />
	<meta name="description" content="币交所是一个多币种数字货币交易平台,目前提供富途币、比特币、莱特币等实时在线交易" />
	<meta content="telephone=no,email=no" name="format-detection">
	<link href="<?=host()?>/css/newstyle.css?v=1" rel="stylesheet"/>
	<script src="<?=host()?>/js/jquery/1.9.1.min.js"></script>
	<!-- <script src="<?=host()?>/js/index.js?v=45"></script> -->
	<script src="<?=host()?>/js/index.js?v=48"></script>
	<script src="<?=host()?>/js/tab.js"></script>
	<style>
		.header_asset div{float: left;margin-right: 20px;}
		.asset_dis{display: inline-block;height: 20px;padding: 0px 10px;line-height: 20px;background: #faad09;text-align: center;border-radius: 3px;color: #fff;}
		.asset_coin{margin-left: 10px;color:#676767;}
	</style>
	<!--[if IE 6]><script src="js/DD_belatedPNG_0.0.8a.js"></script><![endif]-->
	<script type="text/javascript">
	<? # 用户信息(模板初始化)
	isset($user) || $user = empty($this->layout['user'])? array(): $this->layout['user'];
	if($user){?>
		user = {uid:<?=$user['uid']?>, email:'<?=$user['email']?>', name:'<?=$user['name']?>'};
		<?foreach($user as $k=>$v){
			if(strpos($k, '_over') !== false || strpos($k, '_lock') !== false){?>
				user['<?=$k?>'] = '<?=$v?>';
		<?	}
		}
	}else{ ?>
		user = {};
	<? } ?>
	</script>
	</head>
	<body>
		<div class="topheaderWrap">
			<div class="topheader">
				<!--左边成交信息-->
				<div class="topheaderleft">
					<div class="kftel">客服电话：400-051-8422</div>
					<!--<div class="newcoin">
						<a href="/upcoin.html">上新币</a>
					</div>-->

					<!-- <? isset($allCoins) || $allCoins = empty($this->layout['allCoins'])? array(): $this->layout['allCoins'];
					if($allCoins){ ?>
					<div class="topslidenav">
						<ul class="topslideul">
							<li title="<?=$allCoins[0]['display']?>(<?=strtoupper($allCoins[0]['coin_from'])?>) -<?=$allCoins[0]['display_to']?>(<?=strtoupper($allCoins[0]['coin_to'])?>)">
								<a href="/trade/<?=$allCoins[0]['name']?>">
									<img src="/img/coin_<?=$allCoins[0]['coin_from']?>.png" alt="<?=$allCoins[0]['display']?>" style="width: 18px; margin-right: 10px;" />
									<span><?=$allCoins[0]['display']?>(<?=strtoupper($allCoins[0]['coin_from'])?>) -<?=$allCoins[0]['display_to']?>(<?=strtoupper($allCoins[0]['coin_to'])?>)</span>
								</a>
							</li>
							<li title="最新成交价">
								<a href="/trade/<?=$allCoins[0]['name']?>">
									<img src="/img/hdanjia.png" alt="<?=$allCoins[0]['display']?>"/>
									<span>¥<?=(float)$allCoins[0]['info']['now_price']?></span>
								</a>
							</li>
							<li title="买一价">
								<a href="/trade/<?=$allCoins[0]['name']?>">
									<img src="/img/hzficon.png" alt="<?=$allCoins[0]['display']?>"/>
									<span><?=sprintf('%.'.$allCoins[0]['info']['price_float'].'f', (float)$allCoins[0]['info']['buy_one'])?></span>
								</a>
							</li>
							<li title="卖一价">
								<a href="/trade/<?=$allCoins[0]['name']?>">
									<img src="/img/hdficon.png" alt="<?=$allCoins[0]['display']?>"/>
									<span><?=sprintf('%.'.$allCoins[0]['info']['price_float'].'f', (float)$allCoins[0]['info']['sale_one'])?></span>
								</a>
							</li>
							<li title="24H成交量">
								<a href="/trade/<?=$allCoins[0]['name']?>">
									<img src="/img/huachengjiao.png" alt="<?=$allCoins[0]['display']?>"/>
									<span><?=(float)$allCoins[0]['info']['day_total']?></span>
								</a>
							</li>
						</ul>
					</div>
					<? } ?>
					<? if(count($allCoins)>1){ ?>
					<div class="toprightsj"></div>
					<div class="hideinfoslide">
						<? for ($i=1; $i<$count=count($allCoins); $i++) { ?>
							<div class="topslidenav">
								<ul class="topslideul">
									<li title="<?=$allCoins[$i]['display']?>(<?=strtoupper($allCoins[$i]['coin_from'])?>)-<?=$allCoins[$i]['display_to']?>(<?=strtoupper($allCoins[$i]['coin_to'])?>)">
										<a href="/trade/<?=$allCoins[$i]['name']?>">
											<img src="/img/coin_<?=$allCoins[$i]['coin_from']?>.png" alt="<?=$allCoins[$i]['display']?>" style="width: 18px; margin-right: 10px;" />
											<span><?=$allCoins[$i]['display']?>(<?=strtoupper($allCoins[$i]['coin_from'])?>)-<?=$allCoins[$i]['display_to']?>(<?=strtoupper($allCoins[$i]['coin_to'])?>)</span>
										</a>
									</li>
									<li title="最新成交价">
										<a href="/trade/<?=$allCoins[$i]['name']?>">
											<img src="/img/hdanjia.png" alt="<?=$allCoins[$i]['display']?>"/>
											<span><? if($allCoins[$i]['info']['now_price']){echo '¥'.(float)$allCoins[$i]['info']['now_price'];}else{echo '0';} ?></span>
										</a>
									</li>
									<li title="买一价">
										<a href="/trade/<?=$allCoins[$i]['name']?>">
											<img src="/img/hzficon.png" alt="<?=$allCoins[$i]['display']?>"/>
											<span><?=sprintf('%.'.$allCoins[$i]['info']['price_float'].'f', (float)$allCoins[$i]['info']['buy_one'])?></span>
										</a>
									</li>
									<li title="卖一价">
										<a href="/trade/<?=$allCoins[$i]['name']?>">
											<img src="/img/hdficon.png" alt="<?=$allCoins[$i]['display']?>"/>
											<span><?=sprintf('%.'.$allCoins[$i]['info']['price_float'].'f', (float)$allCoins[$i]['info']['sale_one'])?></span>
										</a>
									</li>
									<li title="24H成交量">
										<a href="/trade/<?=$allCoins[$i]['name']?>">
											<img src="/img/huachengjiao.png" alt="<?=$allCoins[$i]['display']?>"/>
											<span><?=(float)$allCoins[$i]['info']['day_total']?></span>
										</a>
									</li>
								</ul>
							</div>
							<? } ?>
						</div>
					<? } ?> -->
				</div>
				<!--右边语言网站地图-->
				<div class="topheaderright" <?if($user){?>style="width:auto;"<?}?>>
					<? if($user){?>
					<div class="topinfo">
						<div class="infoEmail">
							<span>您好，<? if($user['name']){echo $user['name'];}else{echo substr($user['email'], 0, 3).'****'.substr($user['email'], strpos($user['email'], '@'));} ?></span>
						</div>
						<div class="infoHideDiv">
							<h3><? echo substr($user['email'], 0, 3).'****'.substr($user['email'], strpos($user['email'], '@')) ; ?></h3>
							<div>
								<span>UID：<?=$user['uid']?></span>
								<a href="/user_index/userinfo">设置</a>
							</div>
						</div>
					</div>
					<? } ?>
					<div class="topwapmap">
						<span class="hspannav">网站导航</span>
						<div class="wapmaplist">
							<div class="mapchangyong">
								<h2>常用</h2>
								<ul>
									<li><a href="/guide.html">新手引导</a></li>
									<li><a href="/faq.html">常见问题</a></li>
									<li><a href="/contactus.html">联系我们</a></li>
								</ul>
							</div>
							<div class="maptrade">
								<h2>交易中心</h2>
								<ul>
									<li><a href="/trade/btc_cny">比特币</a></li>
									<li><a href="/trade/ltc_cny">莱特币</a></li>
									<li><a href="/trade">富途币</a></li>
								</ul>
							</div>
							<div class="mapusercen">
								<h2>用户中心</h2>
								<ul>
									<li><a href="/user_index/twofactor">安全设置</a></li>
									<li><a href="/user_order/list">交易记录</a></li>
									<li><a href="/upcoin.html">上新币</a></li>
								</ul>
							</div>
						</div>
					</div>

					<div class="toplanguage">
						<img src="/img/hcountry.png" alt="中文" class="hcurimg" />
						<div class="hselectlang">
							<ul>
								<li>
									<a href="javascript:;">
										<img src="/img/hcountry.png" alt="中文" />
										<span>中文</span>
									</a>
								</li>
								<!-- <li>
									<a href="javascript:;">
										<img src="/img/usa.png" alt="英文" />
										<span>English</span>
									</a>
								</li> -->
							</ul>
						</div>
					</div>
					<? if($user){ ?><a class="infoLogout" href="/user/logout">退出</a><? } ?>
				</div>
			</div>
		</div>
		<div class="header_area">
			<!-- <div class="header" style="width: <?=REDIRECT_URL == '/trade' ? 1200 : 1000?>px;"> -->
			<div class="header">
				<div class="indexlogo" style="float:left;padding: 5px 0">
					<a href="/" style="display: block;margin: 14px 10px 0 0;">
						<img src="/img/fullLogo.png" alt="币交所" />
					</a>
				</div>
				<div class="navBox left">
					<ul class="nav">
						<?
						$top_menu = array(
							'/' => '首页',
							'/trade' => '交易中心',
							'/user_index'=>'个人中心',
							'/upcoin.html'=>'上新币',
							);
						foreach($top_menu as $k1 => $v1){?>
						<li>
							<a<?if(REDIRECT_URL==$k1){?> class="navActive"<?}?> href="<? echo $k1; ?>"><?=$v1?></a>
							<!-- <? isset($allCoins) || $allCoins = empty($this->layout['allCoins'])? array(): $this->layout['allCoins']; ?> -->
							<?if($k1=='/trade'){?>
								<div class="typeList">
									<!-- <? foreach ($allCoins as $k2 => $v2) { ?>
									<p onclick="javascript:window.location.href='/trade/<?=$v2['name']?>';">
										<img src="/img/coin_<?=$v2['coin_from']?>.png" alt=""/>
										<span><?=$v2['display']?>(<?=strtoupper($v2['coin_from'])?>)</span>
									</p>
									<? } ?> -->
									<p onclick="javascript:window.location.href='/trade/btc_cny';">
										<img src="/img/coin_btc.png" alt=""/>
										<span>比特币(BTC)</span>
									</p>
									<p onclick="javascript:window.location.href='/trade/ltc_cny';">
										<img src="/img/coin_ltc.png" alt=""/>
										<span>莱特币(LTC)</span>
									</p>
									<p onclick="javascript:window.location.href='/trade/goc_cny';">
										<img src="/img/coin_goc.png" alt=""/>
										<span>富途币(GOC)</span>
									</p>
									<!-- <p onclick="javascript:window.location.href='/trade/lc_cny';">
										<img src="/img/coin_lc.png" alt=""/>
										<span>金全币(LC)</span>
									</p> -->
									<p onclick="javascript:window.location.href='/trade/mtc_cny';">
										<img src="/img/coin_mtc.png" alt=""/>
										<span>美通币(MTC)</span>
									</p>
									<!-- <p onclick="javascript:window.location.href='/trade/uc_cny';">
										<img src="/img/coin_uc.png" alt=""/>
										<span>赢联通兑(UC)</span>
									</p> -->
									<p onclick="javascript:window.location.href='/trade/lbc_cny';">
										<img src="/img/coin_lbc.png" alt=""/>
										<span>直播币(LBC)</span>
									</p>
									<p onclick="javascript:window.location.href='/trade/dsc_cny';">
										<img src="/img/coin_dsc.png" alt=""/>
										<span>打赏币(DSC)</span>
									</p>
									<p onclick="javascript:window.location.href='/trade/gec_cny';">
										<img src="/img/coin_gec.png" alt=""/>
										<span>时代合约(GEC)</span>
									</p>
									<p onclick="javascript:window.location.href='/trade/mac_cny';">
										<img src="/img/coin_mac.png" alt=""/>
										<span>里程积分(MAC)</span>
									</p>
									<p onclick="javascript:window.location.href='/trade/lcc_cny';">
										<img src="/img/coin_lcc.png" alt=""/>
										<span>低碳币(LCC)</span>
									</p>
									<p onclick="javascript:window.location.href='/trade/tur_cny';">
										<img src="/img/coin_tur.png" alt=""/>
										<span>图灵币(TUR)</span>
									</p>
									<p onclick="javascript:window.location.href='/trade/ecf_cny';">
										<img src="/img/coin_ecf.png" alt=""/>
										<span>锎宝汇(ECF)</span>
									</p>
									<p onclick="javascript:window.location.href='/trade/osc_cny';">
										<img src="/img/coin_osc.png" alt=""/>
										<span>桂花积分(OSC)</span>
									</p>
									<!-- <p onclick="javascript:window.location.href='/trade/gec_cny';">
										<img src="/img/coin_gec.png" alt=""/>
										<span>时代合约(GEC)</span>
									</p> -->
								</div>
							<? }else if($k1=='/fulltrade/goc_cny'){ ?>
								<div class="typeList">
									<!-- <?foreach ($allCoins as $k3 => $v3) { ?>
									<p onclick="javascript:window.location.href='/fulltrade/<?=$v3['name']?>';">
										<img src="/img/coin_<?=$v3['coin_from']?>.png" alt=""/>
										<span><?=$v3['display']?>(<?=strtoupper($v3['coin_from'])?>)</span>
									</p>
									<? } ?> -->
									<p onclick="javascript:window.location.href='/fulltrade/btc_cny';">
										<img src="/img/coin_btc.png" alt=""/>
										<span>比特币(BTC)</span>
									</p>
									<p onclick="javascript:window.location.href='/fulltrade/ltc_cny';">
										<img src="/img/coin_ltc.png" alt=""/>
										<span>莱特币(LTC)</span>
									</p>
									<p onclick="javascript:window.location.href='/fulltrade/goc_cny';">
										<img src="/img/coin_goc.png" alt=""/>
										<span>富途币(GOC)</span>
									</p>
									<p onclick="javascript:window.location.href='/fulltrade/lc_cny';">
										<img src="/img/coin_lc.png" alt=""/>
										<span>金全币(LC)</span>
									</p>
									<p onclick="javascript:window.location.href='/fulltrade/mtc_cny';">
										<img src="/img/coin_mtc.png" alt=""/>
										<span>美通币(MTC)</span>
									</p>
									<p onclick="javascript:window.location.href='/fulltrade/uc_cny';">
										<img src="/img/coin_uc.png" alt=""/>
										<span>赢联通兑(UC)</span>
									</p>
									<p onclick="javascript:window.location.href='/fulltrade/lbc_cny';">
										<img src="/img/coin_lbc.png" alt=""/>
										<span>直播币(LBC)</span>
									</p>
									<p onclick="javascript:window.location.href='/fulltrade/dsc_cny';">
										<img src="/img/coin_dsc.png" alt=""/>
										<span>打赏币(DSC)</span>
									</p>
									<p onclick="javascript:window.location.href='/fulltrade/gec_cny';">
										<img src="/img/coin_gec.png" alt=""/>
										<span>时代合约(GEC)</span>
									</p>
									<p onclick="javascript:window.location.href='/fulltrade/mac_cny';">
										<img src="/img/coin_mac.png" alt=""/>
										<span>里程积分(MAC)</span>
									</p>
									<p onclick="javascript:window.location.href='/fulltrade/lcc_cny';">
										<img src="/img/coin_lcc.png" alt=""/>
										<span>低碳币(LCC)</span>
									</p>
								</div>
							<? } ?>
						</li>
						<? }?>
					</ul>
				</div>
				<div class="nt_user right">
					<? if($user){?>
						<? if( strpos(REDIRECT_URL, '/trade') !== false && strpos(REDIRECT_URL, '/trade') == 0 ){ ?>
						<div class="header_asset">
							<div>
								<span class="asset_dis">可用</span>
								<span class="asset_coin"><?=strtoupper($cData['coin_to'])?>：<span id="header_over_cny"><?=(float)$user[$cData['coin_to'].'_over']?></span></span>
								<span class="asset_coin"><?=strtoupper($cData['coin_from'])?>：<span id="header_over_<?=$cData['coin_from']?>"><?=(float)$user[$cData['coin_from'].'_over']?></span></span>
							</div>
							<div>
								<span class="asset_dis">冻结</span>
								<span class="asset_coin"><?=strtoupper($cData['coin_to'])?>：<span id="header_lock_cny"><?=(float)$user[$cData['coin_to'].'_lock']?></span></span>
								<span class="asset_coin"><?=strtoupper($cData['coin_from'])?>：<span id="header_lock_<?=$cData['coin_from']?>"><?=(float)$user[$cData['coin_from'].'_lock']?></span></span>
							</div>
						</div>
						<? } ?>
					<? } else {
						isset($isMobile) || $isMobile = empty($this->layout['isMobile'])? false : true;
					?>
						<div class="hello2">
							<a href="<? if($isMobile){echo 'http://m.bijiaosuo.com/user/login';}else{echo '/user/login';} ?>" class="hello_login">登录</a>
							<a href="<? if($isMobile){echo 'http://m.bijiaosuo.com//user/register';}else{echo '/user/register';} ?>"  class="hello_register">注册</a>
						</div>
					<? }?>
				</div>
			</div>
		</div>
