<table class="Transaction">
	<thead>
	<tr>
		<th></th>
		<th>可用余额</th>
		<th>冻结量</th>
	</tr>
	</thead>
	<tbody>
	<tr>
		<td><strong>人民币</strong></td>
		<td><span id="ua_cny_over">加载中...</span></td>
		<td><span id="ua_cny_lock">加载中...</span></td>
	</tr>
	<tr>
		<td><strong>富途币</strong></td>
		<td><span id="ua_goc_over">加载中...</span></td>
		<td><span id="ua_goc_lock">加载中...</span></td>
	</tr>
	<tr>
		<td><strong>总资产</strong></td>
		<td colspan='2'><span id="ua_cny">计算中..</span> 元</td>
	</tr>
	</tbody>
</table>

<script type="text/javascript">setInterval('ua_refresh()', 1000);</script>
