<div class="footer">
	<div class="copy_con clearfix" style="width: 1200px;">
		<div class="ftTopInfo">
			<div class="ftleftLogo floatleft">
				<a href="/">
					<img src="/img/ft_code.jpg" alt="币交所">
					<span>关注微信公众号</span>
				</a>
			</div>
			<div class="ftchangyong floatleft">
				<h2>常用</h2>
				<ul>
					<li><a href="/trade">交易中心</a></li>
					<li><a href="/guide.html">新手引导</a></li>
					<li><a href="/faq.html">常见问题</a></li>
					<li><a href="/contactus.html">联系我们</a></li>
				</ul>
			</div>
			<div class="ftzhengche floatleft">
				<h2>政策</h2>
				<ul>
					<li><a href="/service.html?type=1">免责声明</a></li>
					<li><a href="/service.html?type=2">法律声明</a></li>
					<li><a href="/service.html?type=3">注册协议</a></li>
					<li><a href="/service.html?type=4">费率说明</a></li>
				</ul>
			</div>
			<div class="onlineSer floatleft">
				<h2>在线客服</h2>
				<ul>
					<li><a href="tel:400-051-8422">客服电话：400-051-8422</a></li>
					<li><a href="tel:400-051-8422">监督电话：400-051-8422</a></li>
					<li>客服邮箱：kefu@bijiaosuo.com</li>
					<li>投诉邮箱：tousu@bijiaosuo.com</li>
				</ul>
			</div>
			<div class="onlineSer kefuQQ floatleft">
				<ul>
					<li>客服QQ1：1662906650</li>
					<li>客服QQ2：994984584</li>
					<li>官方交流群1：468312013</li>
					<li>官方交流群2：551833661</li>
					<li>官方交流群3：539791591</li>
				</ul>
			</div>
		</div>

		<div class="ftcopy">© 2016 Copyright 币交所</div>
	</div>
</div>
</body>
</html>
