<style>
.sellboxa a{width:86px;height:30px;line-height:24px;float:left;margin-left:20px;text-decoration:none; padding:5px 10px; color:#fff; font-weight:bold; font-size:14px;background: url(../images/submitBg.png) no-repeat scroll 0 0;}
.sellbox{margin: 5px auto 10px;width: 740px;overflow:hidden}
.sellmonyl{width:76px; float:left;}
.sellmonyr{width:664px; float:left;}
.sellmonyr p{height:22px;line-height:22px; font-size:13px; color:#FF0000}
</style>
<div class="RightBox">
	<div class="wrap">
		<div class="box">
			<div class="TitleBox">
				<h3 class="PlateTitle">礼品卡充值</h3>
			</div>
			<table class="payRMB">
				<tbody>
				<tr>
					<td colspan="3">
					<div class="sellbox">
						<div class="sellmonyl" style="padding:2px 0 0 10px;width:66px;height:20px;line-height:20px">充值须知：</div>
						<div class="sellmonyr" style="margin-top:2px;width:500px">
							<p>1.充值功能将于1月20日中午12点准时开放。</p>
							<p>2.充值前需要卡片处于激活状态。卡片将在您快递签收信息上网12小时内自动激活。</p>
							<p><span style="height:22px;line-height:22px;float:left">3.若您的签收信息上网24小时后仍未激活，请联系客服。</span><script charset="utf-8" type="text/javascript" src="http://wpa.b.qq.com/cgi/wpa.php?key=XzkzODAwMjI0M185NjI2MF80MDA4MzY3NjY3Xw"></script></p>
						</div>
					</div>
					</td>
				</tr>
                <tr><td colspan="3"><div class="buyText clear rePW"><input type="hidden" id="uidnum" value="<?php  echo $uid?>" />
				<span>充值密码：</span> <input name="number" id="pwdnum" class="loginValue" type="text" value=""><b class="rePWB">请输入15位充值密码</b>
			    <div class="rePWBtn">
				<button class="rePWButton" id="sub">充值</button>
                </div>
                </td></tr><tr>
				<td colspan="3"><div class="buyText clear rePW">
				<span>校验：</span> <input name="num" id="num" class="loginValue" type="text" value=""><b class="rePWB">请输入10位校验码</b>
			    <div class="rePWBtn">
				<button class="rePWButton" id="sub1">校验</button>
                </div>
                </td></tr>
				</tbody>
			</table>
 </p> <br> <br><br> <br> <br><br> <br>
		</div>
	</div>
</div>

<div class="RightBox">
	<div class="wrap">
		<div class="box">
			<div class="TitleBox">
				<h3 class="PlateTitle">充值记录</h3>
			</div>
			<table class="Transaction">
				<thead>
				<tr>
					<th>充值卡号</th>
					<th>充值时间</th>
					<th>充值金额</th>
				</tr>
				</thead>
				<tbody>
                <?php  if(!empty($datas)){?>
				<?php  foreach($datas as $v1){ ?>
					<tr>
						<td><?php  echo $v1['card']?></td>
						<td><?php  echo date('Y-m-d H:i', $v1['utime'])?></td>
						<td><?php  echo $v1['money']?></td>
					</tr>
				<?php  }?>
				<?php  }else{?>
					<tr>
						<td colspan=3>您还没有充值记录</td>
					</tr>
				<?php }?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<script type="text/javascript">
function bankconfirm(payid){
    if(!payid){
        return false;
    }
    var num = document.getElementById(payid).value.length;
    if(num != 15){
        alert('请输入15位充值密码');
        return false;
    }else{
        return true;
    }
}
$(document).ready(function(){
    $("#sub").click(function(){
        var pwd = $("#pwdnum").val();
        var uid = $("#uidnum").val();
        var data = {pwd:pwd, uid:uid};
        $.post('/user_info/cardin', data, function(txt){
            var msg = eval('('+txt+')');
            if(msg.err == 1){
                alert(msg.msg);
                window.location.href='';           
            }else{
                alert(msg.msg);
            } 
        })
    }) 
	 $("#sub1").click(function(){
        var num = $("#num").val();
        var data = {num:num};
        $.post('/user_info/cardin/s/1', data, function(txt){
            var msg = eval('('+txt+')');
            if(msg.err == 1){
                alert(msg.msg);
                window.location.href='';           
            }else{
                alert(msg.msg);
            } 
        })
    }) 
});

</script>
